### ISSUE TITLE
Location permission not requested if gallery permission denied when taking a new photo

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1029]
**Describe the bug**
Location permission not requested if gallery permission denied when adding an observation by taking a new photo with the StandardCamera.

**To Reproduce**
1. Follow the repro steps in #830 but when prompted for gallery permission, tap the "x" button in the upper right
2. You are not prompted to grant location permission and the permission never loads

Similarly, if you repeat the steps and when prompted for the gallery permission you tap the "Keep to add only" button, nothing happens when you tap the green check button.

**Expected behavior**
You should be prompted to grant location permission and location should be retrieved even if you refuse the gallery permission.

**Context (please complete the following information):**
 - Device: iPhone SE (3rd gen)
 - OS: iOS 17.2.1
 - App version: [v0.20.0+68](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.20.0%2B68)

**Comment by budowski** [comment]
@kueda - I tried recreating this in several ways, none worked (meaning, I always got the location permissions dialog):

Scenario 1:

1. Add observation (plus button)
2. Take photo (standard camera)
3. Approve
4. Location Permission shown

Scenario 2:

1. Add observation (plus button)
2. Import photo
3. Decline
4. Goes to ObsEdit and location Permission shown

Scenario 3:

1. Add observation (plus button)
2. No media, goes to ObsEdit
3. Add evidence -> exiting photos
4. Decline
5. Location permission shown
