### ISSUE TITLE
Offline suggestions don't work in Android

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1038]
**Describe the bug**
Offline suggestions don't work in Android

**To Reproduce**
1. Put the device in airplane mode
2. Import a photo of something you know the offline model will do well on
3. Tap "ADD AN ID" when you land on ObsEdit
4. On Suggestions, you get the activity indicator, but the offline suggestions never load

**Expected behavior**
Offline suggestions should load while offline

**Context (please complete the following information):**
 - Device: Pixel 8
 - OS: Android 14
 - App version: [v0.20.0+68](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.20.0%2B68)

**Additional context**
I'm fairly sure this is a bug in https://github.com/inaturalist/vision-camera-plugin-inatvision that I had to [work around](https://github.com/inaturalist/iNaturalistReactNative/pull/1025/files#diff-3eb02ad95f41c6eab40496101db1257c63de98e39479f2e0c9d17e9021131de1R32-R37) here because it was causing a crash, but I don't feel like I know enough about the problem to file an issue there. Clearly android.graphics.Bitmap.getWidth() is getting called on a null object, but I don't know how to replicate it only within the context of that package.

**Comment by joergmlpts** [comment]
That's odd: the parameter for the image is named `uri` but a URI is not supported on Android.  Parameter `uri` is passed to [`BitmapFactory.decodeFile`](https://developer.android.com/reference/android/graphics/BitmapFactory#decodeFile(java.lang.String)) which expects a file path.

Even when the parameter issue is fixed, the offline suggestion still crashes on Android: A list of predictions is the expected return value. But on Android an object with a single name, value pair is returned instead. The name is `predictions` and the value is the array of predictions.

**Comment by joergmlpts** [comment]
@kueda This should ideally be fixed in [https://github.com/inaturalist/vision-camera-plugin-inatvision](https://github.com/inaturalist/vision-camera-plugin-inatvision) but a workaround is available and I can file a pull request for it if desired.

**Comment by kueda** [comment]
Thanks for looking into it, @joergmlpts, but I'm more interested in fixing the problem in `vision-camera-plugin-inatvision`. If you can articulate the problem there in concrete terms, perhaps you could file an issue in that repo?

**Comment by joergmlpts** [comment]
@kueda I've tried to articulate the issue [there](https://github.com/inaturalist/vision-camera-plugin-inatvision/issues/10). The [pull request](https://github.com/inaturalist/vision-camera-plugin-inatvision/pull/11) for this issue has maybe a simpler description.
