### ISSUE TITLE
Explore Filters full screen experience should be a modal.

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#1065]

**Comment by kueda** [comment]
Wait, should it? In the designs it looks like a regular part of the nav hierarchy.

**Comment by jtklein** [comment]
Yes, I think it should be. I think the convention in the designs is, if the screen does not show the bottom tabs it should be a modal. Like for example the MediaViewer.

**Comment by kueda** [comment]
Not sure if you're still planning on doing this Angie but one additional requirement: the Android back button should close the modal. This should be the default behavior if you use `SharedComponents/Modal.js`, but make sure it works if you take a different approach.
