### ISSUE TITLE
SoundContainer player progress bar interactions

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1070]
The audio player in the SoundSlide component *shows* the current progress of the audio playback, but that progress bar doesn't let you seek ahead or back.

- [x] Tapping the bar should seek to that position
- [x] Dragging the current position indicator should seek to that position
- [x] Neither interaction should change the playing status, so if you tap the bar while playing, it should continue playing at that position, and if you tap the bar while not playing, it should not start playing

@abhasinat holler if you have a different opinion re: MVP status. IMO it feels a bit buggy not to support this basic audio player functionality.

**Comment by jtklein** [comment]
Have renamed SoundSlide to SoundContainer

**Comment by abhasinat** [comment]
All of this sounds good to me. Thanks, Ken-ichi.
