### ISSUE TITLE
PhotoCount misaligned or missing after scrolling on MyObservations

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1072]
**Describe the bug**
> Sometimes when scrolling, multi-photo observations lose the number of photos from the icon, or the number is misaligned

**To Reproduce**
No consistent repro steps, but it probably involves scrolling through several pages of observations on MyObservations.

**Expected behavior**
PhotoCount should always show the count and the number should never spill over the icon in the background.

**Screenshots**
<img width="302" alt="Screenshot 2024-01-22 at 3 16 54 PM" src="https://github.com/inaturalist/iNaturalistReactNative/assets/22691/fb4ff5e0-da47-4bcf-b695-33cead2c794b">

**Context (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 17.2.1
 - App version: 0.20.0

**Additional context**
I can't replicate this on my iPhone SE at the moment, but this has been happening for some time. #760 and #539 may be related.

**Comment by albullington** [comment]
I believe this is fixed via PR [#1112](https://github.com/inaturalist/iNaturalistReactNative/pull/1112), so closing for now.
