### ISSUE TITLE
Upload Photos and Sounds before ObservationPhotos and ObservationSounds

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#110]
On the web, we upload these records immediately when people drag them into the Uploader, and they become Photo and Sound records on the server that are, at least temporarily not connected to any observations, taxa, or whatever. This means that when we create the observation we can do so after having uploaded the large media files and decrease the likelihood that an observation will get created before it has any media.

As of https://github.com/inaturalist/iNaturalistAPI/commit/b5530fb6a0f24eda0cd933976918719e9d2bf805, this should be possible with API v2:

- [ ] When uploading an observation, use POST /v2/photos or POST /v2/sounds to upload media *before* creating the Observation, ObservationPhoto, or ObservationSound records
- [ ] When requesting POST /v2/observation_photos, just include the `photo_id` of the instead of the photo file
- [ ] Same with sounds

**Comment by kueda** [comment]
@budowski can you make a pull request for this if it's ready for review?

**Comment by budowski** [comment]
Sorry about that - I merged from latest `main` branch and created PR #395
