### ISSUE TITLE
Multiple common names appear differently on TaxonSearch and ObsEdit

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1104]
**Describe the bug**
When you have multiple common names enabled, they often appear differently on TaxonSearch vs ObsEdit

**To Reproduce**
1. On the web, set your Common Name Lexicon Display Order to match locale first (United States), then Korean: <img width="367" alt="Screenshot 2024-02-01 at 2 06 25 PM" src="https://github.com/inaturalist/iNaturalistReactNative/assets/22691/3c4ce20f-45f6-4f52-bab3-2e51beda0894">
2. In the app, start a new obs w/o evidence
3. Tap the ADD AN ID button
4. Tap the SEARCH FOR A TAXON button
5. Search for "bats"; I see this <img width="371" alt="Screenshot 2024-02-01 at 2 08 15 PM" src="https://github.com/inaturalist/iNaturalistReactNative/assets/22691/cc6a2ae4-b673-4869-9fc8-638c4b949733">, even though the taxon Chiroptera does have a Korean common name
6. Search for "vascular plants"; I see this: <img width="380" alt="Screenshot 2024-02-01 at 2 09 32 PM" src="https://github.com/inaturalist/iNaturalistReactNative/assets/22691/2f93ccca-5b16-4519-bbc8-a68a8666c07f">, which is what I'm expecting
7. Tap the green check button to choose Tracheophyta
8. On ObsDetail, the taxon is displayed with a single common name: <img width="377" alt="Screenshot 2024-02-01 at 2 10 27 PM" src="https://github.com/inaturalist/iNaturalistReactNative/assets/22691/a60ca841-9846-46f4-9e68-c1d13157b20b">

**Expected behavior**
TaxonSearch and ObsEdit should both show multiple common names if that's the user's preference, and the name should look the same on both screens.

**Context (please complete the following information):**
 - Device: Simulated iPhone 15 Pro
 - OS: iOS 17.2
 - App version: v0.21.1+70

**Additional context**
We don't do any handling of multiple common names in the app, so I suspect this is a matter of not requesting the correct data at the right time, or it's a problem with not authenticating API requests, or maybe it's a problem with the API or cached content from the API. If you've ruled out problems with the app, reach out to the web team to figure out if it's an API issue.

**Comment by kueda** [comment]
I can still reproduce this, @albullington. I am seeing *consistent* results now, but I am not seeing the multiple common names I'm expecting, e.g. when I search for "bats" the taxon Chiroptera appears third in the list despite the exact name match, and the Korean name does not appear.

Also, I would use the `/search` endpoint instead of the `/taxa/search` endpoint generally. If `/search` isn't serving up multiple common names, that's a server-side bug we need to fix. It should provide better ranked search results, and those results should match user's expectations from header search on the web (same endpoint).

**Comment by budowski** [comment]
Transitioned to use the general `/search` endpoint with `sources=taxa` - now the order of the results seems better (e.g. when searching for 'bats'). However, `preferred_common_name` returned does not contain the user's language settings (in this case, Korean), even though we do an authenticated request (@pleary).

**Comment by kueda** [comment]
Needs work from the web team.
