### ISSUE TITLE
Explore observations change when you return from ObsDetails

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1122]
**Describe the bug**
New observations load when you return to Explore from ObsDetails, making you lose your place in the list of observations you were reviewing.

**To Reproduce**
1. Go to Explore
2. Tap on the first observation and note its position in the list
3. Spend a few seconds on ObsDetails, e.g. scroll to the bottom of the ACTIVITY tab, scroll to the bottom of DETAILS, open the MediaViewer
4. Note the observation you're looking at (e.g. it's taxon and user) and tap the back button
5. You're back in Explore, but you're looking at a different set of observations. The observation you tapped is either no longer on screen or it's at a different position.

**Expected behavior**
When you tap an observation on Explore to get to ObsDetails and then tap back to get back to Explore, Explore should be in exactly the state you left it in and the observation you tapped should be in the same position on screen.

**Screenshots**
Tony recorded this: https://photos.app.goo.gl/zuAh1vSDXc38ELqdA

**Context (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 17.3
 - App version: v0.22.0+71

**Additional context**
From a user perspective, this is a pretty annoying bug that makes actually using Explore to identify observations very annoying, particularly if the set of observations you're reviewing is changing a lot, e.g. global unknowns.

Technically, this probably has to do with loading new observations every time Explore has focus, which pushes the results around and causes the screen to change, so some thoughts on how I think this should work

* Observations should be *replaced* when:
  * Filters change
  * First render of Explore
* Observations should be *appended* when
  * The user scrolls to the bottom of the list and we load more w/ infinite scroll
* Confusingly, we should only use the `page` param to achieve pagination when sorting by faves; when sorting by date added or date observed, each page is can always have different results at different times, so for consistent results we should instead use `created_d1` and `created_d2` when sorting by date added, and `d1` / `d2` when sorting by date observed, e.g. when you want the next page of results, you would look at the created_at value of the last observation and the next "page" of results would use created_d2=that-date.

**Comment by kueda** [comment]
Need to confirm but this might have been fixed in 4ccf9e750b886b1d97a296925fef51b41e6285a8

**Comment by jtklein** [comment]
Still happens in 0.26.0

**Comment by albullington** [comment]
Closing because this seems to be fixed via the navigation changes to Explore in [b284bb2](https://github.com/inaturalist/iNaturalistReactNative/commit/b284bb2b9ed3199aa7e1be69b3653b8b52568ff2).
