### ISSUE TITLE
Show a reveal button for the password field on Login

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1138]
This would help a lot of people sign in... including me.

- [ ] Show a text button to the lower left of the password field that reads "Reveal" using the same styling as "Forgot"
- [ ] Tapping the button should reveal the text in the password field
- [ ] Tapping the button should change the text of the button to "Hide"
- [ ] Tapping the "Hide" button should restore the original state of obscured text

**Comment by israr002** [comment]
https://github.com/user-attachments/assets/c92d2150-d99a-46c7-9c61-7a4d05316d45

@kueda @abhasinat Let me know if this change as per the expectation or anything else is needed

also one thing we can do like we can show reveal btn only once user starts entering password

**Comment by jtklein** [comment]
Hello @israr002 this looks good to me so far. I think it satisfies the issue here. If you open a pull request I can take a look at the code.

**Comment by israr002** [comment]
@jtklein i have raised a pull request for this feature
