### ISSUE TITLE
Filtering Explore for CC0 photos of captive obs shows 0 results

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1141]
**Describe the bug**
Filter Explore to show CC0 photos of captive observations shows no results, even though there are [quite a few](https://www.inaturalist.org/observations?captive=true&place_id=any&verifiable=any&photo_license=cc0) observations meeting these criteria.

**To Reproduce**
1. Go to Explore
2. Tap the filters button in the upper right
3. Set PHOTO LICENSING to CC0 and WILD STATUS to "Captive/Cultivated"
4. Tap "APPLY FILTERS"
5. Explore shows "No results found

**Expected behavior**
It should show the observations at https://www.inaturalist.org/observations?captive=true&place_id=any&verifiable=any&photo_license=cc0

**Context (please complete the following information):**
 - Device: iPhone SE (3rd gen)
 - OS: iOS 17.2.1
 - App version: 0.22.0 (71)

**Comment by jtklein** [comment]
I tried to replicate it with these steps and can do so. However, if you follow these steps exactly I think it is currently a feature to show no result and not a bug, because:
To see any "captive" observations one would also need to select "casual" in Quality Grade section.

So, we would need to rephrase the problem here.

**Comment by jtklein** [comment]
@abhasinat or @kueda let me know if this is not a bug, and/or if we should set Quality Grade automatically to "casual" whenever the user chooses "captive".
Then I can close or unblock this issue.

**Comment by kueda** [comment]
My vote is to set Quality Grad to casual when the user choose "captive."

**Comment by abhasinat** [comment]
This solution is fine with me if that feels easiest.

Though I do feel like they are separate parameters, as a user may see an observation of a wild organism without any evidence in this list, since that is casual as well.
