### ISSUE TITLE
Enable date range for DATE UPLOADED explore filter

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#1148]

**Comment by jtklein** [comment]
Currently, the designs only show date range as an option for Date Observed.
However, #1137  also specified to add this option to Date Uploaded.
@abhasinat is that really TODO?

**Comment by abhasinat** [comment]
yep, that was my mistake. both date observed and uploaded should have date range. I've updated the designs to reflect this.
