### ISSUE TITLE
SoundRecorder close button should always return to the previous screen

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1165]
This is a bit similar to the work Yaron did in #1109, so we could take that approach, but this would be a good time to investigate whether consolidating stack navigators might be an easier approach. One thing to keep in mind is that one of the reasons we have a separate stack navigator for add obs screens is so they can appear over the bottom tabs, so we don't want to lose that. Using react-navigations modal functionality generally breaks things in Android, I think.

**Comment by budowski** [comment]
This is no longer happening in latest version - probably because of merging of #1211 and #1109
