### ISSUE TITLE
Investigate disk usage

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1182]
Our app takes up a lot of space, arguably too much space. [v0.24.0+73](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.24.0%2B73) is 163 MB. @tiwane reported this disk usage screenshot from [v0.22.0+71](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.22.0%2B71):

![Image](https://github.com/inaturalist/iNaturalistReactNative/assets/22691/d92b7e50-b568-49d4-a726-473e1bfbe54b)

So this is mostly an informational issue, with some optional changes to the app:

- [ ] Why is the app binary so big? How much is coming from the vision model, and what is eating so much disk aside from the vision model?
- [ ] What is taking up 900MB  of "Documents & Data"? Audit what we're writing to disk and report on what takes up the most space

## Optional

Report this information *in the app*, starting with the Developer / Debug view. Maybe add a Disk Usage section and report the size of the of the model files, the directories in Documents & Caches and their disk usage. I think this might be useful user-facing info eventually, but for now it would help a lot if *we* could see it.

**Comment by albullington** [comment]
Reporting this in the Debug menu, and also made an [issue](https://github.com/inaturalist/iNaturalistReactNative/issues/1484) to address space concerns
