### ISSUE TITLE
Clicking the stats bar in the explore header should open the explore view picker

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1193]
Right now, the tab bar in the explore header is not clickable. both the header dark bar and the button in the bottom right should open the explore view picker.

<img width="1100" alt="Frame 320" src="https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/d4ccf169-6ec8-44e2-8959-1e896f84e5de">

**Comment by angielt** [comment]
Already done, closing issue.
