### ISSUE TITLE
Confetti animation doesn't load while offline

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1202]
**Describe the bug**
Confetti animation doesn't load while offline when importing photos

**To Reproduce**
1. Go into airplane mode
2. Start a photo import
3. No confetti

**Expected behavior**
Assuming we want to keep this animation, shouldn't it work while offline? Once you become acustomed to it, not seeing it there feels a bit broken.

**Screenshots**

**Context (please complete the following information):**
 - Device: iPhone SE (3rd gen)
 - OS: iOS 17.3.1
 - App version: 0.23.0 (73)

**Additional context**
Might want to check with @abhasinat about whether we really want to keep it in the first place.

**Comment by angielt** [comment]
Cannot replicate as of 0.45.0

**Comment by kueda** [comment]
Also can't replicate. Thanks, time.
