### ISSUE TITLE
Granting camera permission from Settings requires an app restart in Android

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1206]
**Describe the bug**
If you deny camera permissions, the app prompts you to open the Settings app to grant the permission. If you do so and return to the app, it still asks you to do the same thing.

**To Reproduce**
1. Fresh install of the app (or deny camera permission in Settings)
2. Enter the StandardCamera
3. You should see the camera permission gate
4. Tap OBSERVE ORGANISMS
5. Tap "Don't allow"
6. Tap OPEN SETTINGS
7. In the Settings app, grant camera permission (tap Permissions, tap Camera, tap "Allow only while using the app"
8. Return to iNat (I usually use the app switcher)
9. The permission gate still displays and is prompting you to open settings... even though you just did that
10. Tap the x button in the upper right to close
11. Enter the StandardCamera again
12. It's still asking you to open settings

**Expected behavior**
Once you've granted camera permission in Settings, iNat should realize that, e.g. when the permission gate has focus, it should check for the permission again.

**Context (please complete the following information):**
 - Device: Pixel 8
 - OS: Android 14
 - App version: 0.23.0 (72)

**Additional context**
Works on iOS, so be careful that any changes don't break this there.

**Comment by israr002** [comment]
@kueda Please assign this to me
