### ISSUE TITLE
Font Styling Fixes

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1209]
- [ ] Right now, all headings (Heading1, Heading2, Heading3, Heading4, Heading4 (non-default color), and Heading5) are all Whitney-Medium. They should all be Whitney-Semibold.
- [ ] Subheading1, Body2, Body4, and List 2 are all currently Whitney-Light. They should all be Whitney-Book.

**Comment by abhasinat** [comment]
Found one more!

Body 1 and List 1 should both be Whitney-Medium. But when they are italicized, it looks like Body 1 here is Whitney-Book-Italic. It should be Whitney-Medium-Italic:
![IMG_0728](https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/9dcfd76c-0032-4550-af27-16740ca76401)

- [ ] Please also make sure that all italicized versions for each font style use the same weight as their regular counterpart.

**Comment by angielt** [comment]
Should Body3 also be Whitney-Light?

**Comment by abhasinat** [comment]
Nope, Body1 and Body3 should be Whitney-Medium.
