### ISSUE TITLE
About screen image should have percentage of screen as width

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#1222]
Contrary to now, i.e. hardcoded pixel values for width and height, the image for the iNaturalist wordmark on the About screen should always be 65% of the screen width. The ratio should follow the current one.

**Comment by kueda** [comment]
Hopefully this looks ok:

<img width="1512" alt="Screenshot 2024-04-17 at 11 23 36 AM" src="https://github.com/inaturalist/iNaturalistReactNative/assets/22691/7a15dced-8258-4239-a6a6-d88c5b6d31fe">
