### ISSUE TITLE
LocationPicker minor bugs

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1224]
Stub for a few things that bother me in addition to #1077. Most of these are only apparent in the field, sadly.

- [ ] accuracy circle not showing in iOS
- [x] current location button doesn't exactly center the crosshairs on the current location marker in ios
- [ ] current location button is often not responsive in Android when the cross hairs are very close to the current location but not quite on it
- [x] android: map often pans back to a previous position when the current location updates (like not when you tap the current location button but when the current location marker changes its mind about your current location)
- [x] Yaron: zoom level resets when you zoom out quickly

**Comment by budowski** [comment]
Couldn't recreate some of these issues, fixed others. Note - the "zoom too quickly" issue is still occurring, seems like the `onRegionChangeComplete` callback of the `MapView` component gets triggered multiple times for semi-older values, when zooming out quickly (we basically set the MapView's region while zooming out, but if this happens too quickly, while the user zooms out again, that callback gets triggered again, based on older values - so it seems like some sort of race condition within the `MapView`component.

**Comment by albullington** [comment]
@budowski can you make a separate github issue for any of the steps you couldn't complete here? that way we know what still needs fixing.

**Comment by budowski** [comment]
@albullington - done (#1383)

**Comment by kueda** [comment]
I'm going to close since we merged in the parts that worked diverted to another issue.
