### ISSUE TITLE
Closed Alpha Test

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1253]
We want to test with a broader group of non-staff, but we've got a few todos before we're ready for that.

- [x] #359
- [x] Make a new oauth client for an app named "iNat Beta", make sure if has an image that's the same as the app icon (https://www.inaturalist.org/oauth/applications/843)
- [x] Look into TestFlight options, make sure we can make an invite-only group w/ ~100 ppl
- [x] Update fastlane, probably need a new `alpha` lane that's basically like the `internal` lane but posts builds to new closed alpha audience
- [ ] TBD

**Comment by kueda** [comment]
Re testflight options,

1. Yes, we can make an invite-only group, and in fact we already have one called "iNat Friends"
2. All test groups can have up to 10,000 people
3. We can also make a public link for a test group and limit the number of members
4. Apparently if you take a screenshot of an app in TestFlight and tap it immediately, you get an option to share feedback that we can see in TestFlight. Really not-obvious, so if we want people to do this we'll need some instructions.

@abhasinat here's a proposal:

1. If there are particular users we want feedback from (maybe a few power users, a few casual users), we should invite them to the existing "iNat Friends" group and continue to treat that group as an invite-only group. We can continue to send them "internal" builds whenever we make new builds for staff.
2. Create a separate "Open Beta" group that has a public link and use this for in-person testing. We can make a QR code of the URL so people should be able to join the group and download the app relatively easily. This way you can do in-person testing using a variety of actual devices, plus we can share this a little more broadly if we'd like.

**Comment by abhasinat** [comment]
This sounds good.

I would use 2) primarily on usertesting.com. I will create tasks for users to download the beta on their devices via a public URL and then screen record as they use it. This would be used for both casual users (who have never seen our apps before) and for power users (who we choose to send a link to).

For 1) I would keep this small, and create some sort of regular feedback mechanism akin to our weekly testing doc for those power users. I'm imagining power users who we send a link to in 2) could self-select or be selected for this group.

**Comment by kueda** [comment]
Ok, that's sorted, @abhasinat.

1. Closed alpha functionality supported through the "iNat Friends" group on TestFlight. Go to the TestFlight admin page to manually invite people
2. Open beta functionality supported through the "Open Beta" group on TestFlight. It has a public link that you can get from the TestFlight admin page

Do you want to make any other changes, like removing placeholder or "TODOs" from the app, or are we good?

**Comment by kueda** [comment]
I'll take that as a no.

**Comment by abhasinat** [comment]
I think removing placeholder TODOs would be great! I would just make sure they have corresponding issues in github already.
