### ISSUE TITLE
Location Icon associated with an observation should change based on geoprivacy across the app

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1266]
- [ ] Update the location pin icon's state to change depending on the observation's geoprivacy on every screen associated with that observation, including home screen/my observations, explore, and obs detail
- [ ] Ensure that the location section on obs detail as well as the location detail (map view) display properly based on geoprivacy and location permissions - there are designs for all states of the map view.

### Location Pin Updates: 3 states based on Geoprivacy
Right now, every observation has a location pin and a location associated with it. This shows up on the observations list, as well as on obsdetail under the photo at the very top. I would like for this location pin to change based on the geoprivacy of the observation.

Here's an example of viewing 3 observations in my observations with open, obscured, and private geoprivacy. I can see the locations because they are my observations.
<img width="752" alt="image" src="https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/0a08e252-4b78-48fc-a7d8-57dfc1ef22a8">

Here's an example of viewing other peoples' observations in explore: I can't see the location details because I don't have permissions to see the location, and I can see the pin change based on geoprivacy
<img width="590" alt="image" src="https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/d79dc2ba-8b39-426c-aed5-6948bee7d67a">

These location pin designs should appear everywhere that location pin appears in conjunction with an observation: My observations, explore (observations view), observation detail, location section on observation detail, and the map view on observation detail.

### Text and view of location section on obs detail and Map view
Please reference [these designs](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?type=design&node-id=15976-36613&mode=design&t=G33KrQoAg5WWkN0n-4) to see examples of every type of view for the obs detail page depending on geoprivacy, whether it is the user's observation, and whether they have permission to view the observation's location.

**Comment by kueda** [comment]
FWIW, I think Angie implemented this as specified... but I don't think it was specified correctly. What we want to communicate is whether the coordinates are obscured, not what the user's geoprivacy choice was. I want to be sure that the coordinates of the threatened species I saw are obscured, whether they're obscured because I said they should be OR if the taxon has a conservation status.

**Comment by abhasinat** [comment]
I don't think I understand exactly what you'd like to be different. Do you want more explicit text explaining "This organism has a sensitive status, and its location is obscured. You can always see the location of your own observations." when you observe a threatened species?
