### ISSUE TITLE
Explore button filters & stack navigation

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1271]
There are a number of entry-points to Explore, each with different contexts and expectations about what view is presented and what the filters are. Furthermore, most of these buttons push Explore onto an existing stack navigator, e.g. MyObs -> ObsDetails -> TaxonDetails -> Explore, or even more confusingly, Explore -> TaxonDetails -> Explore, and in these stacked contexts, Explore needs a back button to pop it off the stack and return to the previous screen (plus the previous Explores need to keep their state).

- [x] MyObs toolbar Explore button should
  - [x] Show the Observations view
  - [x] Show a back button that takes you back to MyObs
  - [x] Have an accessibility label that makes it clear you are going to see all of your observations in Explore
  - [x] Filter observations by the current user with no other filters, i.e. user_id=1&verifiable=any and no default geographic filters like nearby
- [x] TaxonDetails Explore button should
  - [x] Show the Observations view
  - [x] Have an accessibility label that makes it clear you are going to see observations of this taxon in Explore
  - [x] Show a back button that takes you back to TaxonDetails
  - [x] Filter observations by the taxon that are verifiable with no other filters, i.e. taxon_id=1&verifiable=any and no default geographic filters like nearby
- [x] UserProfile observations button
  - [x] Show the Observations view
  - [x] Show a back button that takes you back to UserProfile
  - [x] Have an accessibility label that makes it clear you are going to see observations by that user in Explore
  - [x] Filter observations by the profile user that are verifiable with no other filters, i.e. user_id=1&verifiable=true and no default geographic filters 
- [x] UserProfile species button
  - [x] Show the Species view
  - [x] Show a back button that takes you back to UserProfile
  - [x] Have an accessibility label that makes it clear you are going to see species observed by that user in Explore
  - [x] Filter observations by the profile user that are verifiable with no other filters, i.e. user_id=1&verifiable=true and no default geographic filters 
- [x] Bottom tabs Explore button should
  - [x] Default to species view (#1231)
  - [x] Default to Nearby with location permission otherwise Worldwide geographic filter
  - [x] Not lose its state when you navigate away, i.e. when you are in Explore and set some filters then tap Notifications in the bottom tabs and then tap Explore in bottom tabs, those filters and those observations should still be there  (#1215)
  - [x] Not have a back button

I would try to experiment with at least two different screens, one for the root Explore accessed from the bottom tabs that should never have a back button, and another for the Explore that can be stacked (with a back button). Ideally every stacked screen is a separate instance and doesn't navigate you *back* when you do something like Explore -> TaxonDetails -> Explore -> TaxonDetails -> Explore. Alternatively, maybe it would work if the bottom tabs button just resets the nav state.

**Comment by albullington** [comment]
@kueda there's one other entry point I see for explore, from the logged out MyObservations screen. should that one operate similar to the bottom tabs entry point -- species view, default to nearby if location permissions are given, and no filters except verifiable? and should it have a back button to return to MyObservationsEmpty?

**Comment by kueda** [comment]
Let's treat it exactly like the bottom tabs entry point, no back button.

**Comment by albullington** [comment]
closed by PR https://github.com/inaturalist/iNaturalistReactNative/pull/1306
