### ISSUE TITLE
Next screen after cameras is always Suggestions

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1281]
The intent is to land on Suggestions after the user is done in both StandardCamera and ARCamera, so that's when the user taps the confirmation button on StandardCamera or the shutter on ARCamera. The only way out of Suggestions in this context is the back button to return to the camera or the confirmation buttons for each suggestion. This also means suggestions will need to know about the observation before ObsEdit appears because Suggestions needs to know about the coordinates to make its request to score_image.

I can imagine a few ways to do this, so I'm going to try and not over-specify:

* Get current location in the cameras (also need permission gate) and pass that to Suggestions in params
* Always load ObsEdit as the first screen in the the add obs flow and then immediately navigate to the camera while ObsEdit loads its coordinates in the background
* Have suggestions itself try to fetch the current user location  when reached from the cameras

It's not entirely clear to me what needs to be modal and what doesn't, so if that's confusing I guess consult with Abhas.

**Comment by albullington** [comment]
@abhasinat in this flow from Camera -> Suggestions -> ObsEdit, what changes need to be made to the ObsEdit back button? Should it still discard observations and send a user back to MyObservations? Or should it function like a real back button and send users back to the previous Suggestions screen?

**Comment by abhasinat** [comment]
That's a great question. I think with this change, it should function as a normal back button so that the user can go: Camera (AI camera or standard camera) -> Suggestions -> Obs Edit and then back Obs Edit -> Suggestions -> Camera with no interruptions.

**Comment by kueda** [comment]
I'll take a look at the e2e failure in Android.

**Comment by kueda** [comment]
FWIW, I was able to replicate the e2e test failures in Android in this branch, but I was also able to replicate them in main. b397d0d4f58e8ad64ea1e9eb3e6c4828dfaccbda addresses the problems in main, and it fixed them in this branch when I merged that in.
