### ISSUE TITLE
Enable dependabot & audit dependencies

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1314]
- [x] Enable [Dependabot security updates](https://github.com/inaturalist/iNaturalistReactNative/settings/security_analysis) and review and merge its PRs
- [x] Follow up by addressing any remaining high and critical vulnerabilities with our dependencies revealed by `npm audit`.
- [x] Try setting up CodeQL & either abide by its recommendations or report on them

**Comment by albullington** [comment]
Dependabot PR https://github.com/inaturalist/iNaturalistReactNative/pull/1326 will be fixed by the React Native upgrade  in PR https://github.com/inaturalist/iNaturalistReactNative/pull/1339, so I'm leaving that one for now. Everything else should be audited and fixed.
