### ISSUE TITLE
Crash when navigating from ARCamera -> ObsEdit -> PhotoLibrary -> ObsEdit

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1345]
**Describe the bug**
There's a crash happening when a user moves through an observation creation flow with Suggestions, then tries to start a second observation flow and upload the observation. I believe the crash is happening in TaxonResult, and says that Text must be placed within a text component, but I can't replicate this consistently enough yet to copy the crash.

**To Reproduce**
1. Go to AR Camera and get a taxon suggestion (say, Monstera Deliciosa)
2. Take a photo
3. Select the Top Suggestion on the Suggestions screen
4. Save/upload the observation
5. From the MyObservations screen, go to PhotoLibrary
6. Create a new observation and land on the ObsEdit screen
7. Try to save/upload an observation
8. App will crash with the Text error from TaxonResult

**Expected behavior**
A user should be able to create multiple observations; moving through the Suggestions flow should not result in later crashes

**Context (please complete the following information):**
 - App version: [v0.29.0+81](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.29.0%2B81)

Likely related to the bug in https://github.com/inaturalist/iNaturalistReactNative/issues/1353

**Comment by kueda** [comment]
This was fixed as a part of #1477
