### ISSUE TITLE
Back from Obs Edit should return to Obs Detail

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#135]
Repro:

1. Sign in
2. Tap an observation in My Observations
3. Tap the pencil icon in the upper right to edit
4. Tap the back arrow on the left side of the header
5. You return to My Observations when you should return to Obs Detail

**Comment by albullington** [comment]
@kueda do you mind if I separate this into two issues? I have a fix for the navigation, but not the listener removal. These feel pretty unrelated to me (one is a navigation bug, one is related to `useEffect` and realm) and I think it might be easier to reason about them separately.

**Comment by kueda** [comment]
Separate away!
