### ISSUE TITLE
PhotoLibrary navigates straight to ObsEdit after camera flow

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1353]
**Describe the bug**
The PhotoLibrary doesn't always load when you're trying to import a new photo. Sometimes, this screen advances straight to ObsEdit with the previous suggestion.

**To Reproduce**
1. Go to ARCamera -> ObsEdit -> save a photo with a suggestion
2. Go to StandardCamera -> ObsEdit -> save a photo with a suggestion
3. Tap PhotoLibrary to import a photo from the device -> the screen will advance to ObsEdit with the suggestion from StandardCamera still loaded, instead of letting you import a photo

**Expected behavior**
A user should always see the PhotoLibrary when tapping import a photo

**Additional**
Likely related to the bug in [#1345](https://github.com/inaturalist/iNaturalistReactNative/issues/1345)

**Comment by abhasinat** [comment]
Here's the [desired navigation flow](https://www.figma.com/file/gzrhrvjMvaL5aFvgqnVtZ9/iNat-Mobile-Flows?type=whiteboard&node-id=29%3A4740&t=OHR3nnkAVeF39fRz-1) for reference.

**Comment by kueda** [comment]
I can replicate this bug when I run f21ffb00c40348fcf9e0a812e3c9aed44bd72aab (from April 3) but not 4d0165c89b44030596a95f4c0f04f5c3a5cbe826 (today) so I think it was fixed in the interim, possibly as a part of #1477.
