### ISSUE TITLE
Allow users to contact support from Gmail, not only Mail app

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1356]
A user should be able to email support without downloading new software. Since `react-native-email-link` supports multiple email clients, a user should be able to open whichever email app they have on their phone. I believe for this we'll need [getEmailClients( )](https://github.com/includable/react-native-email-link?tab=readme-ov-file#getemailclients) to check for Gmail.

This happens when tapping the "CONTACT SUPPORT" button.

**Screenshots**
![Screenshot 2024-04-04 at 8 12 54 PM](https://github.com/inaturalist/iNaturalistReactNative/assets/35536439/a81fe915-755a-4109-b117-0f209c0b8d4f)

**Comment by abhasinat** [comment]
This also applies to the email confirmation screen after signup.

![Image](https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/73751019-c9bc-485f-b285-ee678042eb1c)

**Comment by albullington** [comment]
i believe this fix should have been applied for all email links. if this isn't fixed in the next build, can you make a new issue @abhasinat?

**Comment by abhasinat** [comment]
Will do.
