### ISSUE TITLE
Review iNaturalist link is broken

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1370]
**Describe the bug**
Link to review iNaturalist isn't working

**To Reproduce**
1. Go to Donate screen
2. Tap on Review iNaturalist button
3. Nothing happens

**Expected behavior**
We should only have working buttons in the MVP

**Context (please complete the following information):**
 - OS: iOS
 - App version: [v0.29.2+83](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.29.2%2B83)

**Additional context**
Might be best to hide this section of the Donate screen for the MVP and add to the app post-MVP, but worth exploring whether it's an easy fix.

**Comment by jtklein** [comment]
The library we are using to show the dialog advises against showing a review prompt with the press of a button:
https://github.com/oblador/react-native-store-review?tab=readme-ov-file#usage

Another library that allows the same prompt goes further and states this to be against iOS and Android guidelines, but I have not checked the original sources.
https://github.com/oblador/react-native-store-review?tab=readme-ov-file#usage

@abhasinat maybe double check the actual design on this one.

**Comment by abhasinat** [comment]
The current iOS app has a button is settings that does exactly this, so I don't think it should be an issue on a button that a user chooses to click. I believe the app store discourages solicitation of reviews.

**Comment by angielt** [comment]
Can't replicate the bug, seems to be working as expected (app ver 0.32.0)

![Image](https://github.com/inaturalist/iNaturalistReactNative/assets/13282161/58d42a12-2e55-4587-bd0b-4b2bd2543ff2)

**Comment by albullington** [comment]
Closing since this is now also working for me, will reopen later if I can find repro steps.
