### ISSUE TITLE
Updating an unmounted component, My Observations

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#138]
On My Observations, there is a warning raised about updating an unmounted component (this happens when switching screens, like going back and forth from Explore to My Obs):

![warning](https://user-images.githubusercontent.com/35536439/182517739-8d85635e-cb70-427a-a21f-b24d52ad78d1.png)

That seems like it might be coming from https://github.com/inaturalist/iNaturalistReactNative/blob/main/src/components/Observations/hooks/useObservations.js#L78, i.e. that listener is not actually getting removed in the teardown method at https://github.com/inaturalist/iNaturalistReactNative/blob/main/src/components/Observations/hooks/useObservations.js#L100, or the teardown never actually gets called.

**Comment by kueda** [comment]
I can no longer replicate this.
