### ISSUE TITLE
LocationPicker bugs

### ISSUE THREAD

**Issue by budowski** [inaturalist/iNaturalistReactNative#1383]
**Describe the bug**
In continuation to #1224 - here is a list of location picker bugs that I couldn't recreate anymore:
* accuracy circle not showing in iOS
* current location button is often not responsive in Android when the cross hairs are very close to the current location but not quite on it

**Comment by kueda** [comment]
I can't recreate the accuracy circle issue and Android is not a priority ATM so I'm going to close.
