### ISSUE TITLE
Replace Whitney font with Lato throughout app

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1395]
We're making a change to replace Whitney fonts with [Lato](https://fonts.google.com/specimen/Lato) throughout iNaturalist. The full list of fonts we need to replace are:

- [x] Book Italic
- [x] Book Pro
- [x] Book
- [x] Book Italic Pro
- [x] Light Italic
- [x] Light Pro
- [x] Light
- [x] Light Italic Pro
- [x] Medium Italic
- [x] Medium Pro
- [x] Medium
- [x] Medium Italic
- [x] Semibold Italic
- [x] Semibold Pro
- [x] Semibold
- [x] Semibold Italic Pro

To complete this issue, we should:
- [x] Remove Whitney fonts
- [x] Add Leto fonts
- [x] Run `npx react-native-asset` to link new fonts
- [x] Make sure ios/Info.plist includes Leto fonts, not Whitney fonts (no need to include the `-Pro` files in Info.plist since those are for Android-only
- [x] Update `styledComponents.js` with Leto fonts
- [x] Update `tailwind.config.js` with Leto fonts
- [x] Audit the app and replace Whitney wherever we added a custom fontFamily (this should be SearchBar, UserText, Button, TextInputSheet, Wikipedia, CustomDrawerContent, and navigationOptions). It's probably ideal to pull these custom font families out into a file of constants so we can have a single source of truth instead of updating this across multiple files. (For example, a file that contains a variable:

```
const DEFAULT_FONT_FAMILY = `Leto-Light${Platform.OS === "ios"
      ? ""
      : "-Pro"}
```

**Comment by albullington** [comment]
@abhasinat can you confirm these are the correct replacements?

1. Whitney Light -> Lato Light
2. Whitney Book -> Lato Regular
3. Whitney Medium -> Lato Bold
4. Whitney Semibold -> Lato Black

**Comment by abhasinat** [comment]
Here are the correct replacements:

- Whitney Light -> Lato Light
- Whitney Book -> Lato Regular
- Whitney Medium -> Lato Medium
- Whitney Semibold -> Lato Bold
