### ISSUE TITLE
Phone Storage Full alert

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1399]
When a user's device is full and they take a photo, iNat may not be able to save their observation, photos, or may even crash. When iNat detects a users' device's storage is full, I would like a native modal to appear that says "Device storage full. iNaturalist may not be able to save your photos or may crash." just so a user understands what is happening. I imagine this is most likely to happen in the multicapture and AI cameras when a user takes a photo, but there may be other places where it could be shown as well– @kueda may have suggestions.

Todo:

- [x] Check to see if device storage is full when
  - [x] a user opens the app or
  - [x] takes a photo from the multicapture camera or ai camera, c
- [x] If it is, show the following native modal:
    Title: Device Storage Full
    Body: iNaturalist may not be able to save your photos or may crash.
    1 Button: OK

This was inspired by some of Carrie's experiences using the app with full storage and not understanding what was happening.

**Comment by kueda** [comment]
FWIW, this manifested like this for Carrie in the logs:

```
JS Error: Fatal: Error: ftruncate() failed: No space left on device
    at Realm_get_shared_realm (native)
    at getSharedRealm (/Users/johannes/Library/Developer/Xcode/DerivedData/iNaturalistReactNative-aidnjchjmnvyupaeknorzteskpgm/Build/Intermediates.noindex/ArchiveIntermediates/iNaturalistReactNative/BuildProductsPath/Release-iphoneos/main.jsbundle:125448:46)
    at Realm (/Users/johannes/Library/Developer/Xcode/DerivedData/iNaturalistReactNative-aidnjchjmnvyupaeknorzteskpgm/Build/Intermediates.noindex/ArchiveIntermediates/iNaturalistReactNative/BuildProductsPath/Release-iphoneos/main.jsbundle:132375:131)
```

I think if we catch something like that in the global error catcher we could show this dialog, though we'll probably need to add to the list of similar exceptions as we encounter them.

**Comment by angielt** [comment]
@abhasinat  should the alert show every time the user tries to take a photo and storage is full?

**Comment by abhasinat** [comment]
it should show on app start up and then every time they try to tap the shutter button while device storage is full
