### ISSUE TITLE
Alert when too many photos taken in Standard Camera

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#142]
Currently we're limiting the Standard Camera to 10 photos, but when you hit 10 it just add's another loading spinner to the photo preview area and doesn't tell you anything's wrong. Instead, when the user tries to add one more photo than the max,

- [ ] Change the limit to 20 (this is what it is across the platform)
- [ ] Don't add a spinner
- [ ] Use a disabled style for the shutter when the user is past threshold
- [ ] When the user taps the disabled shutter button, show a popup / alert that says, "Observations can only have 10 photos. To add more you will need to remove some."

**Comment by albullington** [comment]
This one is already finished, right? I think this can be closed.

**Comment by kueda** [comment]
Closed in https://github.com/inaturalist/iNaturalistReactNative/pull/145
