### ISSUE TITLE
Can't delete photo from observation

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1429]
**Describe the bug**
A user should be able to delete photos via the Media Viewer, coming from the ObsEdit screen

**To Reproduce**
1. Go to ObsEdit for an observation with at least one photo
2. Tap on photo to pull up Media Viewer
3. Use trash can icon to delete photo
4. Tap discard on bottom sheet
5. Nothing happens; photo is not deleted

**Screen Recording**

https://inaturalist.slack.com/archives/C02G5AATVGA/p1713820737823759

**Additional context**

**Comment by kueda** [comment]
Might be related to #1143

**Comment by albullington** [comment]
This appears to still be happening as of the [current commit](https://github.com/inaturalist/iNaturalistReactNative/commit/09f4abdf9b639b90866d3527491456b48197f2d5)

**Comment by kueda** [comment]
Probably spent half of this time writing integration tests, but was glad I did. Could still use some more.
