### ISSUE TITLE
Can't filter Explore for observations w/ no taxon

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1431]
**Describe the bug**
You cannot filter Explore for observations that have no taxon / identification.

**To Reproduce**
1. Go to Explore
2. In the iconic taxon chooser, choose the last option (leaf w/ dashed outline and question mark)
3. Nothing happens

**Expected behavior**
I expect some UI to indicate that you are searching for obs w/ no taxon, and I expect the APPLY FILTERS button to become enabled. When I tap APPLY FILTERS, I expect to see observations that have no identifications.

**Context (please complete the following information):**
 - Device: iPhone SE (3rd gen)
 - OS: iOS 17.4.1
 - App version: 0.31.1 (86)

**Additional context**
There are no designs for this state, so I'm assigning to @abhasinat for now.

**Comment by abhasinat** [comment]
Right now, we're using the "Unknown" button to remove filters.

The desired design/functionality is:

- When there are no buttons selected, all icons should appear. Clicking the unknown button should filter by all observations with no ID/Unknown
- When there is a button selected, a "remove" button should appear at the end of the button list. clicking this button should remove the taxon filter on explore filters entirely and return these buttons to the default, unclicked state.

<img width="864" alt="Explore Filters Iconic Taxa Buttons" src="https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/b14e0a64-e27e-467e-9ac5-32e1bb583cf1">

**Comment by abhasinat** [comment]
Here's a design for what we can display for the Unknown button being selected.

![image](https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/fb7a8320-d9cf-4b91-87e7-0cfa4e0e1c2e)

Here's a screenshot of what Unknown observations currently look like on obs detail, so we can use the same UI here.
![IMG_4BCD5942151B-1](https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/bc038393-7ef6-441a-9e7e-26a57b4a1bb1)
