### ISSUE TITLE
AI Camera displays previous frame

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1435]
**Describe the bug**
When you take a photo via the AI Camera, save it, then reopen the AI Camera, the previous frame is still frozen on the screen for a second before the camera view loads.

**To Reproduce**
1. Take a photo via the AI Camera
2. Save it via Obs Edit
3. Reopen the AI Camera
4. You'll still be able to see the last photo you captured

**Expected behavior**
The AI Camera should load the camera view without stale data, so a user can immediately start using the camera.

**Comment by jtklein** [comment]
Can no longer replicate this.
