### ISSUE TITLE
Clicking “Add an ID” on obs edit for an obs without any photos should open Search Taxa

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1443]
<img width="533" alt="6" src="https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/f3d85939-5dac-4f3e-b75c-5bd6265fed74">

Right now, when you click “Add an ID” on obs edit for an observation without any photos, it opens the suggestions screen with an endless spinner. Instead, when there are no photos for an observation, add an ID should open the “Search Taxa” screen.

**Comment by kueda** [comment]
Fixed by 44c12e1af981e697462b4ffd11d83693cc7595a0, will be in the next release.
