### ISSUE TITLE
Permissions UI Fix

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1445]
<img width="1059" alt="8" src="https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/69f3e9fd-e680-48b4-b314-89beb711cef5">

The background image on the permission screens should extend to the top & bottom of the screen.

**Comment by kueda** [comment]
But not the top?

**Comment by abhasinat** [comment]
I think top would be good too, actually.

**Comment by budowski** [comment]
OK, so the bottom part (navigation bar) and the top bar (status bar) cannot be fully hidden on Android when it's inside modals (and the permission gate is modal-based) - unless we do ugly patch-work directly on node-modules or use a forked version of RN (known issue with react-native):
https://github.com/kadiraydinli/react-native-system-navigation-bar/issues/51

**Comment by kueda** [comment]
Sounds like it's not worth fixing until the react native bug gets fixed. We can re-open if we change our minds.
