### ISSUE TITLE
Projects Search Bar UI fix

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1447]
The search bar on the projects screen seems a bit too high. It should have equal space above and below it. Right now, there is a lot more space below than above.

<img width="545" alt="10" src="https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/3a71cd8c-2afb-40a2-8a52-d97f43ae46af">

**Comment by angielt** [comment]
fixed as part of #1659
