### ISSUE TITLE
Notifications Photo bug & UI Fixes

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1449]
<img width="464" alt="12" src="https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/f5d31a74-14cb-416a-9fe8-201b82dd1c11">

There is a bug with displaying photos in notifications [already](https://github.com/inaturalist/iNaturalistReactNative/issues/1043), and these UI fixes are related.

- [ ] When I _do_ have a notification an obs with no photo (and it's displaying correctly), the outline should stay square around the no photo icon, and not take up the height of the notification
- [ ] The spacing seems to be off in the list items - the text should not have so much space to the right of it. Please refer to the [designs](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?type=design&node-id=8378-12173&mode=design&t=oQacpYPEnqyi04Gj-4) for proper spacing.

**Comment by kueda** [comment]
These *should* be addressed in 24ac2c1a2957104efd1408689146bdb46bb55d40, but I'll leave this open until you've had a chance to review it.

**Comment by kueda** [comment]
@abhasinat can I close this? This fix should be in the latest release.

**Comment by abhasinat** [comment]
yep sounds good.
