### ISSUE TITLE
Activity/Details tabs on Obs Detail should not be sticky

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1451]
Right now on Obs Detail, it seems that your last clicked tab (activity or details) on any observation gets retained when you view another observation.

Desired behavior: every time a user lands on a new Obs Detail screen, the default tab should always be activity (the first tab)

**Comment by kueda** [comment]
FYI, this may simply involve reverting #1393. Also, I think this is a bad idea. If I'm in a "learning" or "research" mode I don't care at all about the Activity tab and constantly having to switch is an annoyance. If I'm in an identifying mode I usually want to land on the Activity tab. Keeping it sticky facilitates both use cases and doesn't really impact new users, who will see Activity by default.

**Comment by tiwane** [comment]
I didn't thinka bout this use case. I basically never use the app to learn, probably because in iOS it's not that helpful. I use the app to add observations and to check on updates on my observations, that's it. I'd be interested in seeing what feedback we get, whichever route we go with.

**Comment by abhasinat** [comment]
I could see this being confusing for first time users. When tabs like this are sticky, it creates an association that you're returning to a screen that you've already been to, which I think would be confusing if a new user is navigating different obs detail pages. Imo I think reinforcing the community aspect of the activity tab on every new obs detail screen is more important than the details tab, which is mostly summarized at the top of the screen.

**Comment by abhasinat** [comment]
Decision from mobile meeting: on a single app session, the obs detail tab should be sticky. When the app is force quit and reopened, the tab should default to the activity tab first.

- [ ] On app open, obs detail should default to the activity tab
- [ ] Within the same session, the tab should be sticky. So if a user switches to the details tab and views another observation, they should see the details tab again
- [ ] If the app is running in the background, then when they return to the app, the next observation they view should land on the last obs detail view they viewed.
- [ ] If the app is force quit and reopened, the first obs detail page a user sees should show the activity tab first.

Note: The session ends when a user force quits the app. If the app is open in the background, the app is in the same session.
