### ISSUE TITLE
Device Storage Full modal

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1452]
When a user's device storage is full, the app has some issues, can crash, and can't save photos.

When 1) a user opens the app or 2) takes a photo from the multicapture camera or ai camera, check to see if device storage is full. If it is, show the following native modal:

Title: Device Storage Full
Body: iNaturalist may not be able to save your photos or may crash.
1 Button: OK

**Comment by kueda** [comment]
@abhasinat is this a duplicate of #1399?

**Comment by kueda** [comment]
I added your more detailed solution to #1399
