### ISSUE TITLE
Crash on nav to ObsEdit from existing observation

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1473]
**Describe the bug**
This TaxonResult bug is one we've bumped into in a few places. In this case, the app is crashing when tapping on an existing observation that has not yet been uploaded.

**To Reproduce**
1. Go to AICamera and take a photo while logged out
2. Save observation via ObsEdit
3. Tap the observation on MyObservations
4. See crash in screenshot below

**Expected behavior**

**Screenshots**
![Screenshot 2024-04-26 at 8 55 54 AM](https://github.com/inaturalist/iNaturalistReactNative/assets/35536439/50e2190f-e945-4ca3-93a8-0c0fbf805347)

**Context (please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: iOS 17
 - App version: [v0.32.0+88](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.32.0%2B88)

**Additional context**
Not sure if there are other scenarios where this is happening. Might be worth trying from the standard Camera, for a logged in user, etc.

**Comment by kueda** [comment]
Another one that I think was fixed as a part of #1477
