### ISSUE TITLE
Collaborators section needs text

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1476]
**Describe the bug**
The Collaborators section on the team page is incomplete. We should either add text here or remove for soft launch. @abhasinat any idea what you'd like to put here?

**Screenshots**
![IMG_9262](https://github.com/inaturalist/iNaturalistReactNative/assets/35536439/0de8b1d5-0cb6-4bd7-89d1-b394e8a4560f)

**Comment by abhasinat** [comment]
@carrieseltzer would love your input on text for the About/Team pages

**Comment by carrieseltzer** [comment]
Here's some text:

Collaborators
The models that suggest species based on visual similarity and location are thanks in part to collaborations with Sarah Beery, Tom Brooks, Elijah Cole, Christian Lange, Oisin Mac Aodha, Pietro Perona, and Grant Van Horn.

Please also add Thea Skaff and Michelle Vryn in alphabetically in the team list.
