### ISSUE TITLE
Crash when starting no evidence observation

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1477]
**Describe the bug**
We're still having some issues with previous data lingering in the ObsEdit flow. When opening ObsEdit with no evidence, a user should always see a fresh observation, not have lingering details about whatever taxon was previously on the ObsEdit screen. We need to think about when this data should be reset and be consistent (when a user navigates to ObsEdit? when they open the AddEvidenceModal? when a user leaves the ObsEdit screen?)

**To Reproduce**
1. Take and save a photo through the AI Camera Flow
2. Tap on AddEvidenceModal
3. Make an observation with no evidence, which will land you on ObsEdit
4. See crash in screenshot

**Expected behavior**
A user should see a fresh ObsEdit screen every time, no matter what screens they were on previously.

**Screenshots**
![IMG_9264](https://github.com/inaturalist/iNaturalistReactNative/assets/35536439/058fcb06-0064-4cc2-8ade-b9159e7dfcfd)

**Comment by abhasinat** [comment]
Here's the [desired navigation flow](https://www.figma.com/file/gzrhrvjMvaL5aFvgqnVtZ9/iNat-Mobile-Flows?type=whiteboard&node-id=29%3A4740&t=OHR3nnkAVeF39fRz-1) for reference.
