### ISSUE TITLE
Bulk upload text and progress bar doesn't match uploads in progress

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1481]
**Describe the bug**
The bulk upload text and progress bar on MyObservations still doesn't reflect the actual status of uploads. 

**To Reproduce**
1. Queue up a large number of observations (Carrie tried 72)
2. Start uploading all of them from MyObservations
3. Observe progress bar. It will say "Uploading 1 of 72" and won't make progress
4. Text may flash and occasionally say "19 observations uploading" but will change states instead of conveying a consistent, accurate message to the user

**Expected behavior**
A user should be able to see the real-time progress of their uploads, along with the correct message letting them know how many uploads are in progress.

**Additional context**
App version: [v0.32.0+88](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.32.0%2B88)

I suspect this is related to our lack of [sequential uploads](https://github.com/inaturalist/iNaturalistReactNative/issues/1427), which is an issue we've decided not to prioritize. The way our code is currently written, all 72 uploads will start at once, instead of moving through sequential progress. That means uploads will complete in a random order, instead of completing one at a time. All 72 uploads will create an observation, then all will try to append any photos or sounds to the observations via a different API call. I think we'll need to address this underlying code if we want to display reliable messaging to the user.

**Comment by kueda** [comment]
Possibly related problem in v0.32.3 (91): progress bar can exceed the text progress:

![IMG_0841](https://github.com/inaturalist/iNaturalistReactNative/assets/22691/808d4715-89fc-4d6e-b216-6a7564bd72fb)

In this particular case there were a few observations with multiple photos, but I was able to replicate this with a couple single-photo observations as well:

![IMG_0856](https://github.com/inaturalist/iNaturalistReactNative/assets/22691/ab97d2bc-8c69-4c76-b5f2-2d61bdb3c404)

**Comment by albullington** [comment]
Closed by PR [#1606](https://github.com/inaturalist/iNaturalistReactNative/pull/1606)
