### ISSUE TITLE
Automatically add Open Beta group to Fastlane build process

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1482]
We'll need to do something like [this](https://stackoverflow.com/questions/57894806/how-do-i-distribute-a-build-to-external-testers-via-fastlane) to automatically distribute our builds to the Open Beta group. We should do this so the Open Beta group automatically gets added to each latest build of the app.

**Comment by kueda** [comment]
`bundle exec fastlane beta` should do this, but we do need to update the README.

**Comment by kueda** [comment]
FWIW, we decided today that we would just update the Open Beta every time we update the internal build w/o any additional qa/qc checks, so IMO we just need to run that additional fastlane command every time we release.
