### ISSUE TITLE
Change to Add Evidence navigation flow

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1487]
**Describe the bug**
When adding evidence to an observation, the user should go back to the camera, then straight back to ObsEdit without landing on Suggestions a second time. Since they've already given an identification, there's no need for them to change their identification while adding evidence.

**To Reproduce**
1. Create an observation
2. Tap add evidence on ObsEdit
3. Tap camera to add evidence via the camera
4. Take a new photo to add to the observation
5. Land on suggestions, when we want the user to land directly back on ObsEdit

**Expected behavior**
Check with @abhasinat if the desired user flow isn't clear. This should only impact the camera, since we only show Suggestions after the camera screens.

**Comment by kueda** [comment]
FYI, this is the authoritative obs creation flow: https://www.figma.com/file/gzrhrvjMvaL5aFvgqnVtZ9/iNat-Mobile-Flows?type=whiteboard&node-id=29-4740&t=aKH7mnoVSljKYjJ0-0
