### ISSUE TITLE
App update means user can't upload previously saved observations

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1488]
**Describe the bug**

**To Reproduce**
1. Install a previous version of the app
2. Make two observations (probably best with photos/evidence)
3. Don't upload these observations; save them locally
4. Update to the latest version of the app
5. Try to upload two saved observations
6. See upload animation spinning forever without an actual upload

**Expected behavior**
Users should not lose the ability to upload data from previous app versions.

**Context (please complete the following information):**
 - App version: [0.32.0+88](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.32.0%2B88)

**Additional context**
Not sure what the underlying issue is here, but I suspect it might have to do with photos being stored in the local /photoUploads directory. [This PR](https://github.com/inaturalist/iNaturalistReactNative/pull/1468) showed me that we needed to change the way we access photos to be able to display them after an app update, but we didn't change the way we access photos for upload.

**Comment by jtklein** [comment]
I have added a fix for this problem for uploading observations with photos. But I have not tested if this also works for sounds. I suspect it will not. So, I am reopening this to remind myself to check obs with sound.

**Comment by jtklein** [comment]
Have tested now and this is indeed still a bug for obs sounds.
