### ISSUE TITLE
Explore providing Realm with context and isolating data persistence in models

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#149]
Currently when we need to persist data in Realm, we open a new Realm connection in a component or a hook and either use it or pass it to a model instance where it gets used. IMO, the components and most of the hooks should not need to know that much detail about data persistence, and opening and closing multiple Realm connections sounds like a recipe for memory leaks and stale Realm handles.

The task here is to explore ways we might achieve two goals:

1. Provide a single Realm connection to all code in the app
2. Isolate data persistence functions from presentation functions like components

This work will be exploratory in nature so it may not necessarily result in a merge. I'm mostly interested in getting a feel for whether we should do something like this, and if so, what approach seems the most reasonable.

I put some time into [exploring these in a branch](https://github.com/inaturalist/iNaturalistReactNative/compare/bb4795d69c5fef05d761e0b93ace2608564b4ffb...realm-in-models) a while ago, by using Context and a Provider to provide a single Realm connection to the entire app, and by using a superclass of all models to store that Realm connection as a class constant (essentially a global). That might be one avenue worth pursuing. My caveat with that approach is that I'm not 100% sure a new Realm connection will get opened when needed (e.g. when the app moves from bacgkround to foreground), nor am I sure if using a class constant is a stable way to make the Realm connection available to code outside of components and hooks (which are the only places the useContext hook can be used to get access to the Realm connection).

[Realm itself provides a `RealmProvider`](https://www.mongodb.com/docs/realm/sdk/react-native/use-realm-react/#using-the-realm-provider) that we could use instead of writing our own, so that may be worth exploring.

Another approach to 2 might be use the [repository pattern](https://developer.android.com/codelabs/basic-android-kotlin-training-repository-pattern#3), e.g. each model might have a repository that performs tasks like Realm CRUD, but also deciding when and how to fetch remote data. Models would be reduced to schema declaration and schema mapping functions, and most of the work would live in the repository. I've mostly encountered this in Android development, so it might not be a great fit in an RN app, but in principle it seems like a reasonable way to isolate data from presentation.

**Comment by kueda** [comment]
Here are some slightly more fleshed out thoughts I've had on the repository pattern in case anyone else is willing to take a stab at it. I started thinking about it by writing some component code that might use a repository:

```javascript
// Get a repository for Observation records using a hook. Note that we don't
// hand it a Realm connection or an API token; it should take care of those
// things
const repository = useRepository( "Observation" );

// Get a single observation by UUID using the repository
const observation = repository.get( "some-long-uuid-1234" );

// Change the observation and persist that change
observation.description = "this is a great new description";
repository.patch( observation );

// Create a new observation and persist it
const newObs = repository.new( { description: "this is my new obs" } );
repository.post( newObs );

// Delete the observation we just made
repository.delete( newObs );

// Check if the repository needs to upload records
if ( repository.syncStatus === repository.NEEDS_UPLOAD ) {
  console.log( "last upload: ", repository.lastUploadAt );
  console.log( "last download: ", repository.lastDownloadAt );
  // Upload records if necessary
  repository.upload( );
} else if ( repository.syncStatus === repository.UPLOADING ) {
  // If upload is in progress, check on the status
  console.log( "upload started at: ", repository.uploadStartedAt );
  console.log( `
    uploaded ${repository.uploadProgress.completed} of ${repository.uploadProgress.total}
    (${repository.uploadProgress.failed} failed)
  ` );
}
```

Some implications:

* The repository is responsible for accessing Realm and an API token. Providing those values might the work of other systems, but the repository is responsible for interacting with them, not the component.
* The repository handles CRUD operations, not the model, the component, or other helpers
* The repository manages sync operations and exposes information about its sync state, e.g. how many records need to be uploaded, whether an upload is in progress, how many records have been completed

I also made https://github.com/inaturalist/iNaturalistReactNative/tree/149-repositories, which takes a very minimal first stab at implementation (does nothing other that get records locally).

Some open questions:

* General thoughts on this approach? Over-wrought?
* Should a repository provider completely encapsulate Realm?
* If the repository acts like a cache for read-only models like Taxon, how/when do we clear the cache?

**Comment by kueda** [comment]
I'm going to remove this from any milestones and unassign myself for now b/c a) I'm not finding time to work on it, and b) Amanda's charging on React Query, which might be incompatible with this approach and/or might address some of the problems I was hoping this would solve. I still think it's worth exploration, but it's on the backburner for now.

**Comment by Chrischuck** [comment]
@kueda  is this issue still relevant? would love to tackle it if so

**Comment by kueda** [comment]
Hm, I think working toward a single Realm connection should still be on the table, either with `RealmProvider` or something else. I'm less sure about the repository pattern, and I'm curious to hear what @albullington thinks because I don't think the repository pattern is compatible with the React Query approach they have pushed forward.

What part of this were you interested in exploring, @Chrischuck? Also, have you seen repositories used in React Native before? I haven't worked on many RN apps so I've never been sure how people generally achieve the right level of abstraction for models / persistence.

**Comment by Chrischuck** [comment]
@kueda I think RealmProvider is still in use so there should be one realm connection, but I could be wrong. Regarding the repository pattern, I can see how it would be helpful but I am not familiar with it.

In some cases, like `useInfiniteScroll` for example fetches data and upserts into realm while `useLocalObservations` actually gives you the data. There are a couple of other places that might benefit with having a "synchronization" layer to abstract away the model.

IMO, seems like the easiest route would be a pseudo repository type of deal where react query calls and realm updates are wrapped in a hook. Though, I'm not sure if the juice is worth the squeeze.
