### ISSUE TITLE
Duplicate observation upload under poor network connection

### ISSUE THREAD

**Issue by tiwane** [inaturalist/iNaturalistReactNative#1493]
**Describe the bug**
Could potentially be user error (eg me importing a photo that was already used for an observation), but I _think_ the same observation was uploaded twice due to the app not correctly showing it was uploaded properly the first time when connection was spotty. I feel like this might have happened a few times during this desert trip.

**To Reproduce**
1. Go to to the Mojave Desert and find an area with spotty connectivity. Try to upload an observation. The app doesn't show it as uploaded successfully. Try to upload again later and the observation uploads.
2. There are two separate observaitons with the same photo and info. 

**Expected behavior**
If the observation is sucessfully uploaded, the app should show it as such and not include it in the next upload attempt.

**Screenshots**

**Context (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 17.4.1
 - App version: 0.32.0 (88)

**Additional context**

See https://www.inaturalist.org/observations/212422583 and https://www.inaturalist.org/observations/212452254.

**Comment by kueda** [comment]
Ok, my fault for waiting too long on this and now I don't have log data. What I wanted to do was check the requests that created those two observations to see if the app submitted separate UUIDs, which would suggest the app had two separate copies of the observation. Or, maybe the app wasn't submitting a UUID at all and the server had nothing to de-dupe with.

Either way, the only way I have to repro this at this point is to try and fail to upload an observation under "Very Bad Network" using the Network Link Conditioner, and then try again under good network... which I just did and it worked fine. So I'm just going to mark this as blocked and we can revisit in a month or so to see if it's still happening to anyone.

**Comment by kueda** [comment]
We haven't seen this recurring so I will assume it is resolved.
