### ISSUE TITLE
Closing AI Camera should always return to MyObservations

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1499]
**Describe the bug**
Closing the AI camera doesn't always lead to the correct navigation flow.

**To Reproduce**
1. Close the app entirely and open it
2. Click on a previously uploaded observation and click the pencil to edit
3. Hit the back button and end up on the dashboard (should it be the obs screen instead?)
4. Now open the AR camera and close it and end up on a “New Observation” screen, and the date will also not be filled out
5. For the rest of the app session, closing the AR camera will bring me back to the “New Observation” screen

**Expected behavior**
Closing AI Camera should always return to MyObservations

**Comment by abhasinat** [comment]
Here's the [desired navigation flow](https://www.figma.com/file/gzrhrvjMvaL5aFvgqnVtZ9/iNat-Mobile-Flows?type=whiteboard&node-id=29%3A4740&t=OHR3nnkAVeF39fRz-1) for reference.

**Comment by budowski** [comment]
Tried recreating this in different ways, does not occur with latest build - @albullington - can you confirm this?

**Comment by albullington** [comment]
Yep, can no longer replicate and will close.
