### ISSUE TITLE
Suggestions screen navigating without user action

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1503]
**To Reproduce**
1. Use the AI camera flow to take a photo
2. Choose a taxon
3. Click the pencil icon to edit the taxon
4. Get moved back to the Suggestions screen then immediately moved forward again to the observation edit page
5. Clicking the pencil a second time brings the user back to the Suggestions screen without unexpected navigation

**Expected behavior**
A user should be able to use the Suggestions screen the first time they land there

**Comment by kueda** [comment]
I can replicate in 254537f54c7ef506a749b6c011f732b1ec89d6da but not in the current main, so I think this was another that was fixed as a part of #1474
