### ISSUE TITLE
Downvoting a DQA doesn't immediately show change to user

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1504]
**Describe the bug**
Downvoting a DQA on one of my research grade obs doesn’t immediately show the quality grade change. Looks like to refresh the quality grade I need to go back to the home screen then go back into the obs, or go back into the DQA screen which also seems to refresh the obs

**To Reproduce**
1. Downvote a research grade observation on the DQA screen
2. See that nothing changes
3. Return to MyObs
4. Tap the observation and see the changes reflected on ObsDetails and the DQA screen

**Expected behavior**
We should show changes made in the app to the user immediately.

**Additional context**
My guess here is that we're updating the observation on ObsDetail when we fetch a remote observation from the server. But we should also show the user their real-time data changes before needing to fetch the whole observation again.

**Comment by kueda** [comment]
Apparently I'm the only one that can repro this now, generally on already-casual observations.
