### ISSUE TITLE
Human suggestions should be treated differently than other suggestions

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1505]
**Describe the bug**
When we recommend "human" as a suggestion, we should only recommend human and not show other suggestions. This is related to our D&I work. Right now, since we're showing suggestions from both the offline model and the online API call, there are scenarios where a human ID can be mixed together with other IDs.

**To Reproduce**
I don't have specific repro steps here, but I'm guessing this will happen by taking a photo of a human object (like a blanket/chair) with a strong wifi connection. The top suggestion in that case would be human from the offline model, and the API suggestions would show different suggestions.

**Expected behavior**
If human is shown in any of the suggestions, either offline or online, we should hide all other suggestions on the Suggestions screen.

**Comment by kueda** [comment]
When I have a human and a plant in frame and the AICamera recognizes the plant, I land on Suggestions and see suggestions for both the plant and a human, so I don't think this is working yet.

![IMG_0969](https://github.com/inaturalist/iNaturalistReactNative/assets/22691/9151a7cc-ae74-4603-99cd-df7270a781d0) ![IMG_0965](https://github.com/inaturalist/iNaturalistReactNative/assets/22691/68c64c4a-8590-488b-8956-2f52a63f0708)
