### ISSUE TITLE
Photo order in multicapture camera is unpredictable

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1506]
**Describe the bug**
Photo order after upload is unpredictable when taken in the multicapture camera

**To Reproduce**
1. Open the multicapture camera.
2. Take a photo of your hand with:
- 1 finger
- 2 fingers
- 3 fingers
- 4 fingers (or a closed fist in the case of the recording)
3. See 4 photos in captured order on the “add an id” screen. Select human.
4. See 4 photos in captured order on the form. Upload.
5. See the first photo shown on your observations screen while uploading.
6. After upload, tap into obs detail. See 1 finger first.
7. Swipe through other photos. See finger 1 appear again in the third position, then swipe back and see a different photo in the first position (fist). Note: the reordering of images seems to be arbitrary. 

Extra web steps:
1. Open your [observation](https://www.inaturalist.org/observations/214058080) on the website. See fist as first photo.
2. Click Edit your observation on the website, then “re-order photos”
3. See that there is no image order assigned to the photos. (This is also true for observations created on the website, so I’m not sure how they are assigned orders)

**Expected behavior**
Photo position should be maintained in mobile and on web.

**Comment by tiwane** [comment]
FWIW, I was unable to replicate with 3 photos, it seems like 4+ is the magic number. See https://inaturalist.slack.com/archives/C02G5AATVGA/p1715029705863169
