### ISSUE TITLE
Photo permission requested when limited access already granted

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1514]
**Describe the bug**
The app asks the user for photo library access permission once per launch even when the user has already granted limited access.

**To Reproduce**
1. Install a fresh copy of the app to reset all permissions
1. Go to Settings and turn on the full obs addition options
1. Tap the add obs button in the bottom tabs and tap the photo import button
1. You should see the permission gate; tap the button to grant permissions
1. You'll see a native alert. Tap "Limit Access..."
1. Choose some photos for limited access
1. You should still be in the native photo chooser. Choose one photo.
1. On ObsEdit, save the obs
1. Force quit the app
1. Tap the add obs button in the bottom tabs and tap the photo import button
1. You should see the native photo chooser. Pick a photo.
1. When you land on ObsEdit, you see a native alert prompting you to grant permission again... even though you already granted permission

**Expected behavior**
The app should not constantly re-ask you for the same permission. Once you've granted limited access, the app should not continue trying to write to photos it doesn't have permission to write to.

**Screenshots**
Initial permission request from PermissionGate:
![Simulator Screenshot - iPhone 15 Pro - 2024-05-07 at 18 05 07](https://github.com/inaturalist/iNaturalistReactNative/assets/22691/8db4b12e-e5df-4a4c-9123-94535d6c4fbf)

Extraneous permission request on ObsEdit:
![Simulator Screenshot - iPhone 15 Pro - 2024-05-07 at 18 17 21](https://github.com/inaturalist/iNaturalistReactNative/assets/22691/47ecef44-c060-4c0b-859c-369f8a506291)

**Context (please complete the following information):**
 - Device: iPhone SE (3rd gen)
 - OS: iOS 17.4.1
 - App version: 0.32.1 (89)

**Additional context**

Reported by Alex, who added,

> The flow that I see suggests the app was using private access, not the 8 items access.

**Comment by budowski** [comment]
Cannot recreate this with latest `main` branch (both on physical device and simulator) - @kueda - still happening to you?

**Comment by kueda** [comment]
@budowski Yes, this is still happening when I follow the steps exactly. Are you sure you fully uninstalled the app before trying to replicate?

**Comment by jtklein** [comment]
Blocked by #1808

**Comment by kueda** [comment]
This is still happening even after #1808, but repro steps are probably a bit different since the flow has changed. Now it looks a bit like this:

1. Fresh install
2. Tap the add obs button (should be in simple mode)
3. Approve permissions, but instead of taking a picture, tap the gallery button
4. When prompted for access to photos, choose Limited access and limit access to a few photos
5. Complete the obs creation process until you get back to MyObs
6. Force quit the app and open it again
7. Create an obs via the AI Camera
8. After you tap the shutter, you get the "Save photos to your gallery" permission prompt (maybe this is ok since you granted limited access before which may not grant the permission to write)
9. Tap SAVE PHOTOS and allow permission to add photos
10. Complete through to My Obs
11. Repeat the AI Camera obs creation process
12. When you tap the shutter, this time you get a native permission prompt with no permission gate. It says "iNat Next Would Like to Access Your Photos" and asks you to select more photos or keep the current selection

I think the expected behavior here is that if we have permission to add but we only have limited access to read, we should not attempt to write metadata (which will trigger the readwrite permission prompt, confusingly).

There is also a way to add a location (with accuracy) when creating a photo in iOS with only add permission. It would be good to know if the CameraRoll library supports that and if not if we could ask for it or implement it in a fork.

**Comment by kueda** [comment]
FWIW, react-native-cameraroll [does not support writing location for new photos](https://github.com/react-native-cameraroll/react-native-cameraroll/issues/561) in the way we do it in INaturalistIOS. I think it's possible if we wanted to fork the library, but maybe not in Android.
