### ISSUE TITLE
Manual Focus in Camera Mode

### ISSUE THREAD

**Issue by Hedaja** [inaturalist/iNaturalistReactNative#1528]
Hi
I gave the latest test version a try. I hope it's okay I'm adding an enhancement request already.
I really enjoyed the new AI camera which felt like magic but I also tried the standard camera.
One thing I noticed, that has already bothered me with the camera app in the current iNat app, is the lack of manual control.
In my workflow I learned that it's often easier to control focus and zoom manually when taking makro photos. The reason is that focus can jump wildly when you are right on the edge of of the minimal focus distance or if you have a small object to focus on. If you set your focus to minimal, you can more easily adjust the focus point with slight movements of the whole phone.

It would be great to add the possibility to manually adjust the focus. On my standard camera app this can be done with a slider on the bottom but I think it might also be useful to be able to move the slider to the left or right edge to make it easily reachable in landscape mode.
[https://www.piespace.de/index.php/s/e6FerRNDmctP4Wo](url)

Having some predefined focus modes might also be possible addition. I think most useful would be a quick switch between auto-focus and makro-focus (minimal focus distance).
[https://www.piespace.de/index.php/s/zqBEgRrgkDzBiYA](url)

**Comment by kueda** [comment]
Totally ok to try, but we're haven't figured out a way to solicit and process public feedback and feature requests yet, so I'm going to close this for now. Generally we use Github issues for work that is ready for a developer, and this would require some product decision-making before it was ready to work on.

@abhasinat, you might be consider this. FWIW, at least in Android I agree the cameras in this app are almost unusable for close-up work when you can't control which camera is being used. On my Pixel 8 it always seems to automatically switch to wide-angle when I feel like I've zoomed in enough, which screws up the focus (and image quality).
