### ISSUE TITLE
Importing a photo after making AI camera obs = vision results from last AI camera observation 

### ISSUE THREAD

**Issue by tiwane** [inaturalist/iNaturalistReactNative#1537]
**Describe the bug**
In certain situations, the app will use the previous observations' photo for suggestions.

**To Reproduce**
1. Open AI camera, get an ID, save observation.
2. Import a photo into the app and tap on Add an ID
3. App will show you results from the observation you made in step 1. You need to discard this observation and reimport the photo.

**Expected behavior**
The app should use my current photo for suggestions.

**Screenshots**

![1CD16F2A-95EB-4F55-AFF9-50302709F4E8_1_102_o](https://github.com/inaturalist/iNaturalistReactNative/assets/15896181/209f3600-8860-4e22-bde6-c77c0e276c6d)

**Context (please complete the following information):**
- Device: iPhone 13 Pro
 - OS: iOS 17.4.1
 - App version: 0.30.0+84

**Additional context**

**Comment by albullington** [comment]
I'm no longer seeing this and suspect it was fixed via https://github.com/inaturalist/iNaturalistReactNative/pull/1531
