### ISSUE TITLE
Replaying and scrubbing audio repeatedly eventually stops playback

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1540]
**Describe the bug**
Replaying and scrubbing audio repeatedly eventually stops the playback indicator from moving as expected.

**To Reproduce**
1. Make a sound observation
2. Replay and scrub audio via the playback UI
3. Eventually the playback indicator will stop moving / the UI will not match the playback

**Expected behavior**
A user should be able to consistently playback sounds and see the correct scrubbing UI without errors.

**Additional context**
There seem to be two related promise rejections:
`Possible unhandled promise rejection: Error: Player has already stopped` - this happens when starting and stopping playback over and over on the Sound Recorder screen
`Possible unhandled promise rejection: Error: Player is null` - this happens when starting and stopping scrubbing over and over on the scrubbing screen

**Comment by kueda** [comment]
As far as I can tell this commit broke the pause button, as in when you were playing a sound and you tapped pause, the audio would continue playing and the play/pause button would not switch to a paused state.

I frankly couldn't repro this bug before this commit so I'm curious if you could, @angie, and if so, maybe you or @albullington could provide more detailed repro steps? Does it not happen on an SE or something?
