### ISSUE TITLE
Locality note in location picker in obs edit should be vertically centered in search bar

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1542]
Right now, the locality note in the location picker inside of obs edit looks strange if the locality note has more than one line:
<img width="294" alt="image" src="https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/26ef6ef7-8839-44ba-b9d7-071c47da44dc">

How it should work:

- [ ] The locality note should wrap for a maximum of two lines, and should truncate with ellipses after two lines
- [ ] The entire two lines of text should be vertically centered inside of the search bar. So in the example above, there should be equal space above and below the two lines of text (space above "phyllis" = space below "US"

**Comment by kueda** [comment]
Apparently we're ok with the current state of affairs, one line, no wrap, scrollable.
