### ISSUE TITLE
Taxon Detail view when accessed through suggestions

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1565]
When a user lands on taxon detail from suggestions, they have a high likelihood of exiting the obs create flow through too many external buttons.

When a user lands on taxon detail while coming from the suggestions screen, hide the following UI elements:
- [ ] the green explore button
- [ ] the kebab menu at the top
- [ ] the entire tab bar

**Comment by kueda** [comment]
Duplicate of #1549

**Comment by loarie** [comment]
can this be closed?
