### ISSUE TITLE
Attribution should not appear on MediaViewer from Suggestions for new photo

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1570]
**Describe the bug**
When you are making a new obs with the camera and you land on Suggestions, you can tap the photo to view it in the MediaViewer. There we show an attribution button that probably shows the wrong license choice

**To Reproduce**
1. Open one of the cameras and take a photo
2. When you land on Suggestions, tap the photo you just took to enter the MediaViewer
3. The attribution button shows the copyright icon no matter what your default license choice is
4. Tap the attribution
5. The alert says "Copyright. all rights reserved" no matter what your default license choice is

**Expected behavior**
Te information should be accurate or there should be no attribution

**Screenshots**

**Context (please complete the following information):**
 - Device: iPhone SE (3rd gen)
 - OS: iOS 17.4.1
 - App version: 0.32.3 (91)

**Additional context**
Talked w/ Abhas and we agreed to just remove the attribution from the MediaViewer when reached from Suggestions for a *new* photo (it should still appear when you're viewing suggestions for one of your synced observations or someone else's observation.

**Comment by israr002** [comment]
@jtklein i have worked on this and raised the pr
