### ISSUE TITLE
Saved observations with sound recordings will never upload

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1574]
**Describe the bug**
A saved observation with a sound recording will not upload.

**To Reproduce**
1. Take an observation with a sound recording
2. Save, don't upload
3. Let the app sit in the background for a while (I think... this is what I did in the Klamath Mountains)
4. Observation will not upload

**Expected behavior**
All saved observations should upload

**Context (please complete the following information):**
 - App version: 0.32.3+91

**Additional context**
Might need to narrow down exact repro steps for this, but I suspect it has something to do with the app not being able to access the right sound file to upload. Carrie and I both experienced this.

**Comment by kueda** [comment]
As expected, I haven't been able to replicate this. @carrieseltzer and @albullington, did either of you experience this this weekend, and/or do you have an suggestions on how I can reproduce it?

**Comment by kueda** [comment]
Alrighty, hearing nothing, I'm going to assume this isn't happening anymore. Please re-open if it re-appears.
