### ISSUE TITLE
Deleting photos from an observation before it's uploaded prevents the obs from uploading

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1575]
**Describe the bug**
If you try to delete a photo from an observation that has NOT been uploaded already, the image doesn't look like it was deleted at first. Then when you try to save or upload the observation, you can see that the image was turned into a blank image. On my observations, that image now also has the "no evidence" taxa icon. And no matter what I do, the observation will never upload.

**To Reproduce**
1. Go to multicapture camera
2. Take any number of photos
3. choose any id on suggestions
4. click on the image under evidence and delete any of the images (if you delete the first one, you will see a no evidence taxa icon on my observations)
5. click discard media and notice nothing happens
6. click back to return to obs edit
7. try to upload or save (it won't upload)
8. click to view obs edit again and notice the blank white space
9. click the blank image to view (there's still an image but it's blank?)

This also happens through all other obs create flows with photos - multicapture camera, ai camera, gallery, an no evidence. However, this does NOT happen when I delete a sound media.

**Expected behavior**
Discard media modal should work, and should delete photos properly. Additionally, a user should still be able to upload observations even if they deleted some of the images from obs edit.

**Context (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 17.4.1
 - App version: 0.32.3 (91)

**Comment by carrieseltzer** [comment]
I may have hit this same issue with sound.
