### ISSUE TITLE
Observation with deleted sound still displayed in MyObservations and ObsDetails

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1578]
**Describe the bug**
When a user deletes an observation with a sound remotely (on iNat web), that observation still shows up in the MyObservations list and still opens an ObsDetails screen. (This is different from an observation with a photo which is deleted remotely, which is currently causing [this crash](https://github.com/inaturalist/iNaturalistReactNative/issues/1485)

**To Reproduce**
1. Create a sound observation in iNat Next
2. Upload to iNat
3. Delete that observation via iNat web
4. See the observation still exists in MyObservations
5. Tap observation and open ObsDetails. Observation will look like a normal observation and will not show the "observation has been deleted" bottom sheet.

**Expected behavior**
Sound observations should be treated like all other deleted observations and should be removed from MyObservations when they are deleted remotely.

**Context (please complete the following information):**
 - App version: 0.32.3+91

**Comment by angielt** [comment]
Cannot replicate on 0.32.6+94 works as expected
