### ISSUE TITLE
Individual obs progress should update immediately after tapping individual upload button

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1580]
**Describe the bug**
When you tap the upload button on an individual observation, it does not immediately change to the in progress state.

**To Reproduce**
1. Make a new observation and save but don't upload
2. Tap on the upload button for that individual observation (not in the header
3. The header state updates immediately, but the individual obs upload state doesn't seem to update until the upload is complete, or until a media upload is complete

**Expected behavior**
The individual observation upload button should show partial progress immediately after being tapped.

**Context (please complete the following information):**
 - Device: iPhone SE (3rd gen)
 - OS: iOS 17.4.1
 - App version: 0.32.3 (91)

**Additional context**
This might require "faking" like 5% of progress or something.

**Comment by albullington** [comment]
Fixed in the [upload rewrite PR](https://github.com/inaturalist/iNaturalistReactNative/pull/1606)
