### ISSUE TITLE
Observation Deleted bottom sheet shows on wrong ObsDetail screen

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1585]
**Describe the bug**
The observation was deleted bottom sheet pops up for me on an observation that I haven't deleted remotely or locally. 

**To Reproduce**
1. Create some observations locally, upload them, and delete them on web
2. Go to the observation just below the last observation you deleted remotely in MyObservations
3. Tap into ObsDetails
4. See observation deleted screen, even though you haven't deleted this observation

**Expected behavior**
The deleted bottom sheet should only show on observations which have actually been deleted remotely.

**Screenshots**
![Screenshot 2024-05-20 at 3 05 11 PM](https://github.com/inaturalist/iNaturalistReactNative/assets/35536439/17000fb5-a7c9-4ffe-8c1c-67de01baa6da)

**Additional context**
Not sure if we need more exact repro steps here.

**Comment by angielt** [comment]
Cannot replicate in 0.32.6+94 on iPhone , works as expected
