### ISSUE TITLE
Changes to suggestions

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1592]
[Please reference these designs for the following states
](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=17975-46328&t=oRoFSIcq98XobLV2-4)

<img width="1518" alt="image" src="https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/cd204a8e-b2d4-4c25-ae45-36d6714d7d68">

Suggestions has six states
1. online - combined score suggestions [default if location permissions granted]
2. online - vision score suggestions (ignoring location)
3. online - user has not granted or has denied location permissions [default if no location permissions granted]
4. offline suggestions
5. no suggestions
6. loading suggestions

### Design changes for all states of suggestions
Several design changes came out of user testing the suggestions screen.

- [x] Change all checkmarks to the "dark" state instead of green
- [x] remove the "search for taxa" neutral button and replace it with a search icon in the top right of the header that links to the same screen
- [x] Remove all help text from this screen
- [x] Instead of "Nearby Suggestions" and "All Suggestions" labels, the second level of ID suggestions beneath the Top ID suggestion should always be labeled "Other Suggestions"
- [x] add an "Add an ID later" link at the bottom of all states. clicking this takes a user directly to obs edit without any ID added.

### 1. online - combined score suggestions

This is working as expected right now- it should always be the default view for suggestions after a user has given location permissions. All that's missing is the "Ignore location" button

- [x] Add a neutral button at the bottom of nearby suggestions that says "Ignore location" -- clicking this button should reload the screen (state 6) and then switch suggestions to state number 2 below.

### 2. online - vision score suggestions (ignoring location)

On iOS, Android, and web, we have an option for online suggestions that allows a user to include taxa not expected nearby. On the new mobile app, we decided to go with "Ignore location" and have the state calculate only using vision scores.

This state is accessed ONLY if a user clicks the "Ignore location" button in the first state above

- [x] When a user taps the "ignore location" button in the first state above, show state 6 (loading state) and then repopulate to state 2.
- [x] A button at the bottom that says "Use Location" should reload the screen (state 6) and then switch back to state 1 above
- [x] In state 2, only use the Vision score rather than the combined score to calculate ID suggestions. When a user toggles back to state 1, use the combined score.
     - Additional context provided by @loarie: The CV API returns Vision, Geo, and Combined scores. If no location is included in the API request, the Geo score is empty and the Combined score is the same as the Vision score. If a location is included the Vision scores and Combined scores are different. 

### 3. online - user has not granted or has denied location permissions
This is the default state for all users when they first use the app - a user should not see any location permissions modals in the app without opting in (see #1594)

- [ ] just like in state 2 above, the results will effectively only use the Vision score. Since no location is included in the API request, the Geo score is empty, and the Combined score is the same as the Vision score.
- [ ] add a primary green button that always appears first beneath the photos that says "Improve these suggestions by using your location" - clicking this button should open the location permission gate or the location permissions denied screen.
- [ ] If a user gives location permissions after prompting the location permissions modal, the suggestions screen should reload (state 6) and then show state 1 above.
 
### 4. offline suggestions
We have a view for offline suggestions that's working well. I updated the UI of the offline state, and I'd like for it to be able to be tappable to reload.

- [x] Update the offline state text and UI to match the designs
- [x] When a user taps the offline state banner, the suggestions screen should reload to try to fetch suggestions (state 6)

### 5. no suggestions
This is working as expected, aside from bugs. If no suggestions come up in any of the states above, a user should see the no suggestions text and the "Add an ID Later" link.

- [x] remove the "Continue" button and allow the "add an ID later" button to be the primary CTA here.

### 6. loading suggestions
This screen is already functional as is, the only thing is to add the "add an id later" button so a user can skip even the loading screen to get to obs edit.

### Notes

- [ ] Multiple of these states can coexist, see the [designs](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=17975-46328&t=oRoFSIcq98XobLV2-4) for examples.
- [ ] When a user accesses suggestions through the Obs Create flow, choosing an organism with the checkmark should open obs edit
- [ ] When a user accesses suggestions through obs detail, choosing an organism with the checkmark should open the ["Suggest ID?" bottom sheet](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=18086-29509&t=HqBKQyoQmhKphAhJ-4), which allows them to add optional remarks before they add the ID to an observation.

**Comment by abhasinat** [comment]
@albullington and I chatted about some edge cases to this and realized there are a few states we need to keep in mind here:

- If a user is coming from the AI Camera or Multicapture camera
     - [ ] and they have enabled location permissions, then the user should see state 1 above
     - [ ] and they have NOT enabled location permissions, then a user should see state 3 above
- If a user is coming from the Gallery (whether 1 photo or from the group photos screen) OR an existing observation detail page (when they click suggest ID)
     - [ ] and the gallery photo or observation has location, then the user should see state 1 above using the location pulled from that photo or observation's metadata
     - [ ] and the gallery photo or observation has NO location, then the user should see state 3 but with the the green "Improve these suggestions by using your location" button hidden, effectively showing only vision results and not prompting a user to improve them with location.
          -  when uploading from the gallery, this is to prevent a user from using their current location to get suggestions for a gallery photo, because it's unlikely that a user's current location matches the gallery photo's location -- they can add location on obs edit and then come back to suggestions to see improved suggestions later.
          - when adding an ID to an existing observation with no location, the user's location is irrelevant to adding an ID. so a user should only see vision suggestions, without a prompt to use their location.

**Comment by abhasinat** [comment]
Also one more thing I forgot to capture:

- [ ] If a user has gotten to suggestions from the "suggest ID" button on obs detail, clicking the "add an ID later" button should do the same thing as the back button - they will just return a user to the obs detail page immediately.

**Comment by albullington** [comment]
A couple lingering issues here:
1. If user taps reload button on offline suggestions while offline, nothing should happen. They should see the same offline suggestions
2. A user should not see the "USE LOCATION" button while offline or while there is an empty list of suggestions

**Comment by kueda** [comment]
Another one: when you scroll far enough that one of the sticky headers sticks, it has a transparent background so the text collides with any text it slides over. The section headers should probably have a white background.

![IMG_1385](https://github.com/inaturalist/iNaturalistReactNative/assets/22691/3333fd09-bd9c-4372-baa6-f9c9f4800268)
