### ISSUE TITLE
Changes to permissions

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1594]
After user testing, we found this was overwhelming for a user and the additional gallery permission led to negative feedback

**Current permissions flow for a first time user**
Home screen -> AI Camera button -> _camera permissions_ -> AI Camera -> Shutter button -> _Location permissions_ -> _Saving to gallery permissions_ -> _Additional gallery permissions_ -> Suggestions

**Desired permissions flow for a first time user**
Home screen -> AI Camera button -> _camera permissions_ -> AI Camera -> Shutter button -> _read AND write to gallery permission_ -> Suggestions -> "Improve these suggestions by using your location" button -> _location permissions_

### Key changes to make for permissions
- [x] whenever we ask to read OR write to the gallery, ask for a single modal to read AND write to the gallery - this should be the case whether the first permission a user sees is to save to the gallery or upload from the gallery.
- [x] prevent location permissions from automatically triggering on suggestions
- [x] Instead, location permissions should trigger opt-in on suggestions and explore and projects, and any time the user opens the location picker on obs edit
    - [x] On suggestions, the user should see a persistent button that says ["Improve these suggestions by using your location"](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=17975-46329&t=oRoFSIcq98XobLV2-11) if they have not allowed location access. Clicking this should open the location permission gate or location permissions denied screen. (this should be covered by #1592)
    - [x] On explore, when a user is viewing species nearby (the default state), they should see an [opt-in message to allow location access](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=17969-41209&t=oRoFSIcq98XobLV2-11). Clicking this should open the location permission gate or location permissions denied screen.
    - [x] On obs edit, the user will by default see an error state for location that says "add location." [Opening the location picker](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=707-8217&t=oRoFSIcq98XobLV2-11) on obs edit when a user has not allowed location should open the location permission gate or location permissions denied screen.
    - [x] On any map screen (including explore map, taxon detail map, obs detail map) whenever a user clicks the "current location" button, the location permission gate or location permissions denied screen.
    - [x] On projects, when a user is viewing nearby projects and hasn't given location access, they should see an [opt-in message to allow location access](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=6196-30539&t=oRoFSIcq98XobLV2-11). Clicking this should open the location permission gate or location permissions denied screen.
     - [x] If a user denied photo Read/write permissions, user should see the gallery or camera permissions denied screen on opening cameras and gallery
     - [x] If a user denied microphone permissions, user should see the microphone permissions denied screen on opening sound recorder

**Comment by jtklein** [comment]
Also:

- [ ] Fix: Location permission gate does not show correct title. Why?
