### ISSUE TITLE
Signed out users should not be able to vote in DQA

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1610]
**Expected behavior**
A signed out user should not be able to vote in the DQA (they can currently).

**Additional context**
Not sure what the appropriate UI is here (maybe check with @abhasinat) but we can at minimum disable the voting buttons for signed out users.

**Comment by abhasinat** [comment]
- [ ] If a user is logged out, hide the DQA button on obs detail

**Comment by kueda** [comment]
@abhasinat FWIW, this is not what we do on the web, and prevents signed out people from seeing important information about why an observation has the quality grade it does. On the web we do this by showing everything we normally show in the DQA, just without the voting functionality.

**Comment by abhasinat** [comment]
Makes sense- imo that's something we can change post-launch. People who understand what DQA is/care about it will be logged in.
