### ISSUE TITLE
Gallery permissions can't be granted after initial denial

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1612]
**Describe the bug**
If a user denies gallery access by selecting "keep add only," they won't be able to use the gallery at all later.

**To Reproduce**
1. Install a new build
2. Press the AI camera button
3. Allow camera access
4. Take a photo
5. Allow location access while using app
6. Allow to save photos to gallery
7. When prompted about photo library access, select “Keep add only”
8. Turn on all observation options
9. Tap gallery
10. Tap “open settings” from “please allow gallery access” screen
11. Tap “Photos” in iNat Next settings
12. See that the only options are “None” or “Add Photos Only”

**Expected behavior**
A user should be able to edit their permissions later in iOS settings.

**Screenshots**
<img width="201" alt="Screenshot 2024-05-29 at 1 19 20 PM" src="https://github.com/inaturalist/iNaturalistReactNative/assets/35536439/7d323ffe-775b-4fb8-8ae8-b6d8e70a7b57">

**Context (please complete the following information):**
 - Device: iPhone 13 pro
 - OS: 17.4.1

**Additional context**
This probably requires some investigation of what should happen after a user says "keep add only" and maybe more digging into [react-native-permissions](https://github.com/zoontek/react-native-permissions)

**Comment by budowski** [comment]
@albullington - does this happen to you still, with latest build?

**Comment by jtklein** [comment]
Blocked by #1808

**Comment by kueda** [comment]
Serious irony: we don't need the PHOTO_LIBRARY permission to import photos, but we *do* need it to add camera photos to an album and write location metadata, so if that's an important part of the camera flow, you'd think we'd be asking for it there and not the ADD permission... but we think it's too scary there b/c it (naturally) doesn't make sense to the user to ask for complete access to the photo library just to add some photos.

It is possible to write location metadata with just the ADD permission, but it will require a mod to react-native-cameraroll.
