### ISSUE TITLE
User should see previous Explore view when returning to Explore screen

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1614]
**Describe the bug**
Right now, the Explore view isn't sticky, which means if a user changes the Explore filters, navigates away from the Explore screen, and then navigates back to Explore, they will see their previous filters without their previous view.

**To Reproduce**
1. Go to Explore via the bottom tab bar
2. Search for Hong Kong as a filtered location
3. Switch to Observers view instead of the default Species view
4. Tap MyObservations on bottom tab bar
5. Tap back to Explore
6. See that the Explore screen still displays Hong Kong, your filtered search, but the view is back to Species View

**Expected behavior**
We should show users the entirety of the previous Explore screen, including their previous Explore view, rather than picking and choosing which parts to preserve.

**Comment by kueda** [comment]
@abhasinat can you sign off on this? I feel like you and I disagree about how this should work so I just want to be clear about what you want.
