### ISSUE TITLE
Handle null/undefined values in upload process

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1637]
**Describe the bug**
Seeing a few [errors caught in Grafana](https://scopus.inaturalist.org:3000/d/H3LCbBLIz/inat-next-errors?orgId=1&from=now-7d&to=now&var-Filters=parsed_user_agent.version%7C%3D%7C0.32.6) for app version 0.32.6, which are probably all related to the [upload refactor](https://github.com/inaturalist/iNaturalistReactNative/pull/1606): 

- [x] Cannot read property 'currentIncrements' of undefined (updateTotalUploadProgress)
- [ ] Cannot read property 'file_url' of null (MyObservationsContainer)
- [x] Cannot read property 'uuid' of null (createUploadProgressObj)
- [x] Cannot read property 'y' of undefined (ObservationsFlashList)

**Comment by kueda** [comment]
* "Cannot read property 'currentIncrements' of undefined (updateTotalUploadProgress)" fixed in 8dbbca04d927121f1ee7a18e5d785cc68e3a0b50

**Comment by kueda** [comment]
If it's not happening, let's call it done.
