### ISSUE TITLE
Local observations aren't being deleted when logged out

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1654]
**Describe the bug**
We're checking for a logged in user before running the deletions code, which means if a user is logged out, makes observations, and then deletes them, they will still see "Log in to contribute & sync X observations" and the observations can never be deleted.

**To Reproduce**
1. Make 2 observations as a logged out user
2. Delete both observations while still logged out
3. See the header text and toolbar text, saying you still have 2 observations to upload. Those observations will still exist in Realm

**Expected behavior**
A logged out user should be able to delete local observations. The only time we should check for a current user in the deletion flow is when we're running API calls, like syncing remotely deleted observations.

**Context (please complete the following information):**
 - App version: 0.32.6

**Comment by kueda** [comment]
This will probably be affected by #1670 so we might want to wait for that before working on this.
