### ISSUE TITLE
Adding photo after denying gallery read permissions results in an extra fake photo

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1662]
**Describe the bug**
If you grant camera, location, and gallery write permissions but deny gallery read permissions, taking a photo results in an extra photo that's just an activity indicator on ObsEdit.

**To Reproduce**
1. Install a fresh build
2. Enter the AICamera
3. Allow Camera Access
4. Tap the shutter
5. Allow Location Access
6. Allow "save photos to your gallery"
7. When prompted for "additional access to your photo library" tap "Keep Add Only"
8. Tap the green button next to a suggestion
9. On ObsEdit, your photo is there, but there's an extra square next to it with an activity indicator

**Expected behavior**
There should not be an extra photo.

**Screenshots**
![IMG_1080](https://github.com/inaturalist/iNaturalistReactNative/assets/22691/232f6a07-4380-4900-9651-6ccaf7a566f8)

Also see this [recording in Slack]([https://inaturalist.slack.com/archives/C02G5AATVGA/p1717862920751959](https://www.google.com/url?q=https://inaturalist.slack.com/archives/C02G5AATVGA/p1717862920751959&sa=D&source=docs&ust=1718051840988509&usg=AOvVaw18fHf1GLwQEjRT7Ke3mENr))

**Context (please complete the following information):**
 - Device: iPhone SE (3rd generation
 - OS: iOS 17.5.1
 - App version: 0.33.0 (95)

**Additional context**
Reported by Carrie. Could be related to #1612 so this might be for you, @budowski

**Comment by jtklein** [comment]
Blocked by #1808

**Comment by kueda** [comment]
As far as I can tell this isn't happening anymore. Might have been fixed by permissions changes, but more likely fixed in changes to managing obs creation state.
