### ISSUE TITLE
Photos not saved to gallery when read permission granted but not write

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1665]
**Describe the bug**
If you grant camera, location, and gallery write permissions but deny gallery read permissions, taking a photo does not write it out to the gallery

**To Reproduce**
1. Install a fresh build
2. Enter the AICamera
3. Allow Camera Access
4. Tap the shutter
5. Allow Location Access
6. Allow "save photos to your gallery"
7. When prompted for "additional access to your photo library" tap "Keep Add Only"
8. Tap the green button next to a suggestion
9. Tap SAVE
10. Check the photos app. The photo you just took does not appear.

**Expected behavior**
If I grant permission to save photos to the gallery, I expect them to be saved there.

**Context (please complete the following information):**
 - Device: iPhone SE (3rd generation
 - OS: iOS 17.5.1
 - App version: 0.33.0 (95)

**Additional context**
Reported by Carrie. Could be related to #1612 and #1662, so this might be for you, @budowski

**Comment by kueda** [comment]
Might be fixed by https://github.com/inaturalist/iNaturalistReactNative/pull/1680

**Comment by jtklein** [comment]
Blocked by #1808

**Comment by kueda** [comment]
Can't replicate, probably got fixed in the interim.
