### ISSUE TITLE
AICamera to ObsEdit to StandardCamera to ObsEdit to Suggestions and back lands on AICamera

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1666]
**Describe the bug**
Trying to add more photos to an obs after having been in the AICamera seems to return you to the AICamera from Suggestions.

**To Reproduce**
1. Enter the AICamera and take a picture
2. Choose a taxon on Suggestions
3. On ObsEdit, tap the "+" button and open the StandardCamera
4. Take a picture to return to ObsEdit
5. Edit the taxon to enter Suggestions
6. On Suggestions, tap the back button in the upper left
7. You land in the AICamera

**Expected behavior**
When you tap back from Suggestions you should land on ObsEdit.

**Context (please complete the following information):**
 - Device: iPhone SE (3rd generation
 - OS: iOS 17.5.1
 - App version: 0.33.0 (95)

**Comment by albullington** [comment]
Tried to replicate using the steps above (latest build is 0.33.1+96) and I'm landing back on ObsEdit as expected.

**Comment by kueda** [comment]
Can't replicate with these steps either.
