### ISSUE TITLE
Explore species map view should not default to 0,0

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1684]
**Describe the bug**
Right now, if I click the explore icon on taxon detail, it opens the map view of that taxon, worldwide, with the map centered at 0,0. The map should instead contain the bounding box of all that taxon's observations, zoomed to fit the bounding box in the map.

**To Reproduce**
1. Go to explore tab
2. tap any north american species to view taxon detail
3. tap the explore button in taxon detail
4. view the map centered at 0,0
5. pan to an observation, zoom in far enough to click on it
6. view obs detail for that organism
7. tap the back button
8. view the map centered at 0,0 again 

**Expected behavior**

- [x] When a user first lands on explore-observations-map view with location set to worldwide, the map should contain the bounding box of all that taxon's observations, zoomed to fit the bounding box in the map.
- [x] If a user zooms in on the map to view the individual observation pins, when they click in to view obs detail and then click back, they should return to the zoomed-in view of the map they were on before, not have it return to 0,0

**Comment by jtklein** [comment]
Currently, observations and tiles are not showing at all for me on the Explore map.
