### ISSUE TITLE
Add a reset button to the taxon chooser in explore

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1685]
Right now, it's impossible to reset the taxon search to all organisms except by clicking into explore filters. To fix that:

- [x] Please add a "Reset" button in the top right of the header on the search taxa modal in explore. Clicking this should bring a user back to the view of explore they were on previously filtered by All organisms. View the [designs](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=9739-32368&t=ENHrsYjdtlNMP2GC-11) here.
- [x] Please add this button on the user search and project search inside of explore filters as well.

Note: this UI is the exact same as the reset button on the search location modal in explore.

<img width="629" alt="image" src="https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/b2f2ee7f-fb99-4a3a-b5c3-edaca1a79483">

**Comment by albullington** [comment]
@abhasinat it looks like User and Projects search also are missing a reset button. Should we expand this issue to include all three?

**Comment by abhasinat** [comment]
sure, I think that's a good idea. updated.
