### ISSUE TITLE
Vision plugin continues classifying when camera is closed

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1725]
This might be a bug in https://github.com/inaturalist/vision-camera-plugin-inatvision, or maybe it's a bug in how we're using it, but I'll err on the side of the latter: when you open the AICamera, allow the model to load, then close it, the vision plugin continues classifying... something, maybe empty frames.

To prove this, put an NSLog statement in the [`recognitionHandler`](https://github.com/inaturalist/vision-camera-plugin-inatvision/blob/main/ios/VisionCameraPluginInatVision/VisionCameraPluginInatVision.m#L115-L123) and watch the Console after you've closed the camera. Your log statement will continue printing pretty much until you close the app.

We might be able to solve this by properly unmounting the AICamera when it's not visible, which seems to be the source of lots of fun React Navigation bugs, but there might also be a potential fix in the library, e.g. if you receive 10 blank frames in a row maybe through an error.

This probably goes a long way toward explaining why this app eats battery.

**Comment by jtklein** [comment]
I could not replicate this.
Adding a NSLog to the `[recognitionHandler](https://github.com/inaturalist/vision-camera-plugin-inatvision/blob/main/ios/VisionCameraPluginInatVision/VisionCameraPluginInatVision.m#L115-L123)` stopped logging after navigating back out from the camera with the (x) button.
Also after backing out from the camera I could see no more reference to the VNCoreMLRequest assuming it was correctly garbage collected.

**Comment by kueda** [comment]
Yup, can't repro either.
