### ISSUE TITLE
Landscape photos have portrait orientation

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1726]
**Describe the bug**
When you take photos in landscape orientation in the StandardCamera, they end up in portrait orientation.

**To Reproduce**
1. Enter the StandardCamera
2. Rotate your device to landscape orientation; note that the buttons rotate to match
3. Take a photo
4. Note the preview is in portrait orientation
5. Tap the green checkmark to get to Suggestions; photo still in portrait orientation
6. Choose a taxon to get to ObsEdit; photo still in portrait orientation
7. Tap "Save" to get to MyObs; photo still in portrait orientation

**Expected behavior**
Landscape-oriented photos should remain in landscape orientation

**Screenshots**
From left to right, this screenshot shows previews of photos take in

1. Landscape right
2. Landscape left
3. Portrait

![Screenshot 2024-06-28 at 6 00 42 PM](https://github.com/inaturalist/iNaturalistReactNative/assets/22691/17c8c46d-a538-4012-be2f-f4e569fba696)

**Context (please complete the following information):**
 - Device: iPhone SE (3rd generation)
 - OS: iOS 17.5.1
 - App version: 0.34.0 (97) (but happening in 41445beed636e5e4119f7a2a8f24def41433fb48)

**Additional context**
Probably related to https://github.com/inaturalist/iNaturalistReactNative/pull/1713

**Comment by jtklein** [comment]
Have reverted #1713 this should remove this bug. I have no device though on where this appears, so please confirm and close if possible.

**Comment by kueda** [comment]
I think your reversions fixed it. What device were you using? I'm not sure why an SE would be different than a 13.
