### ISSUE TITLE
LocationPicker doesn't always update accuracy

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1734]
**Describe the bug**
When creating a new observation, the accuracy doesn't update correctly from LocationPicker -> ObsEdit, so an observation will be saved with a different accuracy than the user selected.

**To Reproduce**
1. Go to AICamera and create a photo
2. Tap on LocationPicker from ObsEdit
3. Pan out so you have a higher location accuracy (say 120m)
4. Save and land on ObsEdit -- you'll still see a location accuracy of 5

**Expected behavior**
LocationPicker should update accuracy correctly and store this via `updateObservationKeys`.

**Context (please complete the following information):**
- iOS
 - App version: v0.34.0+97

**Additional context**
LocationPicker appears to be updating accuracy correctly for synced observations (MyObs -> ObsDetails -> ObsEdit -> LocationPicker -> ObsEdit), so this might be related to fetching the user's current location or might be specific to unsynced observations.

**Comment by kueda** [comment]
FYI, this isn't just about accuracy, it's also about coordinates. I think ObsEdit is just overwriting these values with the original values upon return.

**Comment by budowski** [comment]
@albullington - is this still happening to you with latest main build? I tried both on Android and iOS devices and couldn't recreate this

**Comment by albullington** [comment]
Closing since I can't reproduce anymore.
