### ISSUE TITLE
Projects keyboard & UI fixes

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1737]
Right now when you land on the projects screen, the "search for a project" search bar is selected and the keyboard is open.

- [ ] By default when you land on this screen, the search bar should not be selected and the keyboard should be hidden. The keyboard should only open when a user taps the search for a project bar.
- [ ] When the keyboard is visible, tapping anywhere outside the keyboard and search bar should dismiss the keyboard.
- [ ] When you type into the keyboard, the X close button should be vertically aligned inside the search bar, which it is not currently.
![IMG_8747](https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/72b6e34c-019e-4b39-826e-fdd067f84f4f)

**Comment by albullington** [comment]
Closed by https://github.com/inaturalist/iNaturalistReactNative/issues/1737. @budowski, when you make PRs, can you please use "Closes #1737" to close the issues automatically when we merge the PRs?
