### ISSUE TITLE
Show iconic taxon image by default on AI camera

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1739]
Right now, when you are using the AI camera offline, you see an infinite loading wheel where the image is since we can't load the image, along with a scientific name.

Instead, we should show the iconic taxon image (in white) associated with that organism by default instead of a loading wheel. Then, if a photo loads, it should overwrite the iconic taxon image, similarly to how the scientific name is overwritten by common and scientific name when it's accessible.

@kueda mentioned that this may not be possible and would require research to see if we can load the iconic taxon associated with an organism while offline.

Existing implementation:
![IMG_8751](https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/dda8d490-2b2d-4350-8a8d-cf73f2034dba)

Desired implementation:
![image](https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/e2f37049-38cd-4a80-a0b9-eb852f303b28)

**Comment by kueda** [comment]
We should make sure it works this way for all uses of the TaxonResult component... assuming this is possible.
