### ISSUE TITLE
Hide wikipedia link in TaxonDetails if there's no URL

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1740]
**Describe the bug**
There are some edge cases like [this one](https://www.inaturalist.org/taxa/231783-Strangalia-acuminata) where a taxon can have a wikipedia description but not a url. So we're showing a wikipedia link that the user can't open.

**To Reproduce**
1. Go to Strangalia acuminata Taxon Details screen via Explore
2. Tap on Read more on Wikipedia link
3. Nothing happens

**Expected behavior**
Right now, we're checking to see if a user can open the link and doing nothing if the wikipedia url doesn't exist. Instead, we should hide the "Read more on Wikipedia" link (or defer to @abhasinat on what the preferred UX is here).

**Context (please complete the following information):**
OS: iOS
App version: v0.34.0+97

**Comment by kueda** [comment]
Note, also merits some exploration of why the link for that specific taxon isn't working, b/c the wikipedia page exists.
