### ISSUE TITLE
Keyboard prevents user from giving location permission

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1743]
**Describe the bug**
When adding a location for the first time from ObsEdit -> LocationPicker, a user will see the keyboard covering the bottom half of the LocationPermissionsGate.

**To Reproduce**
1. Install a fresh build
2. Create an observation with a gallery photo
3. Tap on LocationPicker to edit location
4. LocationPermissionsGate will pop up with the keyboard covering the button to confirm or deny

**Expected behavior**
Keyboard should not block the location permissions screen.

**Screenshots**
![IMG_1915](https://github.com/inaturalist/iNaturalistReactNative/assets/35536439/fe14d2de-82d1-4e95-af35-13469835c7eb)

**Context (please complete the following information):**
OS: iOS
App version: v0.34.0+97

**Additional context**
This is likely happening because the LocationPicker is loading underneath the LocationPermissionsGate. Maybe it's better to show the location permissions gate in ObsEdit before navigating to the Location Picker.

**Comment by jtklein** [comment]
I had to fix this in my current branch while working on changes to permissions.
