### ISSUE TITLE
Refactor location fetch using watchPosition

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1744]
Current useUserLocation and useCurrentObservationLocation try to fetch location until the accuracy is good enough, but they do so using the Geolocation library's getCurrentPosition() method. Given my experience in the field, I'm not convinced this actually works very well. I often see the fetch giving up when the accuracy is still 50m, especially while offline, whereas switching the native iOS app quickly gets the accuracy down below 10m.

Instead, I think we should attempt a refactor using the watchPosition() method, which would start that process up and receive location updates until the accuracy is good enough, and then stop watching. I've experimented with this approach a bit, but I struggled to successfully stop watching, but I was probably messing something up.

So the task here is to start by refactoring useUserLocation to use watchPosition(). It should expose the same API (i.e. the hook should return the same values).

I would not spend more than a day or two on this without taking stock and discussing. This might also be the solution to #1688, which I'm stuck on and need to hand off.

**Comment by albullington** [comment]
Closed by https://github.com/inaturalist/iNaturalistReactNative/pull/1788
