### ISSUE TITLE
Radio Button Sheet UI Fixes

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1746]
Right now, the spacing on radio button bottom sheets have spacing that doesn't match the designs. Please update the radio button sheet component with the following spacing. This should apply to:
- Obs Edit - Captive/Cultivated, Geoprivacy
- Explore - Change view
- Explore FIlters - sort by, date observed, date uploaded, photo licensing

Here's what they look like right now. I've color-coded the incorrect spacings:
<img width="1414" alt="image" src="https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/f4995f89-78a7-478a-b32a-6c3a62aadcc7">

And here's the correct spacing they should have, with the colors indicating which numbers apply to which spacing:
<img width="1414" alt="image" src="https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/35907542-9893-403f-92ca-0a8b01dcef25">

Correct spacing:
Pink - 12pt
Green - 3pt
Blue - 15pt
Orange - 10pt

**Comment by jtklein** [comment]
@abhasinat Blue is 20pt in Figma.
