### ISSUE TITLE
Online suggestions location permissions

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1755]
More changes to the online suggestions screen.

This screen is the default state for all users when they first use the app - a user should not see any location permissions modals in the app without opting in (see https://github.com/inaturalist/iNaturalistReactNative/issues/1594)

- [x]  just like in regular online suggestions, the results will effectively only use the Vision score. Since no location is included in the API request, the Geo score is empty, and the Combined score is the same as the Vision score.
- [x]  add a primary green button that always appears first beneath the photos that says "Improve these suggestions by using your location" - clicking this button should open the location permission gate or the location permissions denied screen.
- [ ]  If a user gives location permissions after prompting the location permissions modal, the suggestions screen should reload and then show the online suggestions state with location enabled.
- [x] per [this comment](https://github.com/inaturalist/iNaturalistReactNative/issues/1592#issuecomment-2183421638), make sure the Improve With Location button does not appear unless a user is coming from the AICamera or Camera screen. It should not appear when a user is coming from the PhotoGallery, GroupPhotos, PhotoSharing, ObsEdit, ObsDetail, etc.

This is split off from the bigger enhancement issue with changes to suggestions (https://github.com/inaturalist/iNaturalistReactNative/issues/1592) because it's dependent on the changes to permissions issue (https://github.com/inaturalist/iNaturalistReactNative/issues/1594). Once that is finished, we'll be able to prompt a user for location permissions on Suggestions when coming from the AICamera or StandardCamera.

**Comment by jtklein** [comment]
As exemplified here [const { hasPermissions, renderPermissionsGate, requestPermissions } = useLocationPermission( );](https://github.com/inaturalist/iNaturalistReactNative/blob/6fa6db58111365eff19478903b25c0b69b0c9324/src/components/Suggestions/SuggestionsContainer.tsx#L53) I have added a hook to check for location permission now.
You can use the `hasPermissions` variable for conditional rendering of components that should only show with or without location permission.

This [line](https://github.com/inaturalist/iNaturalistReactNative/blob/6fa6db58111365eff19478903b25c0b69b0c9324/src/components/Suggestions/SuggestionsContainer.tsx#L251) renders the PermissionGate, and you can add callbacks there if you have to react to the permission being granted for example. Example with callbacks [here](https://github.com/inaturalist/iNaturalistReactNative/blob/6fa6db58111365eff19478903b25c0b69b0c9324/src/components/Explore/SearchScreens/ExploreLocationSearch.js#L164).
