### ISSUE TITLE
ObsEdit not refetching location

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1778]
This is hard to reproduce consistently, but ObsEdit does not seem to actually continuously fetch coordinates, or if it does it seems to bail around 30-50 m of accuracy.

Often what this looks like is the the activity indicator next to the location on ObsEdit is still spinning, but the location is not updating, and the system location fetch indicator in the status bar says it's not actively fetching anymore.

We can discuss priority, but IMO this blocks Soft Launch.

This is probably closely related to #1688 and one potential solution might be #1744, so consider this kind of an umbrella / tracking issue.

**Comment by albullington** [comment]
Possibly fixed by https://github.com/inaturalist/iNaturalistReactNative/pull/1788

**Comment by kueda** [comment]
As far as I can tell, ObsEdit *is* fetching location continuously as of #1788 so this was probably fixed by Amanda's work there. #1841 addresses some related bugs, and #1839 is probably unrelated to the work on location fetching.
