### ISSUE TITLE
Explore view doesn't retain geographic bounds in grid view

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1780]
**Describe the bug**
When navigating to a smaller map area, then viewing those observations in grid/list view, then navigating away from and back to Explore, the geographic bounds are not maintained. The grid/list will instead show all of a user's observations again, instead of the observations filtered by the map bounds.

**To Reproduce**
1. On MyObs, press the Explore button in the header to view your observations in Explore
2. Go to map view
3. Zoom in on an area with observations and tap REDO SEARCH IN MAP AREA
4. Go to grid view and tap on an observation
5. On obs detail tap back
6. Suddenly, your geographic search no longer applies and you’re just looking at explore grid view observations of all your observations

**Expected behavior**
Once a user searches for observations within a geographic bound, they should continue to see only the observations within that bound in grid/list view. This is still true even if they navigate away from Explore and back to Explore.

**Context (please complete the following information):**
 - App version: 0.35.2+100

**Comment by jtklein** [comment]
Have done a bit of research but I think this takes more time than I have this iteration.
