### ISSUE TITLE
Navigate to a new Explore instance when tapping the obs count from species view

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1783]
**Describe the bug**
When you tap the number of observations from the Species view of Explore, it just sets the taxon filter of the current view of Explore and there's no way to get back unless you know to go to the Filters dialog and reset the filters.

**To Reproduce**
1. Go to Explore and if you're not already on the Species view, get into Species view
2. Tap the "x observations" text on one of the species
3. The species filter gets applied and you enter the Observations view
4. There no visible way to undo what you just did

**Expected behavior**
Tapping that text should load a *new* instance of the Explore screen that you can back out of.

**Context (please complete the following information):**
 - Device: iPhone SE, 3rd gen
 - OS: 17.5.1
 - App version: 0.35.2 (100)

**Additional context**
There are a lot of overalpping problems here, and doing this will probably be a short trip to navigation hell (what happens you go Explore -> TaxonDetails -> Explore -> species view -> tap observations count?). I would not spend more than a day on this before conferring with Abhas again.

Alternative solutions:

* Make the obs count text not tappable (it's inaccessibly small with no indication it can be tapped)
* Add a visible way to clear the taxon filter in the Explore header
* Interactions with each species that aren't navigating to TaxonDetails should be within a kebab menu button, so it's clearly interactive and of an accessible size. Tapping that could open an alert or a popover.

**Comment by abhasinat** [comment]
This is something that won't be completely solved till we implement changes in #1899. Here's the solution to go with after talking to Ken-ichi and Angie:

- [ ] make the obs count text not tappable for soft launch.

**Comment by angielt** [comment]
More context from conversation with Abhas and Ken-ichi: This issue isn't currently possible because the goal is for the user to back out of explore and create new instances of explore as many times as needed and it isn't possible with how we are storing explore states currently until we rewrite explore.
