### ISSUE TITLE
Confidence interval dots dont seem to be displaying correctly

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1784]
**Describe the bug**
Right now, the confidence interval dots on suggestions don't seem to be matching combine score outputs.

**Example**
Using this [observation](https://www.inaturalist.org/observations/227495623) as an example. Here is the [CV output](https://www.inaturalist.org/computer_vision_eval?observation_id=227495623).

Below are screenshots of the CV next to what we see in iNat Next:
<img width="538" alt="image" src="https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/84688f10-b029-498f-96db-871404acc350">

**Expected behavior**
The dots should follow the following values for combined scores (this should apply to vision scores when a user is not using location or hasn't given location permissions):
- 5 dots: 80-100
- 4 dots: 60-80
- 3 dots: 40-60
- 2 dots: 20-40
- 1 dot: 0-20

In the above example, Common Blue should have 5 dots, and the rest should have 1 dot.

**Context (please complete the following information):**
 - iPhone 13 Pro: iOS 16.6.1)
 - 0.35.0+99

**Comment by kueda** [comment]
This was actually due to a problem with the scores being returned by the vision API, which was fixed in https://github.com/inaturalist/inatVisionAPI/commit/2510a98f5cfdb3aff2f297a09d92240bf0c6c3fe
