### ISSUE TITLE
Hide debug mode

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1785]
Currently anyone can enter debug mode from the About screen, which is going to be confusing for most people. Instead we want to hide it so that only people who know to look for it will turn it on:

- [x] Hide existing "Debug Mode: off" button
- [x] Tapping three times on the version on the About screen turns on debug mode
- [x] When debug mode is on, show the button to turn it off. It should read "Turn Off Debug Mode"
- [x] Hide the network tool in Release builds. It doesn't really show any secrets that can't be extracted through decompilation but it does make them easier to find

**Comment by abhasinat** [comment]
Adding on to this:

- [ ]  Make sure the text in the "Turn off debug mode" button on the about screen is Heading4 in all caps, right now it appears to be in camel case.
- [ ] All buttons and the header on the debug screen itself should have text in Heading4 in all caps
