### ISSUE TITLE
For top ID suggestion on suggestions, change the checkmark to be green

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1801]
@tiwane and @kueda have both mentioned that the top ID suggestion needs more of a clear visual focus.

if there is a top ID suggestion on the suggestions screen, turn the checkmark for the top ID suggestion ONLY to be the "green" state. all other suggestions should remain in the "dark" state.

Here's an example, as updated in the [designs](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=17975-46328&t=xXLHdwIEYusfw5TS-4):
<img width="935" alt="image" src="https://github.com/user-attachments/assets/38aaaa2b-db51-4e0a-a354-844aa0cb04f3">

**Comment by jtklein** [comment]
The green checkmark means "I have seen this taxon" in other screens.

**Comment by abhasinat** [comment]
I know. We'll have to see what happens in user testing.
