### ISSUE TITLE
"Contact Support" and "Teacher's Guide" buttons should link to Freshdesk

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1803]
Right now on the help page, the "Contact Support" button opens an email. @tiwane would like this to change.

- [x] Tapping the "Contact Support" button on the Help page should open an in-app browser that leads directly to https://help.inaturalist.org/en/support/tickets/new
The header for the in-app browser should have a back button and the title should read "Contact support"
- [x] Tapping the "Teachers' Guide" button on the Help page should open an in-app browser that leads directly to https://help.inaturalist.org/en/support/solutions/articles/151000170805-inaturalist-teacher-s-guide
The header for the in-app browser should have a back button and the title should read "Teachers' Guide"

**Comment by jtklein** [comment]
Might be more work than expected, because a reCaptcha is blocking the site from loading in the in-app browser.

**Comment by kueda** [comment]
Rolling this into https://github.com/inaturalist/iNaturalistReactNative/issues/1934. @jtklein's concern should not be an issue since we're opening the freshdesk form page in an external browser.
