### ISSUE TITLE
Select this taxon button should only show up when navigated through suggestions

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1813]
**Describe the bug**
Right now, the "select this taxon" button is showing up when i navigate to taxon detail pages outside of suggestions.

**To Reproduce**
1. Make sure you are logged in.
2. Tap the explore button in the nav bar
3. Tap any species to go to its taxon detail screen
4. scroll to "taxonomy" and click any taxon
5. See "Select this taxon" button

This is also happening if i navigate to a taxon detail page from other places in explore or from obs detail and then click on another taxon under taxonomy.

**Expected behavior**
The "select this taxon" button should only appear when a user is logged in and has navigated to a taxon detail page inside of the suggestions flow, accessed through the "suggest id" button on obs detail or the obs create flow.

**Context (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 17.5.1
 - App version: 0.36.0 (101)

**Comment by albullington** [comment]
I don't think this is quite accurate -- we also want the "Select this Taxon" button to show up if a user comes through TaxonSearch, right? There's at least one scenario where they can land on TaxonSearch without landing on Suggestions:

1. create an obs with no evidence
2. land on obs edit
3. tap "Add an ID"
4. land on Taxon Search, not Suggestions

from there, if a user taps into TaxonDetails, I assume they would get stuck outside of the obs create flow the same way they could from Suggestions, so we should show the button there as well.

**Comment by abhasinat** [comment]
I guess in my head, this is still "from suggestions" because the user clicked add an id inside of obs edit.
