### ISSUE TITLE
Increase width of progress bar around circle

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1821]
The width of the progress bar that goes around the arrow of individual observations is a bit too small from what i can tell. the width of the circle should be 2px all the way around. Designs are [here](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=772-12221&t=xXLHdwIEYusfw5TS-11) for reference.

<img width="482" alt="image" src="https://github.com/user-attachments/assets/4c0bdaf2-acb2-4ba5-af86-c81ba20b818e">

**Comment by jtklein** [comment]
In the [code](https://github.com/inaturalist/iNaturalistReactNative/blob/860b2ae9240d13d47f8c7a67a911600c3d770519/src/components/SharedComponents/UploadStatus/UploadStatus.js#L165-L166) it is set to 2p.
What should we do, increase to 3?

**Comment by abhasinat** [comment]
Hm... lets try 2.5p
