### ISSUE TITLE
Add an internal feedback form to the menu

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1844]
We need a better internal feedback mechanism in iNat Next for soft launch.

- [x] Add a new menu item in the drawer menu titled "Feedback" that shows up below settings on [logged in menu](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=3771-24591&t=4T8KNWs0DYZBEwWr-11) and below help on [logged out menu](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=3773-22107&t=4T8KNWs0DYZBEwWr-11)
- [x] When a user taps this, open a text field [bottom sheet](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=19101-54252&t=4T8KNWs0DYZBEwWr-11) titled "Feedback"
     - [x] If a user is offline, show the [offline alert](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=19101-54253&t=4T8KNWs0DYZBEwWr-11)
- [x] When a user clicks submit, open a [native iOS/Android alert](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=19101-53821&t=4T8KNWs0DYZBEwWr-11) with the text in the designs.
     - [x] if a user has not typed any text in the form, the submit button should be inactive/unclickable
- [ ] ~~create a new inaturalist email with the email ID feedback@inaturalist.org. if you don't have permissions to do this, ask @carrieseltzer or @loarie~~
- [ ] ~~On submit send an email to feedback@inaturalist.org with the following data:~~
     - ~~What is the user's login state (signed in, signed out)~~
     - ~~What is the state of their obs wheel (ai camera, full obs wheel)~~
     - ~~How many observations have they created? (0, 1-9, 10-100, 100-999, 1000+)~~
     - ~~If logged in, what's their username?~~
     - ~~If logged in, how many ID's have they made? (0, 1-9, 10-100, 100-999, 1000+)~~
     - ~~Text from the feedback form they fill out.~~

Here's an example of what the format of the email to send to feedback@inaturalist.org might look like (ignore slashes "/" in the actual implementation, those are just indicating different options). This would theoretically allow us to set up labelling with filters.

```
signed in: yes/no
obs wheel: ai camera/wheel
observations: 0/1-9/10-99/100-999/1000+
username: username/loggedout
ids: 0/1-9/10-99/100-999/1000+/loggedout

[text from form]
```

However, maybe spend an hour or two looking into ways of structuring it more formally, like maybe https://developers.google.com/gmail/markup/getting-started

**Comment by kueda** [comment]
Ok revised final step based on the fact that we can't send client emails:

- [ ] Make a logger with the context of `feedback`, e.g. `const logger = log.extent( "feedback" )`
- [ ] When the user submits the form, log an `info` level event where the user's message is the only message, e.g. `logger.info( feedbackMessage );`

Let's just start with that and forget about the user attributes like number of obs or add obs button state.
