### ISSUE TITLE
Scientific Names view is not working on all screens

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1849]
**Describe the bug**
If I have taxon names display set to "Scientific Name," it is not displaying correctly in all places.

**To Reproduce**
1. Make sure you're logged in
2. Go to settings
3. Change your Taxon names display to "Scientific Name" only
4. Navigate to My observations/Home and see it display incorrectly
5. Navigate to explore/species view and see it display incorrectly
6. view any obs detail or taxon detail to see it display correctly

**Expected behavior**
When a user has scientific name display on, they should always see only scientific name. It's currently not working on:
- Home Screen/My observations
- Explore/species view

**Context (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 17.5.1
 - App version: 0.36.0 (101)

**Comment by albullington** [comment]
Alex is seeing this still happening, and I can replicate in some places for Scientific name first or Scientific name only.

Repro steps:
1. Go to Settings and toggle scientific name only
2. Go to MyObservations -- you'll see observations with Common Name/Sci Name in both grid/list view
3. Go to ObsDetails for one of those observations -- you'll see scientific name only
4. Go to Explore Species View -- you'll see Common Name/Sci Name
5. Go to Explore Observations View -- you'll see Sci name only in both grid/list view

No idea why this isn't being set and shown consistently.
