### ISSUE TITLE
AICamera suggestion appears on ObsEdit after choosing Add ID Later

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1860]
**Describe the bug**
When you get a suggestion in the AICamera, proceed to Suggestions, and choose "Add an ID Later", the suggestion from the AICamera is set as the identification on ObsEdit.

**To Reproduce**
1. Open the AICamera and point it at something that yields a suggested taxon
2. Tap the shutter to proceed to Suggestions
3. Tap "Add an ID Later" at the bottom of the screen to proceed to ObsEdit
4. On ObsEdit, the taxon suggested in the AICamera is already set as the identification

**Expected behavior**
"Add an ID Later" should take you to ObsEdit with *no* taxon selected.

**Context (please complete the following information):**
 - Device: iPhone SE (3rd gen)
 - OS: iOS 17.5.1
 - App version: 0.36.1 (102)

**Additional context**
This feels like AICamera setting observation properties for no reason.

**Comment by albullington** [comment]
afaik this was fixed last week: https://github.com/inaturalist/iNaturalistReactNative/pull/1830
