### ISSUE TITLE
User see full obs wheel when they first sign up

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1883]
**Describe the bug**
I made a new test account, and after I clicked "continue to iNaturalist" on the email confirmation screen, I saw the full obs wheel button instead of the AI camera button

**To Reproduce**
1. on fresh install, sign up for a new inat account
2. click "continue to iNaturalist" on the email confirmation screen
3. land on the home screen with [this design](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=354-7435&t=LLC3d54kJNd1pDhj-11)
4. see the + button obs wheel instead of the AI camera

**Expected behavior**
The default state for all users, logged in, logged out, or signed up should always be AI camera on a fresh install of the app.

**Context (please complete the following information):**
Device: iPhone 13 Pro
OS: iOS 17.5.1
App version: 0.73.0 (103)

**Comment by albullington** [comment]
@abhasinat I wasn't able to replicate this with a fresh build, following the repro steps above. Do you have any additional steps or a video recording?

**Comment by abhasinat** [comment]
hmmm, i can't replicate this either but now I ran into an entirely different bug that I've never seen before - making a brand new account and then clicking "continue to inaturalist" logged me into my regular abhasm inat account on a fresh install.
