### ISSUE TITLE
Signing out of an account with 0 observations doesn't always work properly

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1886]
**Describe the bug**
When you click signout of a logged in account that has zero observations (in mine and @tiwane's cases, we made brand new accounts) - the home screen still seems to display the username of that account that just logged out. in tony's case, the old username remained while being populated with his new account's data.

**To Reproduce**
1. Create a new account
2. make 0 observations
3. Try to sign out
4. View the home screen still displaying the username of the user that just logged out
5. log in with normal inat account and see if the old account name is still displayed

**Expected behavior**
This isn't happening when I log out of my normal account - the home screen immediately refreshes to be the logged out home screen, which it should always do when a user signs out. When I log into my regular account after I log out of my test account, the old name should definitely not show.

**Screenshots**
Tony's [screen recording](https://inaturalist.slack.com/archives/C02G5AATVGA/p1721918059349559) in slack.

**Context (please complete the following information):**
Device: iPhone 13 Pro
OS: iOS 17.5.1
App version: 0.73.0 (103)

**Comment by abhasinat** [comment]
Here's another [screen recording](https://inaturalist.slack.com/archives/C02G5AATVGA/p1722380529597969) of me trying to log out of a new account and crashing the app.

**Comment by kueda** [comment]
Closed in #2294
