### ISSUE TITLE
Signup/Login images are too small and pixelated

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1888]
Images on the signup/login screens are too pixelated right now. All images in full resolution can be found [here](https://drive.google.com/drive/folders/1GeX8T481uzLNb9tt-3ZAr3uMtjM4NZ7H?usp=drive_link).

- [ ] For the iNaturalist logo, please use this [SVG](https://drive.google.com/file/d/1GEYBmLr5P7m2_vpQcOsgrPsGFNiZNoJi/view?usp=drive_link)
- [ ] For all other photos, please use the full resolution image in the folder linked above. Imo, loading time being higher is worth the photos not being pixelated.

**Comment by angielt** [comment]
@abhas The current images we have are darkened to use for background image. Can you edit the new images for that too?
