### ISSUE TITLE
If a user denies location permissions, the default view of the explore tab should be worldwide

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1889]
**Describe the bug**
If a user denies location permissions, the default view of the explore tab should be all organisms worldwide. Right now, if I deny location permissions, the explore tab still opens "all organisms nearby" with the green "allow location access button"

**Expected behavior**
If a user has already denied location permissions, the default view of the explore tab should always be all organisms worldwide. The user should only see the locations permissions denied screen when they tap "nearby" in the explore location shooser.

**Context (please complete the following information):**
Device: iPhone 13 Pro
OS: iOS 17.5.1
App version: 0.73.0 (103)

**Comment by kueda** [comment]
@angielt can you move this to the top of your list for this iteration, please?

**Comment by kueda** [comment]
Related problem that this should address:

1. Fresh install
2. Go to Explore
3. Open the Filters
4. Tap EDIT LOCATION
5. Tap NEARBY
6. In the permission gate, tap the the button and chose "Allow once"
7. Back to Filters
8. Tap X in upper left
9. Explore is still showing the ALLOW LOCATION button even though we just allowed location access

**Comment by angielt** [comment]
> Related problem that this should address:
> 
> 1. Fresh install
> 2. Go to Explore
> 3. Open the Filters
> 4. Tap EDIT LOCATION
> 5. Tap NEARBY
> 6. In the permission gate, tap the the button and chose "Allow once"
> 7. Back to Filters
> 8. Tap X in upper left
> 9. Explore is still showing the ALLOW LOCATION button even though we just allowed location access

Was working on this and got this working but explore would freeze when following the above steps and instead denying location permissions. Will make another issue to continue this
