### ISSUE TITLE
Explore species view fixes after location granted

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1918]
There are a few strange things happening here:
1. The loading wheel in the dark gray header bar with the X-Species count starts loading even before a user grants permission, when we're not yet fetching anything
2. After a user grants location permissions, there is no loading state. Instead, the screen says "No results found"
3. Loading species takes a *long* time
4. Species API fetch includes all worldwide results, not nearby results, after a user grants location access

We should make sure that the Explore Species View shows the correct loading status and also passes the right nearby location parameters to the API. Also, we should speed up this API result if we can (maybe check to see which fields we're requesting from the API).

**Comment by abhasinat** [comment]
Discussed in review meeting: when a user lands on explore species nearby without granting location permissions, don't use the loading indicator in the dark gray bar, and have the bar be entirely blank, like this:

![image](https://github.com/user-attachments/assets/1b29201f-1ff2-4362-ae6d-60d2b889f010)
