### ISSUE TITLE
Add no results and offline states to taxon, location, projects, and user search screens

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1925]
Right now, we have no states for no results or offline in the search UI. Please add the following to all search screens. This includes taxon search, location search, user search, and projects search.

- [x] Add a [no results](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=21392-25279&t=Fpd9fOjOVmOwoZy7-11) state: when a user is online and what they have typed in the search bar produces no results
- [x] Add an [offline](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=21392-25996&t=Fpd9fOjOVmOwoZy7-11) state: when a user has typed text into the search bar and they are offline. tapping the offline state text and image should try to refetch search results.

**Comment by jtklein** [comment]
Taxon search should have an offline state now in main, not yet in a release.
