### ISSUE TITLE
Control web access in in-app browser

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1934]
Our current in-app browser is uncontrolled which will increase our age rating in the App Store if we answer Apple's questions honestly. To assuage that, we agreed to take some steps to control web access in the in-app browser and send the user to their actual web browser in other situations

Places to launch an external web browser

- [x] Help
    - [x] VIEW INATURALIST HELP
    - [x] CONTACT SUPPORT
    - [x] VIEW TEACHER'S GUIDE
    - [x] INATURALIST FORUM
- [x] Donate / SHOP INATURALIST MERCH

To control the in-app browser

- [x] Allow the in-app browser to show any URL for the following domains
    - [x] *.inaturalist.org
    - [x] *.donorbox.org
- [x] If the user tries to load any URL that does not meet those criteria, open the URL in an external web browser
- [ ] Ensure the in-app browser works for the following views
    - [x] About
        - [x] Terms of Use
        - [x] Privacy Policy
        - [x] Community Guidelines
    - [x] Settings / INATURALIST SETTINGS
    - [ ] Donate / DONATE TO INATURALIST
- [x] Audit all other uses of `FullPageWebView` and ensure the user cannot visit anywhere other than inaturalist.org and donorbox.org

**Comment by kueda** [comment]
@carrieseltzer is ok with merging without testing the Donate screen.

**Comment by carrieseltzer** [comment]
I'll test donations in the next build.

**Comment by carrieseltzer** [comment]
I tested debit card, Apple Pay, bank transfer and PayPal. The only one that didn't work was PayPal. See screen recording in slack.

**Comment by kueda** [comment]
Thanks for testing, @carrieseltzer. I carved out a separate issue for PayPal: https://github.com/inaturalist/iNaturalistReactNative/issues/1985
