### ISSUE TITLE
Crash: going to Suggestions for recently uploaded observation

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#1955]
**Describe the bug**
App crashes when going to Suggestions for a recently uploaded observation

**To Reproduce**
1. Upload an observation
2. Go offline
3. Tap observation to get to ObsDetails
4. Tap Suggest ID
5. Land on Suggestions with offline notice
6. See the following crash: “[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]”
7. App shuts down

**Expected behavior**
App should not crash

**Screenshots**
<img width="208" alt="Screenshot 2024-08-12 at 1 51 56 PM" src="https://github.com/user-attachments/assets/5bf4a366-547a-4721-b5ca-c6b41687554e">

**Context (please complete the following information):**
 - Device: iPhone
 - OS: 17
 - App version: 0.40.0+108

**Additional context**
Not sure what's causing this, but might be related to photo resizing since the photo URL changes between local files and remote files

**Comment by kueda** [comment]
This seems like a regression of #1611, so fyi, @jtklein .
