### ISSUE TITLE
Worldwide button on explore location chooser is broken right after you give permissions

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#1956]
**Describe the bug**
Right after granting location permissions on explore, for some reason, the worldwide button doesn't work. but it works when you navigate away from explore and come back

**To Reproduce**
1. On a fresh install of inat next, click the explore tab
2. Allow location access and let nearby suggestions load
3. tap "nearby" in the header to open the location chooser
4. tap the worldwide button, and notice how nothing happens (try as many times as you'd like)
5. tap to any other screen, then return to the explore tab
6. tap "nearby" in the header to open the location chooser
7. tap the worldwide button, and notice how it loads worldwide properly

**Expected behavior**
the worldwide button in the location chooser should work immediately after granting location permissions and loading nearby suggestions.

**Context (please complete the following information):**
 - iPhone 13 Pro, iOS 17.5.1, 0.40.0 (108)

**Comment by kueda** [comment]
I can't replicate this so I think it was fixed in the interim, maybe as a part of #1961
