### ISSUE TITLE
Offline suggestions should only show high-scoring taxon as Top ID

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1963]
Currently the offline model only gives us a single branch at a time, so offline Suggestions only really show you one species and its ancestors. Changing that is captured in #1856, but currently, we're always showing the tip of the branch (the finest rank taxon) as the "TOP ID SUGGESTION" even if it has a low score. This is probably going to lead to some bad IDs, so this is an interim solution:

For offline suggestions

- [ ] Talk to the computervision team and ask if the the 78 score threshold seems reasonable for the offline model results (it probably needs to be 0.78 for offline scores). If not, what's the write cutoff?
- [x] When we get a branch of results, look for lowest rank taxon with a score above the cutoff score. If it exists, show that as the TOP ID SUGGESTION and all the other taxa in the branch as OTHER SUGGESTIONS sorted by finest to coarsest rank
- [x] If there are no taxa in the branch above the cutoff score, the UI should behave the way it does when there is no TOP ID SUGGESTION, i.e. with the "We're not confident" message, and all the taxa in the branch should appear under OTHER SUGGESTIONS, sorted by finest to coarsest rank.

**Comment by kueda** [comment]
@albullington did you talk to the CV team about the right score cutoff? What did they say?

**Comment by albullington** [comment]
I started the [conversation in Slack](https://inaturalist.slack.com/archives/C4GS9KY9J/p1723666516607199) but didn't get a concrete answer. I put in a variable at the top of the file to make it easier for us to change later as needed.
