### ISSUE TITLE
App store description text

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1968]
Need text for the app store description, max 4000 characters. You can either add it directly to the App Store or include it in a comment on this issue.

**Comment by carrieseltzer** [comment]
Try the new version of iNaturalist: iNaturalist Next! We’re collecting feedback on this new app to help you more easily connect with nature and contribute to science.

Identify plants and animals and record your wild encounters with iNaturalist Next, a field guide, nature journal, and biologist-best-friend rolled into a single app.

iNaturalist helps millions of people like you learn more about the plants, animals, and fungi near them using AI suggestions backed up by a global community of knowledgeable naturalists. 

Point iNaturalist Next at plants & animals to see species suggestions while you’re outside, or import photos from your library to finally figure out what that weird bug was. When you share your photos with dates and locations, other people can confirm or refine the identification, creating valuable data for biodiversity research and conservation!

KEY FEATURES
Identify & learn about wildlife anywhere in the world
Contribute to science by sharing your observations
Engage with other people who are curious about biodiversity

And it’s more than a mobile app! Explore and connect even more at https://www.inaturalist.org.
