### ISSUE TITLE
App store screenshots

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#1969]
At least 1 (max 10) for each of the following is required

- [x] iPhone 6.5" (1242 x 2688px, 2688 x 1242px, 1284 x 2778px or 2778 x 1284px)
- [x] iPhone 5.5" (1242 x 2208px or 2208 x 1242px)

Please either add the screenshots directly to App Store Connect, or attach them to a comment on this issue.

**Comment by abhasinat** [comment]
All of the required screenshots have been uploaded.
