### ISSUE TITLE
Identify flow

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#20]
No designs for this yet, so we can loosely base this on [Identify](https://www.inaturalist.org/observations/identify) on the web. Functionality needed:

Identify:
- [x] Empty identify screen (this is the default until a user chooses a location + taxon)
- [x] Filtered identify screen - Grid View (tap into identify details, which is similar to obs details)
- [x] Filtered identify screen - Card/swipe view (swipe right to agree, swipe left to mark as reviewed)

Identify details:
- [ ] Compare tool
- [ ] Flags for DQA
- [ ] View image / zoom

A few things we'll need on all RN screens for an issue to be marked complete:

- [ ]  API v2
- [ ]  React Hooks
- [ ]  Accessibility
- [ ]  RTL support
- [ ]  Unit/integration test coverage via react-native-testing-library

**Comment by albullington** [comment]
There's a bug with `place_id` in observation/search that will need to be fixed before a user can search by location. [#289](https://github.com/inaturalist/iNaturalistAPI/issues/289)

**Comment by kueda** [comment]
Going to close this for now until we're ready to work on it.
