### ISSUE TITLE
Explore worldwide species load as quickly as the web

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#2024]
**Describe the bug**
Worldwide species in Explore is slow, even though it's showing exactly the same data you see at https://www.inaturalist.org/observations, which is very fast, so we're probably appending some unnecessary extra params that are busting the cache. I'm seeing the following that look unnecessary b/c they're defaults:

- `order_by=created_at`
- `order=desc`
- `quality_grade=research,needs_id`

And the following that we could probably change to mimic the web

- `per_page=20`

If removing / changing these doesn't get you a fast response, consult with the web team to choose the params that will utilize the cache.

**Comment by jtklein** [comment]
From this [conversation](https://inaturalist.slack.com/archives/C04MF2V4ZAN/p1726168845440439) it became apparent that server-side caching is currently not possible for API v2 requests that use the `fields` parameter which this request does.

We might switch to API v1 for this particular request, as it is the front-page for Explore for many users.
