### ISSUE TITLE
In the feedback form, when there is no text, a user should not be able to click submit

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#2025]
By default, the submit button on the feedback form is disabled when a user has not started typing. Right now, a user can start typing, then backspace and delete everything they typed, and the submit button is still enabled, so they can then submit an empty feedback form.

- [ ] Please make it such that the submit button is disabled on the feedback form if the form is blank, even if a user types and then backspaces to make it empty.

**Comment by israr002** [comment]
@angielt just checking , have you started working on this issue? If not, I can take it over and work on it ??

**Comment by angielt** [comment]
> [@angielt](https://github.com/angielt) just checking ,have you started working on this issue? If not, I can take it over and work on it ??

It's already done but there are plenty more issues you can take a look at!
