### ISSUE TITLE
Active bottom tab doesn't change when swiping back from Notifications

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#2034]
**Describe the bug**
The active bottom tab doesn't change when go back via swipe.

**To Reproduce**
1. Open the app to land on MyObs. Note that that tab in the bottom tabs has a green outline to indicate it's the current tab
2. Go to Notifications. The notifications icon is now green to indicate you're on that tab
3. Swipe from the left side of the screen to go back
4. You're back on MyObs, but the Notifications icon is still green

**Expected behavior**
When you swipe back to MyObs, the notification icon should go back to being dark gray and the MyObs icon should have the green outline.

**Screenshots**
![IMG_1956](https://github.com/user-attachments/assets/2c27c94d-d05a-4496-8839-dcd7f9ec95eb)

**Context (please complete the following information):**
 - Device: iPhone SE (3rd gen)
 - OS: iOS 17.6.1
 - App version: 0.44.0

**Comment by israr002** [comment]
@kueda @jtklein I am working on this
Please assign this to me
