### ISSUE TITLE
Make help text in advanced add obs modal closable

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#2039]
The help text for the add obs modal is distracting and leads to incorrectly tapping the help text instead of the buttons it describes. Abhas would like to make it closable.

- [ ] Add an "x" button ([design](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=15467-58188&t=0YcW6ef1rVW2z8WI-4)) to the upper right that makes the help text disappear forever ![image](https://github.com/user-attachments/assets/9092426e-64fd-48ca-a561-09707f3e2aaf)

The only non-trivial part here is figuring out where to store this preference. Maybe in the user's table? Or in mmkv.

**Comment by kueda** [comment]
@abhasinat the way @albullington implemented this, the "x" button just closes the modal. I thought we wanted it to dismiss the help text forever, i.e. after you tap that x all you see are the green buttons and you never see the white area again. How did you want this to work?

**Comment by abhasinat** [comment]
yes - i think the x button should dismiss the modal till fresh install
