### ISSUE TITLE
Typos on Obs Detail

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#2075]
Several typos on Obs Detail, go to Details tab and scroll down to Data Quality. 

- [ ] "Needs Id" -> Needs ID
- [ ] "resarch" grade -> Research
- [ ] Data quality "Assessement" -> Assessment

**Comment by jtklein** [comment]
I can only find the "Needs Id" one, can you share a screenshot @abhasinat?

**Comment by abhasinat** [comment]
![IMG_0195](https://github.com/user-attachments/assets/98bbb97d-ed24-4b07-974f-8fb1061b35b4)
