### ISSUE TITLE
Pull to refresh notification

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#2080]
When you pull down on notifications

- [ ] Reveal a row at the top that has an activity indicator and the text "Loading..."
- [ ] When the user releases, the loading row should stay in place until notifications have loaded
- [ ] When the user releases, check for new notifications
- [ ] When we get a response, update the view and get rid of the loading row

**Comment by abhasinat** [comment]
https://github.com/inaturalist/iNaturalistReactNative/issues/2332
