### ISSUE TITLE
Bug with uploading # after starting new observation

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#2083]
**Describe the bug**
Uploading status in toolbar isn't always correct

**To Reproduce**
1. Create 2 observations, save each and start both uploads on MyObs
2. Wait for upload success (checkmark) to show, but don't wait long enough for it to go away
3. Create a new observation and save
4. Start upload from MyObs
5. See the wrong number of uploads (3/3 uploads, rather than uploading 1 observation)

**Expected behavior**
Number of uploads displayed in the toolbar should always reflect the correct number of uploads, instead of including previous uploads in the total count.

**Comment by kueda** [comment]
Probably a related set of repro steps:

1. Make an obs w/o evidence and tap UPLOAD NOW
2. Before that obs finishes uploading, make another obs w/o evidence and tap UPLOAD NOW
3. Even though the first obs finished uploading, the toolbar status says "Uploading 2 of 2 observations"
