### ISSUE TITLE
look at a failing jest test

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#2094]
https://github.com/inaturalist/iNaturalistReactNative/tree/failing-jest-test demonstrates a consistently failing test that we should figure out

**Comment by kueda** [comment]
@albullington, https://github.com/inaturalist/iNaturalistReactNative/commit/5635936d384b603b6c03da299e758b71d0bb1474 addresses the test failure in that branch. FWIW, the main problem seemed to be the use of `useCallback`. I *think* the problem was that `useCallback` was storing a stable function that returned a new component every time it was called, so the `SuggestionsFooter` was constantly getting recreated. `useMemo` memoizes the return value itself, i.e. the component (which, confusingly, is itself a function, of course, thank you React).

A slightly less significant problem in that branch was the use of `queryBy` instead of `findBy`. `findBy` is going to be a little bit safer in complicated situations like integration tests where we're not 100% sure the things we're looking for exists at the moment we look for it.

Does this address the issue? Would you like me to merge that branch?

**Comment by albullington** [comment]
Ah, interesting find and good learnings here about `useCallback` and `findBy`. Yeah, that addresses the issue -- I can see `PhotoDeletion` tests passing instead of the unmounted node error -- and would be great to merge.
