### ISSUE TITLE
PhotoCount text overflows icon

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#2131]
Happening when system font is set to the largest size, probably everywhere PhotoCount gets used but particularly on obs grid items and ObsDetails. If possible we should try and scale up the icon along with the text size, but failing that we should probably just not allow that text to scale up.

![IMG_675790649A5A-1](https://github.com/user-attachments/assets/e63aeb27-e352-4f76-8e71-12bd49545c9e) ![IMG_F6F3347FD7BD-1](https://github.com/user-attachments/assets/b0b4eeeb-cb5a-43e5-919e-7fad21ae52bd)

**Comment by israr002** [comment]
@kueda Please assign this to me

**Comment by israr002** [comment]
@kueda If we scale the icon, it might overlap with some cards in the obs grid view. I think it would be better to prevent the text from scaling. What are your thoughts on this ?
<img width="323" alt="image" src="https://github.com/user-attachments/assets/90c14d1c-6bd3-4ba7-a6b1-b3dff7938429">

**Comment by kueda** [comment]
Hm, that actually looks pretty good, and it's even more important on ObsDetails. I would probably cut off or hide the quality grade indicator in cases of potential overlap, but this is more of a design decision, so what do you think, @abhasinat? We could also just merge the change to the photo count and deal with the overlap in a separate issue
