### ISSUE TITLE
Submitting a comment does not update ObsDetail

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#214]
**Describe the bug**
When you submit a comment, it appears that nothing happens.

**To Reproduce**
1. Go to ObsDetail
2. Author a comment
3. Hit the Send button
4. Nothing happens. If you check the website it seems like the comment was submitted, but the UI does not change

**Expected behavior**
When I submit a comment, I expect it to appear as an activity item. Knowing how it works, I also expect some kind of loading indicator while it's being submitted. Ideally there would be some skeleton UI for the newly added comment *and* a loading indicator like we do on the web.

**Screenshots**

**Context (please complete the following information):**
 - App version: [e.g. 1.0.0]

**Additional context**

**Comment by albullington** [comment]
Closed via PR #247
