### ISSUE TITLE
Add a progress bar & background upload inside of the multiple observations upload screen

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#2151]
Right now, when you are using the multiple observations uploader, the upload only begins once you finish processing all your observations. Some users want the uploads to begin in the background immediately when they tap "upload now" - this is a better UX and also does what the button says it does.

This new UI, combined with the "# observations" at the top of the screen and "# of #" should cohesively help a user understand the upload state of all their observations.

Add the following to the multiple observations upload screen. Here are the [designs](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=21909-33846&node-type=section&t=8VoBjZoPfTOeXnqn-11).
- [x] when there are observations that have been saved or uploaded, display a progress state bar that is sticky to the bottom bar that can be populated with # uploading, # upload failed, # saved, and # uploaded. This bar should sit on top of everything else on this screen (basically attached to the bottom sticky buttons), so all other UI should scroll behind it.
- [ ] When an observation is uploading, display a progress bar that functions the same way as the progress bar on the home screen when observations are uploading (with the same amount of time before it disappears)
- [ ] If we get background upload working inside of this flow, please make sure to make an issue to make sure background upload also works from MyObs, which it currently does not. #1633

![image](https://github.com/user-attachments/assets/b8e4f780-ddf3-417f-b600-4ab9c114ca6b)

**Comment by carrieseltzer** [comment]
Thanks Abhas. I'm not sure this addresses the lack of visual transition after saving or uploading an observation and landing on the next observation.

**Comment by abhasinat** [comment]
Got it, I don't think I understood your original request till now. I agree that is confusing. Here's another issue covering what you mentioned:
https://github.com/inaturalist/iNaturalistReactNative/issues/2325

**Comment by abhasinat** [comment]
Based on our discussion in the mobile meeting, this may require more exploration to see what we can do to get background upload working while you are in the app.
