### ISSUE TITLE
Change color of explore view switcher UI

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#2154]
Explore switcher UI is too difficult to see right now, so we want to change the colors of it to make it more visible on the darker cards.

- [x] Change the [explore view button](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=6409-22627&node-type=frame&t=8VoBjZoPfTOeXnqn-11) to have a white background, green icon, and a light gray inside border

![image](https://github.com/user-attachments/assets/d88af0fd-7de9-4dc9-ad3f-6e2165a56ec8)

**Comment by israr002** [comment]
@kueda Hi , Would it be possible to provide the design access for this enhancement? I can work on this ticket, and having the designs would help to implement it

**Comment by kueda** [comment]
@israr002, I'll see if we can figure out a better way to do this, but here's a screenshot from Figma showing what the button should look like with some useful values:

<img width="480" alt="Screenshot 2024-10-28 at 10 45 21 AM" src="https://github.com/user-attachments/assets/6b3012ac-926a-49ee-bfc4-48e7d4f7b61d">
