### ISSUE TITLE
TaxonDetails needs a gradient behind the taxon name title on iPad

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#2171]
Per the [design](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=2255-16900&t=jqDLiF8DU8LV9HxE-4), there should be a gradient covering the photo area but behind the other from 50% opacity black at the bottom to full transparent at the top.

<img width="502" alt="Screenshot 2024-09-24 at 3 09 44 PM" src="https://github.com/user-attachments/assets/1b038d4b-bb33-41ba-b2fd-6711ab190936">

**Comment by angielt** [comment]
I see a gradient currently in the app. Are you seeing something different? @kueda

**Comment by kueda** [comment]
I'm seeing it on my SE, but

1. This is a part of the iPad support issue, so make sure it's working on iPad
2. Check out recent changes to that part of the code. Maybe it got fixed between now and when this issue was created

**Comment by angielt** [comment]
I cannot replicate this

**Comment by kueda** [comment]
@angielt I can replicate on iPad, which I think was the original intent of this issue, so I updated the title. You can see the current iPad portrait design at https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=2320-16505&t=4lTUnFo3BkyrfsvZ-4
