### ISSUE TITLE
TaxonDetails sticky header

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#2174]
[Designs](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=2188-17874&t=B2j1LVdj0uPjDKNz-4) specify

- [ ] Nav header (w/ back button and kebab) should stick on scroll
- [ ] Component w/ rank, names, and Explore button should stick to the top when it scrolls to that position
- [ ] Before rank/name/Explore component gets to the top, it should start animating
  - [ ] Background to white
  - [ ] Text color to black
  - [ ] Drop shadow appears
- [ ] When rank/name/Explore component is animating, nav header should also be animating
  - [ ] Background to white
  - [ ] Text color to black

**Comment by abhasinat** [comment]
Related details in this issue:
https://github.com/inaturalist/iNaturalistReactNative/issues/2331

**Comment by kueda** [comment]
Superseded by [#2331](https://github.com/inaturalist/iNaturalistReactNative/issues/2331)
