### ISSUE TITLE
Multiple taps on an observation can open multiple instances of obs detail

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#2204]
**Describe the bug**
Right now, if you tap an observation from my obs or explore quickly multiple times, it can open multiple instances of that same obs detail screen on top of each other, and then you have to click back multiple times through the same screen to get back to the previous screen.

**To Reproduce**
1. Go to Home screen/My obs in list view
2. Quickly tap on a single observation several times super fast
3. Notice how it opens multiple instances of the obs detail page for that obs on top of each other
4. Click back and see the same obs detail that you need to back out of multiple times

Note: this happens on explore as well.
May take a couple tries (you have to click it really fast)

**Expected behavior**
We should disable multiple navigation taps on an observation on explore or my observations once one is in progress. No UI changes needed.

**Context (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: 18.0
 - App version: 0.49.0 (118)

**Comment by israr002** [comment]
@jtklein sorry i missed to message on this ticket to assign me.
I saw that you assigned it, but I had already started working on it and have raised a pull request.
