### ISSUE TITLE
Nearby button in Explore Filters doesn't work first time permissions are given

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#2207]
**Describe the bug**
Nearby button in Explore Filters > Explore Location Search doesn't work the first time permissions are given

**To Reproduce**
1. Go to Explore, then Explore Filters
2. Make sure your location settings are set to Ask Next Time Or When I Share
3. Tap on Edit Location, then Nearby
4. You'll be prompted for location. Say yes, give access once or always
5. Nothing happens, and you land back on the Explore Filters screen with the "Apply Filters" button disabled. At this point, you need to either exit out of the screen or change another filter to be able to tap "Apple Filters"
6. Nearby does seem to applied if you change another filter and go back to Explore

**Expected behavior**
The first time Nearby is applied in Explore Filters after permissions are given, we should enable the "Apply Filters" button to allow a user to apply this change and return to Explore.

**Screenshots**
![Screenshot 2024-09-30 at 2 39 04 PM](https://github.com/user-attachments/assets/e8a0e41e-f3ff-4bd4-9f60-0badf88092bf)

**Context (please complete the following information):**
 - Device: iPhone
 - App version: 0.45.0

**Comment by israr002** [comment]
@kueda Please assign this to me

**Comment by albullington** [comment]
@israr002 i assigned to you
