### ISSUE TITLE
PhotoGallery photos have no selected state in Android

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#221]
**Describe the bug**
Photos in the PhotoGallery do not have a selected state when you tap them.

**To Reproduce**
1. Start a new observation by opening the gallery
2. Tap on a photo
3. The photo you tapped should have a green checkmark in the upper right, but it doesn't

**Expected behavior**
When you tap a photo in the gallery to select it, it should have a green checkmark in the upper right of the photo to indicate that it was selected like it does in iOS.

**Context (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 12
 - App version: Build 28

**Comment by albullington** [comment]
This should be fixed by the [add evidence PR](https://github.com/inaturalist/iNaturalistReactNative/pull/220).
