### ISSUE TITLE
Globalize text in Info.plist

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#2218]
Text in Info.plist (e.g. permission explanations) are not currently globalized, but they should be

- [ ] Audit Info.plist and list out all localizable text
- [ ] Figure out how to globalize these values
- [ ] Do it!

Here's an example:

<img width="362" alt="Screenshot 2024-10-02 at 2 58 16 PM" src="https://github.com/user-attachments/assets/58cf7c5c-3db7-435c-9cfd-61a613fa2c4f">

**Comment by kueda** [comment]
@jtklein have you already started working on this and if not do you mind if I take it? I'm realizing it's a prerequisite for #2099

**Comment by jtklein** [comment]
I have not started yet, but I did the same thing for Seek two years ago, so let me know if you need any pointers or PR reviews.

The PR that introduced it in Seek is this https://github.com/inaturalist/SeekReactNative/pull/530/files but I did the actual work in XCode manually, so the code changes don't tell much. Another commit added i18n for the home screen shortcut item here: https://github.com/inaturalist/SeekReactNative/pull/537/commits/bfbfe641881865643c810c7b8516a16b26ced721

Usually crowdIn requires some deviations from their locale abbreviations for some languages, but I just checked and the `%osx_code%` that we are using for the info.plist translations does not have any Manual Mappings in the Seek project settings screen, so maybe none required for this part.
