### ISSUE TITLE
PhotoGallery lets you select the same photo again

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#222]
**Describe the bug**
The PhotoGallery lets you select the same photo multiple times and import a bunch of duplicate photos.

**To Reproduce**
1. Start a new observation from the gallery
2. Tap on a photo. The button should change to "Import 1 photo"
3. Tap on the same photo again. The button says "Import 2 photos"
4. Tap "Import 2 photos"
5. On GroupPhotos, the same photo appears twice

**Expected behavior**
Tapping a photo should select it, and tapping it again should unselect. You should not be able to select the same photo multiple times.

**Context (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 12
 - App version: Build 28

**Additional context**
While there is some use to making multiple observations from the same photo, we should do that elsewhere (like GroupPhotos).

**Comment by albullington** [comment]
Fwiw, I'm not seeing this issue in the [add evidence PR](https://github.com/inaturalist/iNaturalistReactNative/pull/220).

**Comment by kueda** [comment]
Yeah, I think this was closed in b70057332774bb1c658af96d93f2fe05a74786ab
