### ISSUE TITLE
Deleting three observations in rapid sequence crashes the app

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#2230]
**Describe the bug**
If you delete three observations with photos without letting the toolbar settle, the app crashes with a Realm error.

**To Reproduce**
1. Sign into an account with at least 3 observations with photos (or make and upload them)
2. Delete each observation without waiting for the toolbar status to reset
3. The app crashes with the error: "Accessing object which has been invalidated or deleted"

**Expected behavior**
Deleting observations should not crash the app.

**Screenshots**
![IMG_2226](https://github.com/user-attachments/assets/e0a29c24-4545-4a00-a215-5e3e8e684b73)

**Context (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 17.6.1
 - App version: 0.50.0 (119)

**Comment by kueda** [comment]
Abhas and I both failed to replicate this today. If you can't either, please just close as not planned.

**Comment by albullington** [comment]
Also could not replicate.
