### ISSUE TITLE
Localize app store description and release notes

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#2248]
Both of these things should be localized, and in theory we can use Crowdin to perform the translation and Fastlane to post those translations to the app stores. In practice... who knows. FWIW, we already commit all release notes to the repo as en-US sources: https://github.com/inaturalist/iNaturalistReactNative/tree/main/fastlane/metadata/android/en-US

- [ ] Make release notes available for translators on Crowdin (probably as new files, but maybe as one single new file that always gets updated)
- [x] Make app store description available for translators on Crowdin (as a new file)
- [x] Incorporate Crowdin translations into repo during the pull action
- [x] Figure out how to post both the release notes and app store descriptios to the app stores in the Fastlane `prod` lane (or maybe in a new lane; to date, the prod lane has not been very useful for updating the iOS App Store b/c you can't specify the build you want to release).

**Comment by jtklein** [comment]
In the Mobile circle meeting we decided to not include changelogs in this issue and only make sure store descriptions are translated and synced with the stores.
