### ISSUE TITLE
Audio recordings disappear when saved, not uploaded

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#2250]
**Describe the bug**
Audio recordings sometimes disappear when saved and not uploaded for a few hours or a few days. The audio recordings don't play sound and say 0:00/0:000 for audio length.

**To Reproduce**
1. Record audio
2. Save observation
3. Ignore the app for a few days or hours. Maybe close the app?
4. Try to upload a sound. Upload will not complete, and audio will not play back

**Expected behavior**
Saved audio recordings should be preserved in the app until they are uploaded.

**Screenshots**
See [forum](https://forum.inaturalist.org/t/audio-files-display-0-00-0-00-and-play-no-sound-on-saved-observations/57090)

**Context (please complete the following information):**
 - iOS
 - App version: 0.49.0 (118)

**Additional context**
It's possible we're clearing the soundUploads cache of sounds that haven't yet been uploaded, so that might be a place to start looking for the bug. Not sure if closing/backgrounding the app is part of the problem.

**Comment by kueda** [comment]
FYI, #2263 is probably related.

**Comment by kueda** [comment]
@angielt, can you please list out the consistent repro steps you found?

**Comment by angielt** [comment]
I mainly followed the repro conditions listed in the issue and made sure the audio could be played back no matter how long its been. Although you could probably change the frequency of when clearCaches is called to test it.
