### ISSUE TITLE
Flagged comment still appears flagged after being resolved

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#2262]
**Describe the bug**
Flagged comments still appear flagged after being resolved.

**To Reproduce**
1. View https://www.inaturalist.org/observations/245155834 in the app
2. The comment by alr1243 shows an orange flag and the label "Flagged"
3. View https://www.inaturalist.org/observations/245155834 on the web to confirm there are no open flags

**Expected behavior**
If a comment (or ID) has flags but they are all resolved, it should not appear flagged.

**Screenshots**
![IMG_2231](https://github.com/user-attachments/assets/3ac32b92-26fb-4483-91ed-8e25ba6d92c7)

**Context (please complete the following information):**
 - Device: iPhone SE (3rd gen)
 - OS: 17.6.1
 - App version: 0.50.0

**Additional context**
The flagged state should only appear if there are any unresolved flags on the comment or ID.

**Comment by israr002** [comment]
@kueda Please assign this to me
