### ISSUE TITLE
Hold onto local copies of media longer

### ISSUE THREAD

**Issue by angielt** [inaturalist/iNaturalistReactNative#2263]
Consider holding onto local copies of obs photos and maybe sounds for longer. When you try to look back at the photos the day after with little or no internet it kinda sucks to not be able to see the photos. 

OS: iOS, Android

**Comment by kueda** [comment]
FWIW, I think we should hold on to them for a month, maybe with an exception if the app is using more than 5 GB of disk or something.

**Comment by kueda** [comment]
FWIW, I'm pretty sure the date-based retention part is a one-liner: https://github.com/inaturalist/iNaturalistReactNative/blob/main/src/sharedHelpers/removeSyncedFilesFromDirectory.ts#L4. Disk usage threshold may be a bit harder.
