### ISSUE TITLE
Unable to clear note once written

### ISSUE THREAD

**Issue by angielt** [inaturalist/iNaturalistReactNative#2273]
**Describe the bug**
When you type a note and press 'Done' and go back to clear it, the 'Done' button is grayed out and you can't clear the note. 

**To Reproduce**
1. Make an observation
2. Save a note
3. Try and clear the note

**Expected behavior**
The 'Done' button shouldn't be grayed out if there are changes to the text and it is possible to make changes.

**Comment by wadekar9** [comment]
can i work on this issue ?

**Comment by israr002** [comment]
@kueda Please assign this ticket to me

**Comment by kueda** [comment]
@wadekar9 sorry I missed your comment, I just assigned this to you. @israr002, if Nayan doesn't make any progress on this in a week, I'll assign this to you.

**Comment by kueda** [comment]
Well, it's been a week, so I'm assigning this to @israr002.
