### ISSUE TITLE
Weighted geographic center on taxon range maps

### ISSUE THREAD

**Issue by angielt** [inaturalist/iNaturalistReactNative#2274]
Suggested by Carrie. Currently, a single id on the other side of the world can skew the center of the taxon range which makes it hard to see the points on the map in NA or Asia without expanding the map. 

Water Tupelo is a current example of this (E NA range with one point in India).

**Comment by kueda** [comment]
This might be out of scope for this app. We just use a bounding box on observations we get back from the API for an observation search, and there's no info about a center of obs density. IMO, this is actually a feature b/c it helps me find observations that are misidentified or have bad coordinates and fix them. Thoughts, @abhasinat?

**Comment by abhasinat** [comment]
I agree, this is something to be solved by the work on the anomaly detector, not by iNat Next imo
