### ISSUE TITLE
Active tab green icon color on tab bar disappears after the menu is pressed

### ISSUE THREAD

**Issue by angielt** [inaturalist/iNaturalistReactNative#2289]
**Describe the bug**
The green color on the active tab disappears back to dark gray after the menu button is pressed.

**To Reproduce**
1. Tap on the tab so it is active and green. 
2. Tap on the menu button
3. Close the menu

**Expected behavior**
Active tab color should remain after the menu is closed.

**Context (please complete the following information):**
 - Device: [e.g. iPhone]
 - OS: [e.g. iOS 17.6.1]
 - App version: [e.g. 0.51.0]

**Comment by israr002** [comment]
@angielt i have fixed this in PR : #2286

**Comment by angielt** [comment]
Duplicate of #2034
