### ISSUE TITLE
Changes to observations that are in queue to be uploaded

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#2317]
Right now, there are a few bugs & changes we want to make to observations that are being uploaded

When an observation is being queued to be uploaded (whether by clicking the sync button in the toolbar OR the upload button next to a saved observation):
- [x] make the dots around the arrow dance (rotate clockwise): the dots should rotate at a constant rate of 360 degrees every 10 seconds, and the arrow should stay stationary. and make the opacity of this entire icon 50% only while the dots are dancing. This is difficult to make a prototype of, so please let me know if you need clarity on this.
- [x] make the entire row of that observation untappable (right now, an observation in queue to be uploaded is tappable)

The only way to cancel uploads should be from clicking the X button in the toolbar. When an observation shifts from queuing to upload to uploading, the dots should disappear and the progress ring should appear around it, just as it currently does.

**Comment by albullington** [comment]
@abhasinat for the second part of this, do you want to give users any visual indication that taps on the list or grid item are disabled?

**Comment by abhasinat** [comment]
I think the icon with dancing dots being at 50% opacity in addition to the observation photo being at 50% opacity (which it already is) should do the trick.
