### ISSUE TITLE
Nearby button does nothing if user denied location permissions

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#2318]
**Describe the bug**
When a user who has denied location permissions goes to Explore, they tap nearby and nothing happens. 

**To Reproduce**
1. Change location settings to "never" for iNat Next in phone settings
2. Tap on Explore
3. Tap "Worldwide"
4. Tap "Nearby"
5. See that nothing happens

or alternatively

2. Tap on Explore
3. Tap on Explore Filters
4. Tap Edit Location
5. Tap Nearby
6. See that nothing happens

**Expected behavior**
We should show the user the location permission gate if they tap on Nearby from either search location screen in Explore/Explore Filters and they have denied location permissions. A user should get feedback on what's happening when tapping on Nearby, even if they have denied permissions.

**Context (please complete the following information):**
 - Device: iPhone
 - App version: 0.52.0

**Comment by kueda** [comment]
Not sure if you've started working on this yet, @jtklein but FYI #2418 might close this
