### ISSUE TITLE
Camera functionality is laggier than native camera

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#2320]
Some users have been reporting in the forum that the camera is laggy. I'm noticing some lagginess when taking an AI camera photo -- it's definitely not an immediate response when tapping the capture photo button. This is more of an exploratory issue than anything, but it would be great to see if we can speed up the responsiveness of the camera -- loading the camera, taking a photo, and tapping any of the buttons in the camera. 

One place I'd start investigating is all the `useEffects` that we have throughout the camera code. It's possible that we're creating a lot more rerenders than we actually need. We have a lot of addListeners in different parts of the camera code, for example, and maybe that can be consolidated.

It would be a nice-to-have if we could do some time tracking and prove that we can make the camera functionality faster, but not strictly necessary.

**Comment by kvangork** [comment]
It might be helpful to add more detailed debug logging, including timing information, around the camera experience.

Anecdotal and unreplicated, but today I had an experience where the AI camera made a prediction at some middle level (I had a sketch of a mushroom on my kitchen counter) and then I turned it around to point at a pineapple. The UI became unresponsive. Both the camera preview and the "age of result" counter continued to work smoothly, but none of the on-screen buttons responded to taps. I force quit the app, but there isn't anything relevant in the debug logs.
