### ISSUE TITLE
Bugs related to if I have denied location permissions

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#2321]
**Describe the bug**
If I have denied location permissions in the app, there are a few bugs happening right now.

**To Reproduce**
1. Deny location access
2. Go to Projects
3. Go to the nearby tab
4. Tap "Allow location access"
5. nothing happens

1. Deny location access
2. Go to Explore
3. Go to the location picker
4. Tap "Nearby"
5. nothing happens

**Expected behavior**
- [x] In Projects -> Nearby Projects -> "allow location access" should work
- [x] #2318
- [x] https://github.com/inaturalist/iNaturalistReactNative/issues/2319

**Context (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: 18.0.1
 - App version: 0.52.0 (121)

**Comment by kueda** [comment]
The parts that were unique to this issue where addressed in #2418
