### ISSUE TITLE
Swipe down to close media viewer

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#2322]
Some users in feedback (and @tiwane and @kueda) would like to be able to swipe to close the media viewer.

- [x] When a user does a swipe down motion on the photo in the media viewer, it should close the media viewer and return a user to the previous screen.

**Comment by kueda** [comment]
Sorry again, @israr002, I missed your comment here too. Will try to do better in the future.

**Comment by israr002** [comment]
No problem @kueda
