### ISSUE TITLE
Allow users to move from explore species to observations view

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#2323]
On Explore/Species View, the species cards tell you how many observations of each species there are but you can't currently get from species view to observations view since we took away the functionality to tap the "X observations" text (which was not very accessible).

Here's the [design](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=7063-33876&node-type=frame&t=wCgV1eq0l5xi9RwS-11).

- [ ] Add an observation icon to the top right of all species cards with a drop shadow.
- [ ] This icon should have a tappable area of 39x39px in the top right corner of each species card
- [ ] Tapping this icon should take a user to the observations view of the species card they tapped on, with all other explore filters retained.

![image](https://github.com/user-attachments/assets/fed30b74-7b6b-46cc-8516-87003a8f5cd0)

**Comment by israr002** [comment]
@kueda  Could you please assign this task to me? Additionally, could you provide a screenshot of the specific drop shadow values in Figma?

**Comment by abhasinat** [comment]
Yep, here you go: 
<img width="242" alt="image" src="https://github.com/user-attachments/assets/ba84614e-29ba-4c7a-baa9-79b3a9067c81">
