### ISSUE TITLE
Explore map zoom and display not immediately showing nearby circle when switching views

### ISSUE THREAD

**Issue by angielt** [inaturalist/iNaturalistReactNative#2343]
**Describe the bug**
When switching to obs view in explore, the map zooms in without fetching updated map tiles and shows orange blur on the screen until you pan the map. After the map is panned it immediately zooms out to show nearby circle.

**To Reproduce**
1. Make sure location is granted, and location is nearby
2. Go to Explore
3. Switch to Observation view
4. See orange zoomed in map
5. Pan map
6. See map zoom out to show nearby circle

**Expected behavior**
When switching to obs view, the map show smoothly load and show the results. 

**Screenshots**
[link to slack](https://inaturalist.slack.com/archives/C02G5AATVGA/p1730494630580169)

**Context (please complete the following information):**
 - Device: [e.g. iPhoneSE]
 - OS: [e.g. iOS17.6.1]
 - App version: [e.g. 0.52.0]

**Comment by kueda** [comment]
Even though I know I was the one who reported this, I can't replicate this in main, nor can I replicate it when I roll back to 0.52.0 and install it on my iPhone SE. Were you able to replicate it when you filed this, @angielt?

**Comment by angielt** [comment]
I do remember I was able to replicate when I made the issue

**Comment by kueda** [comment]
Somehow I was able to replicate in 0.52.0 after a few tries, but not in main, so I think this was got fixed elsewhere.
