### ISSUE TITLE
Add an expand map button beneath obs detail map

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#2346]
Some users have reported a similar UX issue to #2029 for Obs Detail. For increased accessibility, this map should also have an "expand map" button beneath it similar to taxon detail. tapping this button should expand the map.

<img width="747" alt="image" src="https://github.com/user-attachments/assets/8b2991e7-3be1-4357-843a-b01e6ed09cea">

**Comment by israr002** [comment]
@kueda Please assign this to me
