### ISSUE TITLE
Offline taxon search

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#2348]
Not being able to search for and choose a taxon for an observation while offline is annoying for, well, maybe everyone, but particularly [power users](https://forum.inaturalist.org/t/inaturalist-next-what-are-your-thoughts-after-trying-it-for-a-while/57526). It's particularly annoying when you know the app has some local taxa that we could be searching.

On TaxonSearch,

- [x] If offline, don't hit the API and instead search Realm Taxon records; try to match the text against the `name` and `preferredCommonName` attributes; try [setting](https://www.mongodb.com/docs/atlas/device-sdks/sdk/react-native/model-data/define-a-realm-object-model/#std-label-react-native-set-fts-index) and [using](https://www.mongodb.com/docs/atlas/device-sdks/sdk/react-native/crud/query-data/#filter-with-full-text-search) a Realm full-text search index; but if that's taking more than half a day, the [`CONTAINS` operator](https://www.mongodb.com/docs/atlas/device-sdks/realm-query-language/#std-label-rql-string-operators) should be fine
- [x] NEEDS DESIGN: if offline, show a notice about being offline, something like "Showing offline results. To search for more species, try again when connected to the Internet."

Related to #1958

**Comment by abhasinat** [comment]
Here's a [design](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=22146-44802&node-type=frame&t=wppYDUbcCgGuRi0G-11) for a new variant of the Fixed Search Header component.

- [ ] This version of the search header component should appear when there is no internet.

<img width="686" alt="image" src="https://github.com/user-attachments/assets/4f4ca805-e408-42ab-ada8-27d3f2328105">
