### ISSUE TITLE
Error when formatting dates on observation overview page

### ISSUE THREAD

**Issue by tobias47n9e** [inaturalist/iNaturalistReactNative#2387]
**Describe the bug**
After logging in the observation overview page shows this error message on Android:

> Use `dd` instead of `DD` (in `DD. MM.YY,  HH:mm`) for formatting days of the month to the input `Sat Oct 19 2024 15:55:09 GMT+0200`; see: https://github.com/date-fns/date-fns/blob/master/docs/unicodeTokens.md

My i18next object shows this:

```ts
{"language": "de", "languages": ["de", "en"]  ... }
```

And `i18n.t("datetime-format-short")` shows: `DD. MM.YY,  HH:mm`, while `i18n.t("date-format-short")` shows: `dd. MM. yy`.

**To Reproduce**
1. Log in on Android emulator
2. See error

**Expected behavior**
Observations should show.

**Screenshots**
<img src="https://github.com/user-attachments/assets/ba3d0d9d-d03b-4143-90a5-1619704fef2c" height="400"/>

**Context (please complete the following information):**
 - Device: Android emulator
 - OS: Android
 - App version: current main branch

**Comment by tobias47n9e** [comment]
I would like to work on this issue

**Comment by kueda** [comment]
Please use Crowdin to add translations. Source text flows from github to crowdin, and translations flow back from crowdin to github, not the other way around. To suggest new translations in Crowdin, get a Crowdin account and find the strings you want to change at https://crowdin.com/editor/inaturalistios/724/en-de

**Comment by tobias47n9e** [comment]
Oh right. Sounds good. Too bad that the translators can crash the app when they are not careful about the correct syntax of the date and datetime formats.

**Comment by kueda** [comment]
Translators don't crash the app. Developers crash the app when we fail to
have the right safeguards in place. In this project we prevent integration
if the ftl is invalid. We should probably do more date format validation if
you want me to write up an issue for you to work on.
