### ISSUE TITLE
Add date format validation to FTL validation

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#2394]
We already [validate the format of FTL](https://github.com/inaturalist/iNaturalistReactNative/blob/main/src/i18n/i18ncli.js#L181-L223) translation files we get from Crowdin, but we don't validate the content, mostly because Fluent is pretty permissive, BUT we should validate date formats, as pointed out in #2387 and as made painfully obvious by some recent Android releases.

- [ ] for every string beginning with `date-format-`, [format](https://date-fns.org/v4.1.0/docs/format) it with date-fns, catch any formatting errors, and add them to the list of errors to report
- [ ] ensure that when these problems are present in the relevant source strings, `npm translate` fails with an error code

In theory that will be enough to cause our translation integration pipeline to fail when these formatting problems occur.

**Comment by kueda** [comment]
@tobias47n9e would you like me to assign you to this one?

**Comment by tobias47n9e** [comment]
@kueda Yes :smile:
