### ISSUE TITLE
OfflineNotices appears side-by-side on ObsDetails from Notifications while offline

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#2412]
**Describe the bug**
If you view an obs w/ multiple photos from Notifications while offline, you see side-by-side OfflineNotices

**To Reproduce**
1. Fresh install
1. Sign into an account with a notification about an observation with multiple photos; DON'T view the observation, or the photo will be cached
1. Go to Notifications while online, and make sure you can see that notification
1. Go into airplane mode
1. Tap the notification
1. You see side-by-side OfflineNotices; they are too tall; you also can't scroll

**Expected behavior**
* You should just see one OfflineNotice per photo,
* The OfflineNotices should not be side-by-side
* The OfflineNotices should be the same height as a regular photo
* You should be able to scroll to see the rest of ObsDetails

**Screenshots**
![IMG_2293](https://github.com/user-attachments/assets/113837d0-281e-46b2-a604-0c90fb1833cb)

**Context (please complete the following information):**
 - Device: iPhone SE, 3rd gen
 - OS: 17.6.1
 - App version: 0.53.1 (123)

Note that I don't think this happens on ObsDetails whenever you're offline, not just from Notifications.

**Comment by albullington** [comment]
Maybe worth noting here that this bug also makes it impossible to scroll down in ObsDetails
