### ISSUE TITLE
Explore rapidly alternates between different maps

### ISSUE THREAD

**Issue by joergmlpts** [inaturalist/iNaturalistReactNative#2432]
**Describe the bug**
In Android, Explore rapidly alternates between different maps

**To Reproduce**
1. Go to Explore. Explore starts with a species view and all organisms. Set the location to Greater San Francisco Bay Area:
![Screenshot_20241114-193943](https://github.com/user-attachments/assets/77b4bea8-7f4d-4d82-97e2-cb0bba035daa)

2. Go to Observations and select the map view. Wait for the map to display.
![Screenshot_20241114-194030](https://github.com/user-attachments/assets/eca78074-4faf-438c-85d7-3da4737864c2)

4. Tap on 'All Organisms' and select taxon *Scoliopus bigelovii*.
5. Two or three maps are displayed over and over in rapid succession. They differ in their center coordinates and zoom. These are two of them:
![Screenshot_20241114-194124](https://github.com/user-attachments/assets/e9a0a9d1-fa19-49d4-89d2-d1725461b3be) ![Screenshot_20241114-194136](https://github.com/user-attachments/assets/5530738e-278e-47df-828b-2c555683fdc0)

**Expected behavior**
The map should not change quickly. Only a single map should be displayed or the oscillation should at least come to an end.

The map should be overlayed with tiles for the selected taxon. The maps are still shown for all organisms. The map should look like this:
![Screenshot_20241114-194540](https://github.com/user-attachments/assets/76862fba-b5e2-4e0e-833c-6c9ceb403786)

**Context (please complete the following information):**
 - Device: Pixel 7 Pro, also Android emulator w/ image Pixel 6a
 - OS: Android 15 on Pixel 7 Pro, Android 11 in Android emulator
 - App version: 0.53.1 (123)

**Additional context**
A workaround is to tap My Observations and then tap Explore again. This causes the oscillation to stop and the correct tiles for the selected taxon to be displayed.

**Comment by kueda** [comment]
Given that you were trying this in an emulator, does than mean you were running the current HEAD of the main branch?

**Comment by joergmlpts** [comment]
Yes, I see this can be reproduced with the current head of the main branch and well as with release 0.53.1 (123) and earlier releases.

**Comment by kueda** [comment]
I can repro in v0.54.0+125, happens whenever I choose a place, regardless of the place.

**Comment by joergmlpts** [comment]
Great! It was on and off for me. Sometimes a place would trigger it, sometimes a taxon change was also required, and sometimes I would not see the issue at all - all when running the same build.

Please do not assign this issue to staff just yet. I think I'm getting close to understanding what's going on and should be able to fix it.
