### ISSUE TITLE
Remove info and checkmark buttons from suggestion displayed at top of AI camera

### ISSUE THREAD

**Issue by kvangork** [inaturalist/iNaturalistReactNative#2456]
The AI camera suggestion should not have visible buttons. This will help users avoid confusion about how to capture their observation. By taking a photo and giving us the chance to use the online vision api they're also likely to get a better set of identification suggestions.

**Comment by israr002** [comment]
<img width="379" alt="image" src="https://github.com/user-attachments/assets/3bc39994-039f-4191-92c0-d5ef2ba3b94a">
@kvangork Are you referring to the above section in AI Camera

**Comment by kvangork** [comment]
@israr002 thanks for clarifying! That is the section I was referring to, which I believe is an instance of `TaxonResult`. The goal is to remove the chance for users to interact with the component and then be confused about why they don't have a photo recorded.

There's probably a minimal and sufficient change to achieve that goal using the existing `showCheckmark` and `hideInfoButton` properties on `TaxonResult` and not pursuing the larger modification of removing or disabling the Pressable that wraps the entire component. I'll edit the issue accordingly.

**Comment by jtklein** [comment]
The checkmark button should take a photo when pressed and accept the currently shown taxon as ID.
If it does not do that it is a bug.
