### ISSUE TITLE
GitGuardian: pre-commit hooks

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#25]
We should implement GitGuardian [pre-commit hooks](https://docs.gitguardian.com/internal-repositories-monitoring/integrations/git_hooks/pre_commit). This will allow us to prevent secrets from being committed to GitHub (for example, in case a file is not yet listed in `.gitignore`).

We'll also need to add instructions for setting up the hook to `README.md`.

**Comment by jtklein** [comment]
I have created a GitGuardian account for the organization, credentials are in the password manager.
