### ISSUE TITLE
Size & Language issues with 2 buttons side by side

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#2500]
### Multiple Buttons
Right now, some users in the forum have encountered issues with the UI that shows 2 buttons side by side in large text and in different languages (like German).

<img width="729" alt="image" src="https://github.com/user-attachments/assets/7cdf5957-1a0d-4f8f-988a-bc6fb25f7530">

For all screens that use my multiple buttons component above, enforce the following rules.
Note: These should **only apply** when 2 buttons are stacked next to each other, and all single buttons should stay as they are:
- no large text on these buttons (max large text size is 1x)
- max 3 lines of text inside the button, followed by a truncation with ellipses (see below)

<img width="684" alt="image" src="https://github.com/user-attachments/assets/70ffb61e-7c35-43aa-a533-cafd77ab5cdc">

Here are all the places in iNat Next with this component:
- [x] Obs Edit: Save and Upload
- [x] Obs Detail: Comment and Suggest ID
- [ ] Explore Filters: by me & not by me
- [x] Location Search: Nearby & Worldwide
- [ ] Bottom Sheets
     - [x] Suggest ID: Add Comment and Suggest ID
     - [x] Suggest ID with Remark: Edit Comment and Suggest ID
     - [x] Agree with ID: Add Comment and Agree
     - [x] Agree with ID with Remark: Edit Comment and Agree
     - [x] Delete Comment
     - [x] Withdraw ID
     - [x] Unfollow User
     - [x] "Check your email" in email confirmation (dont know if this is in our flows right now or not)
     - [x] Log out
     - [x] Discard Filter Changes
     - [x] Join Project
     - [x] Leave Project

### Missing Kebab Menu
Additionally, there are issues on Obs Edit when "New Observation" is translated and pushes the kebab menu off the screen:
<img width="517" alt="image" src="https://github.com/user-attachments/assets/7f76e548-291a-4ed8-9cd9-95f4ab94fee7">

For headings that sit next to back buttons and kebab menus like this (I think Obs Edit is the primary example), here are the guidelines:
- no large text on these headings (max large text size is 1x)
- The heading should be centered on screen, and there should be a min of 20px distance between the heading and the buttons to its left and right. The text should truncate with ellipses if the text exceeds this text area.

<img width="409" alt="image" src="https://github.com/user-attachments/assets/2978cc9c-e70e-45c6-a9bb-ac274c1d7fee">

**Comment by kueda** [comment]
Some implementation notes:

* Refactor `<ButtonBar>` so it can accept arbitrary children like it does now, but can also accept an object of button configurations (basically just `title` and `onPress`)
* Button configurations should be
  * `title`: the title of button
  * `onPress`: callback when button pressed
  * `isPrimary`: whether this button is primary and can expand to a max of 2/3 the width and use primary styling
* When it accepts button configurations, it should apply the restrictions Abhas described above
* Refactor to use `<ButtonBar>` in all the places Abhas listed above
