### ISSUE TITLE
Photo counts not centered

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#2506]
The photo count icon's number is not properly centered inside the icon. Here are the [designs](https://www.figma.com/design/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=1492-26516&node-type=frame&t=6lIMZR1Y99XFSa39-11) for proper centering.

![image](https://github.com/user-attachments/assets/4ec74b1f-7165-463f-abea-78d521e8728d)

**Comment by kueda** [comment]
This makes it to github, I assume.

**Comment by kvangork** [comment]
> This makes it to github, I assume.

Yes, it did.
