### ISSUE TITLE
Explore's map view opens ObsDetails beyond observation tiles

### ISSUE THREAD

**Issue by joergmlpts** [inaturalist/iNaturalistReactNative#2522]
**Describe the bug**
Explore's map view accepts taps outside the map region and navigates to ObsDetails for them.

**To Reproduce**
1. Go to Explore, select Observations, and enter Map View.

![Screenshot_1733419469](https://github.com/user-attachments/assets/53abc2c7-f282-404d-90e8-bbcfb7bfe8a4)

2. Tap on the map outside the region of observation tiles. In this example, I aimed for Jepson Prairie and tapped near the top of the map. The app navigates to ObsDetails:

![Screenshot_1733419462](https://github.com/user-attachments/assets/145c1ce3-08c7-4e59-b081-2bd3f8b0c0b7) ![Screenshot_1733419528](https://github.com/user-attachments/assets/98f73d56-2d20-4b3b-af4a-a1733677ab6d)

Oddly enough, the observation that opened is not even from where I tapped. It is from much further south.

**Expected behavior**
Ignore taps on the map where tiles do not show observations. 

**Context (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 15
 - App version: 0.55.3+130

**Additional context**
This issue has been observed on Android. It is unknown if this is also an issue on iOS.

**Comment by kueda** [comment]
This sounds like it's related to #1207 as well, like it seems as if the map view is capturing interactions with elements layered above it, but I'm not 100% convinced they're the same so let's leave this open for now. Definitely an Android-only issue.

**Comment by joergmlpts** [comment]
Is there something wrong with v0.55.3+130? Wherever I tap on the map, ObsDetails opens the same observation, that mallow. I never saw this before.

**Comment by joergmlpts** [comment]
This issue is only for Android and a very specific context. It only occurs when the map view is first shown. After user interaction has occurred - like panning or zooming - taps outside the map region have no effect anymore and the app works as expected.

This issue is because [currentZoom is initialized to zero](https://github.com/inaturalist/iNaturalistReactNative/blob/214bb6a818f8ea922f255ae6770fbdf69c1a3bd4/src/components/SharedComponents/Map/Map.tsx#L117) and it will not be set to the correct value until user interaction occurs. This issue can be assigned to me; I have a fix.

This does not seem related to issue #1207. My guess is issue #1207 is due to a subtle difference in event handling in Android vs iOS. Buttons and map view are not in a parent-child relation and they get separate events in Android where in iOS the button handles the event and that's the end of it - the event is not propagated to the map view.
