### ISSUE TITLE
App start needs login

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#253]
Build 32

Every time I open iNatRN I have to log in again.
It might be losing it's jwt every time the app is shut down, and it's failing to get a new one.

**Comment by jtklein** [comment]
It's actually not every time I open the app anymore. After installation it happened many times I opened the app. Now it did not happen for several app opens.

**Comment by kueda** [comment]
@jtklein have you figured out any consistent repro conditions?
