### ISSUE TITLE
Location not imported along with gallery photos

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#2575]
**Describe the bug**

Not sure if other people are running into this or if it's only me… when I try to import a gallery photo, the location is not showing up in ObsEdit.

**To Reproduce**

1. Delete app
2. Reinstall fresh app from the App Store (currently 0.55.3 - 130)
3. Log in or don't log in
4. Change Settings to show all observation options
5. Tap the plus button and open the gallery
6. Import a recent photo taken in the iOS native camera
7. If logged in, advance to ObsEdit. If logged out, save observation and tap into ObsEdit from MyObservations screen
8. ObsEdit will show No Location, rather than the observation location from metadata

**Expected behavior**

Imported photos should use their metadata location

**Screenshots**

**Context (please complete the following information):**

* App: iNatNext
* Device: iPhone 15 Pro
* OS: 18.2
* App version, or Browser: 0.57.0 (132) and 0.55.3 - 130 (TestFlight and production)

**Additional context**

Maybe this is something funky with the latest iOS 18? I also can't get the AICamera or StandardCamera to load a camera instead of a black screen on either app version.

**Comment by kueda** [comment]
Alex, Tony, and I all [tried to reproduce this](https://inaturalist.slack.com/archives/C02G5AATVGA/p1734475699931569) in iOS 18.2 and could not, so I think this was something unique about Amanda's setup.
