### ISSUE TITLE
Uploading an observation to the website is coming from "testclient"

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#267]
After uploading an observation, on the website version the panel that shows from which app the observation was uploaded shows "testclient" as the source of the observation.

I am not sure if this is to change here or on the website code, or on the client apps database. Anyway, it concerns this app so I have added it here.

**Comment by kueda** [comment]
Yeah, we're using the credentials from https://www.inaturalist.org/oauth/applications/1 while we're developing, which seems fine to me. Do you think that's a problem for some reason? FWIW, eventually we will want to shift to different app credentials, though it's debatable what those should be. We could use the ones for the existing apps and just use different build settings for iOS and Android, or we could treat the RN app as a totally separate app and track its usage independently from the native apps. Thoughts?
