### ISSUE TITLE
Some photos not shown when navigating between folders

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#268]
When making an observation in gallery screen: when changing the folder once selecting a photo and then switching back to the first folder, a portion of the youngest photos is not shown.

**Comment by kueda** [comment]
@jtklein I can't replicate this, and I'm also not sure what portion of the newer photos are not being shown. Can you enumerate your repro steps? I know everyone's phone is going to be different but everyone starts out in "Camera Roll" and probably has a "Camera folder.

**Comment by jtklein** [comment]
So, I narrowed it down and can replicate every time on my phone: When changing to a folder and then back to the first folder the photos that are younger than the youngest one in the second folder are not shown. I have made a screen recording on my iPhone with the version from TestFlight.

https://user-images.githubusercontent.com/17345891/206203741-e925dd55-1d87-4e95-b9e2-dacd4a54125b.mp4
