### ISSUE TITLE
Camera flow

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#28]
A user should be able to take photos with the AR Camera on supported devices (probably iOS 13+ in case we decide to include the latest model, tbd on minimum Android OS). Users with older devices should have a fallback to a regular camera where they can still take photos within the iNat mobile app.

- [ ] AR camera
- [ ] Only show vision camera option for iOS 13+ and Android 12+ (for now)
- [x] Regular camera as fallback (probably [this library](https://github.com/mrousavy/react-native-vision-camera))

**Comment by kueda** [comment]
Vision camera is going to be a whole collection of issues, I suspect, so I'm going to close this.
