### ISSUE TITLE
Top 2 observations in obs list are not tappable when scrolled down

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#298]
*To Reproduce**
1. Go to ObsList
2. Scroll down so the first observation is tucked slightly under the toolbar
3. First two observations are not pressable

**Expected behavior**
A user should be able to tap all observations and navigate to the appropriate screen (obs detail or obs edit)

**Screenshots**

**Context (please complete the following information):**
 - Device: iOS/Android

**Comment by angielt** [comment]
I wasn't able to replicate this bug on iOS or android 

https://user-images.githubusercontent.com/13282161/210854424-a0c1e9f2-ea8f-490b-b0c8-cc7d5bbeb88e.mp4

**Comment by albullington** [comment]
I can replicate. If I scroll up so the header is offscreen, I can't tap to navigate anywhere above the blue markup line.

<img width="521" alt="Screen Shot 2023-01-05 at 11 30 49 AM" src="https://user-images.githubusercontent.com/35536439/210864851-b6ec0953-8180-4f4b-ace9-d84d72162a0f.png">

**Comment by Chrischuck** [comment]
Looks to be blocked by something around this component

<img width="1189" alt="Screenshot 2023-01-05 at 3 15 24 PM" src="https://user-images.githubusercontent.com/13311268/210881494-7bb0befb-d3e9-4e21-8f0a-a4cc7d15afd6.png">
