### ISSUE TITLE
Bug with observed_on_string when saving observation

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#311]
**To Reproduce**
1. Go to Photo Importer on iOS simulator
2. Tap on one of the photos that come preloaded with the simulator
3. Either tap the back button, then save, or tap the save button
4. See error in screenshot below

**Expected behavior**
The client should make sure that all photos are saved with `observed_on_string` in a string format, not a date object.

**Screenshots**
<img width="464" alt="Screen Shot 2022-12-21 at 12 45 17 PM" src="https://user-images.githubusercontent.com/35536439/209002980-b252f878-d7cb-4acf-bf39-3467df8ca23e.png">

**Comment by kueda** [comment]
FWIW, I can replicate in Android.
