### ISSUE TITLE
Tapping on obs w/o evidence from My Observations takes you to obs edit

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#313]
**Describe the bug**
When you tap an observation without evidence on My Observations you end up on Obs Edit instead of Obs Detail.

**To Reproduce**
1. Make an observation without evidence
2. Tap on it in My Observations
3. You land on Obs Edit instead of Obs Detail

**Expected behavior**
You should land on Obs Detail. An observation without evidence is just like any other observation

**Context (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 12
 - App version: 0.1.1 (32)

**Comment by albullington** [comment]
Is this for an observation that has already been uploaded to the server or for an observation that is pending upload?

Issue #282 made it so any observation that has not been uploaded yet will land a user back on Obs Edit, instead of Obs Detail.

**Comment by kueda** [comment]
I guess it's any observation that hasn't been uploaded. What was the thinking there? I'm fine if that's a temporary fix for something, but if that's the case maybe it would help to show a toast or something to that effect.

**Comment by albullington** [comment]
This is something Abhas recorded in our last mobile sync bug hunt as a way the UX should work. In the mobile sync notes, it's under bug hunt, Abhas, and the first item under home screen: "When clicking on a saved observation, it should open obs edit, not obs detail (which is populated with nothing)"

**Comment by kueda** [comment]
Thanks. Looks like that was on [11/29](https://docs.google.com/document/d/1h4a_V6bSwQLL8hB2DtOKUjNRheqHKkVr6DUfvBBlv28/edit#heading=h.1fgbo64ubo9w).
