### ISSUE TITLE
Tapping no-evidence icon in grid view does nothing

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#314]
**Describe the bug**
When viewing My Observations in grid view, tapping the icon for an observation without evidence does nothing when it should bring you to Obs Detail.

**To Reproduce**
1. Make an observation without evidence
2. Go to My Observations
3. Tap on the icon for your observation without evidence: nothing happens.

**Expected behavior**
It should bring you to Obs Detail just like it does when you tap the photo for an observation with a photo.

**Context (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 12
 - App version: 0.1.1 (32)

**Comment by jtklein** [comment]
I can not replicate this on emulator, pressing on the no evidence icon goes to Obs Detail for me. Did you mean list view, maybe? There it seems to crash.

`TypeError: Cannot read property 'length' of undefined

This error is located at:
    in ObsDetails (at SceneView.tsx:132)`

**Comment by jtklein** [comment]
OK, I could also get the same error on grid view, it is not always happening though.

**Comment by kueda** [comment]
FWIW, I can't replicate this any more either. Not sure what was happening originally.
