### ISSUE TITLE
My Observations doesn't show any taxon name for observations of taxa without common names

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#320]
**Describe the bug**
In the list and grid views on My Observations, observations associated with a taxon that has no common name shows nothing in the name area.

**To Reproduce**
1. Make an observation of a taxon with no common name, like the [genus _Corbicula_](https://www.inaturalist.org/taxa/64009-Corbicula)
2. Save the observation and view it in list view on My Observations
3. The `place_guess` and date/time appear but it's just a blank space where the name should appear

**Expected behavior**
If an observation is associated with a taxon that has no common name, My Observations should still show the scientific name in both list and grid views.

**Screenshots**

List and grid views of the same observation of _Corbicula_:

![Screenshot_20221230-171602](https://user-images.githubusercontent.com/22691/210115195-6030f1e7-fa38-4870-927f-9969a00f8f7f.jpeg)
![Screenshot_20221230-171554](https://user-images.githubusercontent.com/22691/210115200-bbf39d32-3e44-479f-a722-4d976b4b542a.jpeg)

**Context (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 12
 - App version: 0.1.1 (32), d51685b48855fe469ffde50a28581c418fa2b0e8

**Additional context**
Taxon name display is complicated and I think we'll eventually need something similar to the [`<SplitTaxon>` component](https://github.com/inaturalist/inaturalist/blob/main/app/webpack/shared/components/split_taxon.jsx) we have on the web, so one way to address might be to get started on a version of that for RN. FWIW, "split" was supposed to mean "showing both common and scientific names whenever possible," but I've never been very happy with that. Open to better names if people have ideas. `DisplayTaxon`? `DisplayTaxonName`? `TaxonNameForUser`? `MoreComplicatedThanMaybeItNeedsToBeTaxonNameDisplay`?

**Comment by Chrischuck** [comment]
Would love to take a stab at this @kueda

**Comment by kueda** [comment]
Go for it, @Chrischuck.

**Comment by Chrischuck** [comment]
<img width="341" alt="Screenshot 2023-01-02 at 8 30 39 PM" src="https://user-images.githubusercontent.com/13311268/210300653-64c8a69a-267a-4d68-af5e-9706db49d5cb.png">

Got these going for a couple of observations w/o common names.

Not sure if we want to have common and scientific names on different lines? Or any other changes for that matter. I more or less used the same logic from the `SplitTaxon` component.

Also, could someone chime in on how i18n is done in this app? Thanks!

**Comment by kueda** [comment]
Thanks, @Chrischuck, I'll try and review this week (if not today).

> Not sure if we want to have common and scientific names on different lines?

Just show one name for now, so if there is a common name show that, and if there's not show the scientific name. Eventually we'll want to show the name that the user prefers, but I think that's out of scope here.

> Also, could someone chime in on how i18n is done in this app?

FWIW, [instructions on translation](https://github.com/inaturalist/iNaturalistReactNative#translations) are in the README.

**Comment by albullington** [comment]
Closed by #334
