### ISSUE TITLE
Selecting a taxon in AddID should happen without having to dismiss the keyboard

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#322]
I hope this is possible. Currently when you add an ID and you type something in to find a taxon, the results show up as you type, but to actually choose a result, you tap the green checkmark and all it does is dismiss the keyboard. Then you have to tap the green checkmark again to actually choose the taxon. You should be able to choose it by tapping it once.

**Comment by Chrischuck** [comment]
https://www.reddit.com/r/reactnative/comments/awsd3g/prevent_input_from_swallowing_a_tap_event_on/

this seems relevant, I can take a look into this

**Comment by albullington** [comment]
Closed via PR #336
