### ISSUE TITLE
verifyCredentials failed when calling /oauth/token -  CLIENT_ERROR 400

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#326]
Error thrown when logging in using my iNat account on an Android emulator. The app continues to work though and I can see my data when I dismiss the error.

<img width="410" alt="Screenshot 2023-01-02 at 20 56 52" src="https://user-images.githubusercontent.com/17345891/210274002-481e7286-13f1-432b-9793-00e8bd75d0a9.png">

**Comment by kueda** [comment]
FWIW, I can get this to happen when I try to sign into an account that hasn't been verified, which points to a number of related things that should probably change.

- [ ] Requests to `/oauth/token` should include a `locale` parameter in the body so error responses can be localized
- [ ] Requests to `/oauth/token` will return a JSON body when when there's an error, per the OAuth spec. We should show the `error_description` in the body to the user (maybe in an alert, maybe in the red error text we currently show).
- [ ] These 400 errors during auth are not really errors in the software and probably should not be logged with `console.error` (other kinds of errors, e.g. 5xx errors, should)
