### ISSUE TITLE
Move Android e2e tests to ubuntu-latest

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#328]
Currently, Android e2e CI tests are running on macos-latest in GitHub Actions with 10x the cost compared to running on ubuntu-latest. In contrast to the iOS tests, the Android tests do not need to be run macos, so we could explore switching to a different runner.
There were some hurdles though with using ubuntu that I couldn't overcome immediately. So, it would not be a straight-forward exercise.

**Comment by kueda** [comment]
FWIW, we are not paying for these Github Actions runs, so the cost is not really an issue until that situation changes. Is there another advantage to running these on Ubuntu?

**Comment by jtklein** [comment]
No, only cost reasons, but maybe good to keep in mind.

**Comment by jtklein** [comment]
We are currently relying on two commands to rebuild Detox from cached node_modules, to save time, which are only available on macOS, so closing this for now.
