### ISSUE TITLE
Crash when signing in as a user with a non-English locale

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#349]
**Describe the bug**
When you sign in as a user with a locale of `es` the app crashes immediately after sign in.

**To Reproduce**
1. On the website, change your language to `Spanish` so your locale is `es`
2. In the app, sign in
3. The app will crash on My Observations

**Expected behavior**
Signing in as a user with a non-English locale should not crash. The app should be localized with the user's locale if possible, otherwise we should just be showing English text.

**Context (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 12
 - App version: [8c13f0b](https://github.com/inaturalist/iNaturalistReactNative/commit/8c13f0ba1cb5f41e932cdab5bc6d8d865442730c), but I'm pretty sure this predates that commit.

**Additional context**
IMO, this would be a good end-to-end test: sign in as a real user whose locale is always `es` or `es-MX` and ensure My Observations loads.

**Comment by jtklein** [comment]
FYI, we will add an e2e test later today for this scenario.

**Comment by Chrischuck** [comment]
@jtklein Hmmm ok, I can take a look at this again this weekend

**Comment by Chrischuck** [comment]
@jtklein can you provide a species + language that I can use to test this with?

**Comment by jtklein** [comment]
https://www.inaturalist.org/taxa/76465-Crassula-ovata in Spanish

**Comment by albullington** [comment]
Can't reproduce this, and I believe it was fixed with unicode in [this commit](https://github.com/inaturalist/iNaturalistReactNative/commit/4f732bace9a7a0bce3c8c104bfd8ca627645c7df).
