### ISSUE TITLE
Refactor test factories to produce minimally viable record

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#351]
The task is to update the factories so they make a minimally viable record.
E.g., the observation used in tests currently has comments, photos, identifications, a description etc. A minimum viable observation would have none of those though.
If tests need things like an observation with comments or photos, the test should construct them individually.

**Comment by albullington** [comment]
@jtklein do you have thoughts on which keys should remain in a minimum viable observation? The only key that's required in realm is a uuid, so a LocalObservation factory could be as simple as only having a uuid.

Or we could simplify LocalObservation so it only contains keys with primitive values, but not keys with additional factories (like comments, identifications, taxon, user).

Maybe it would help to have more context on why you think we should simplify factories & how it improves our test suite to construct more complex factories/mocks in individual tests.

**Comment by jtklein** [comment]
This came up during changes to `ObsDetails.test.js`:

When testing the UI for an observation that has neither photos nor sound (= observation without evidence) I had to do the following:
```

const mockObservation = factory( "LocalObservation", {
  created_at: "2022-11-27T19:07:41-08:00",
  time_observed_at: "2023-12-14T21:07:41-09:30"
} );
const mockNoEvidenceObservation = factory( "LocalObservation", {
  created_at: "2022-11-27T19:07:41-08:00",
  time_observed_at: "2023-12-14T21:07:41-09:30"
} );
mockNoEvidenceObservation.observationPhotos = [];
mockNoEvidenceObservation.observationSounds = [];
```

A minimally viable observation would be the one with the least required fields that get's accepted by the API and created. In this specific case, e.g. empty sound and photos would be accepted. I don't know exactly how this minimally viable observation would look like from server specs, i.e. which fields are required and which optional.
