### ISSUE TITLE
Ensure JWT gets refreshed

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#353]
We use JSON Web Tokens (JWTs) as tokens of authorization when accessing iNat on behalf of a user. Our JWTs expire after 30 minutes, after which the API should return a 401 response when you try to use them. We currently try to address this in `getJWTToken` (which should probably be renamed since we're getting a JSON Web Token, not a JSON Web Token Token) by storing the time when we retrieved the token, and the next time we ask for one, we check to see if the existing token is about to expire (or is past expiry) and if it is we fetch a new one.

However, occasionally the app reports problems about the JWT not working. I haven't found consistent repro conditions, but it seems to happen after the app has been idle for a while, which suggests the JWT is expiring and not getting refreshed.

I *believe* problems occur when components and hook hold on to the JWT in state, e.g. in the `useApiToken` hook, which seems to hold on to the token forever until the user logs out. So one solid TODO here is to make sure this doesn't happen, either by always using getJWTToken directly to take advantage of its expiration check, or to build the expiration check into hooks and components that hold on to the token.

You might also considering adding some defensive code to all authenticated API requests that responds to 401 and 403 responses by refreshing the JWT and trying again once.

**Comment by kueda** [comment]
FWIW, I hit what might be a related issue today: I installed the app with `npm run android`, signed in while connected to Metro, disconnected by device, drove into the woods where I had spotty Internet connectivity, opened the app again and was immediately signed out.

**Comment by jtklein** [comment]
We merged changes so that now we will fetch a new token and retry if a 401 or 403 is hit using react-query. And we fetch the token on every render in `useApiToken` hook.
