### ISSUE TITLE
Log exceptions

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#358]
#357 needs to happen first

Catch JS and native exceptions with [react-native-exception-handler](https://github.com/a7ul/react-native-exception-handler) (or something, but that was the first that I found and it seems pretty popular and up-to-date) and try to log a stack trace using [react-native-logs](https://github.com/onubo/react-native-logs). Ideally we would log fully symbolicated native crashes, but I think it would still be useful if we can get the JS traces.

**Comment by jtklein** [comment]
Some links which might be helpful, from my research into the matter for Seek:

two packages for error handling
https://github.com/a7ul/react-native-exception-handler
https://github.com/bvaughn/react-error-boundary

This might be helpful in getting setup:
https://stackoverflow.com/questions/67767451/how-to-handle-errors-globally-in-react-native
https://github.com/a7ul/react-native-exception-handler-example/blob/master/App.js

package to simulate a native test error:
https://github.com/cwhenderson20/react-native-crash-tester
