### ISSUE TITLE
Standard Camera layout doesn't adapt when rotating to landscape orientation

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#360]
**Describe the bug**
When you rotate the device from portrait to landscape orientation, the layout does adjust and the bar at the bottom remains the same width

**To Reproduce**
1. With the device in portrait orientation, open the Standard Camera
2. Rotate the device to landscape orientation; the bar including the shutter and back buttons remains the same width it was in portrait, flush left

**Expected behavior**
That bar should fill the width of the screen, OR the Standard Camera should simply not allow rotation on small screens (this seems to about the behavior of the Google Camera on my Pixel, though I feel like rotation should be allowed on large devices like tablets where there's room for it.

**Screenshots**
Here's what this looks like on my Pixel in landscape:
![Screenshot_20230112-140426](https://user-images.githubusercontent.com/22691/212221261-b75024ae-335a-4876-8998-49d5165ddb32.jpg)

**Context (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 12
 - App version: [fbeedb2](https://github.com/inaturalist/iNaturalistReactNative/commit/fbeedb2f2b979656cf7d1aa812f8c1722fe10c50)

**Additional context**
Possibly the same solution as #350. One additional requirement: when the device is in landscape orientation, the pictures taken should also be in landscape orientation, even if the UI doesn't change!

**Comment by albullington** [comment]
@angielt are you still working on this one? It looks like most of this is done, but we still need:

- [ ] Show landscape mode on tablets, but not phones (landscape is working for me on iPhone at the moment)
- [ ] Saved photos to be taken & displayed (in the media viewer, for example) in landscape mode, not portrait mode

**Comment by angielt** [comment]
This issue was probably one I worked on in a branch for another issue since they were similar and I forgot to close it at the time. I remember disabling landscape orientation for smaller devices but it seems to not be working currently. I'll work on this while i'm working on other issues with the Standard Camera.
