### ISSUE TITLE
Obs Edit should not ask you to discard changes if you didn't make any

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#361]
**Describe the bug**
Whenever you enter Obs Edit for an existing observation then tap the back button in the header (or the Android system back button), You get an alert asking you if you want to discard changes, even if you didn't make any.

**To Reproduce**
1. Make a new observation and save without uploading
2. Edit that observation
3. Don't make any changes, just tap the back button in the header
4. You'll get the "unsaved changes" alert, even though you don't have any unsaved changes because you didn't change anything

**Expected behavior**
The alert should appear for new observations... because at the very least the date is an unsaved change, but when editing an existing observation it should only show you this alert if you actually changed something.

**Context (please complete the following information):**
 - Device: any
 - OS: any
 - App version: [fbeedb2](https://github.com/inaturalist/iNaturalistReactNative/commit/fbeedb2f2b979656cf7d1aa812f8c1722fe10c50)

**Comment by Chrischuck** [comment]
I can take a look at this

**Comment by albullington** [comment]
Fixed in PR #368
