### ISSUE TITLE
Allow sharing photos with the app

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#364]
This might be actionable in Android and more of a research question in iOS, but I'd like to support sharing photos from outside the app to the app. This is something I do constantly in the native apps, usually because I want to use a different camera app to take photos, then immediately share them with iNat. Inside the app it should drop you on the Group Photos view just like it does when you're choosing photos to import from inside the app, and you should identically after that.

First step is probably to describe a plan of attack, like what libraries are you going to use, is this going to be possible in iOS, etc, and if that seems reasonable we can articulate a plan for implementation.

**Comment by Chrischuck** [comment]
https://medium.com/@sumedh.tare/react-native-share-extension-61a1ca47cea0

Looks promising
