### ISSUE TITLE
Shutter effect isn't working anymore

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#391]
**Describe the bug**
We added a nice shutter effect for the camera in #108 but it doesn't seem to work any more

**To Reproduce**
1. Open the Standard Camera
2. Tap the capture button
3. Witness the terrifying absence of a shutter effect

**Expected behavior**
I expect the behavior from #108 to still work.

**Context (please complete the following information):**
 - Device: Pixel 3, iPad Air 5th gen
 - OS: Android 12, iPadOS 16.2
 - App version: 0.1.1 (37)

**Comment by Chrischuck** [comment]
I can make a pr for this
