### ISSUE TITLE
Map does not show in Android on ObsDetail page

### ISSUE THREAD

**Issue by Chrischuck** [inaturalist/iNaturalistReactNative#396]
**Describe the bug**

On android, it appears the map does not show in the ObsDetail page. This was brought up in PR #385 

**To Reproduce**

1. Select an observation
2. Click on "Data" tab
3. See that the map shows on ios but not android

**Expected behavior**
The map should show

**Screenshots**
<img width="775" alt="Screenshot 2023-01-26 at 3 46 56 PM" src="https://user-images.githubusercontent.com/13311268/214957833-c350bdf2-73e3-42ee-bef2-2949a603d8cc.png">

**Context (please complete the following information):**
 - Device: Android Pixel 3
 - App version: [e.g. 1.0.0]

**Additional context**

Poking around, I think this [line](https://github.com/inaturalist/iNaturalistReactNative/blob/main/src/components/SharedComponents/Map.js#L30)

should be 
```
  if ( !initialLatitude || !initialLongitude ) {
```

I don't have a google maps api key, but when I make that change an error about not having an api key comes up. So I think it's going in the right direction.

However, I think there's a deeper issue in that the `useUserLocation` hook only gets the location for iOS, which is why `latLng` is null in android.

**Comment by kueda** [comment]
Not happening in [v0.17.1+64](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.17.1%2B64)
