### ISSUE TITLE
InlineUser component

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#398]
`<InlineUser user={user} />` corresponds to ["Username & Profile Picture"](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=1492%3A12073&t=C1renIwFPVp304V0-0) in the UI designs:

<img width="191" alt="Screen Shot 2023-01-26 at 3 22 28 PM" src="https://user-images.githubusercontent.com/22691/214972803-b44113ac-810a-401d-9fa2-091dbd191051.png">

So that's

- [x] a 22px / 1.222rem `<UserIcon />`
- [x] 7px / 0.388rem space
- [x] `@` and the username (login) in Body3 style (depends on #383)

I guess for now we don't worry about truncation.

**Comment by kueda** [comment]
@Chrischuck would you mind commenting on the issue before working on it? The work is much appreciated, but I don't think I can assign you until you comment, and it also helps others know that the issue is being worked on already.

**Comment by Chrischuck** [comment]
@kueda apologies, forgot to do so.

**Comment by jtklein** [comment]
This #410 addresses some of the TODOs only. The further required change from the above TODO is the Text after the new Text components is available.

However, I would like to add:

- [ ] Replace the fallback images (no user image & offline) with icons from our own icon font after those two icons are included
- [ ] Add unit test for the UserIcon component
- [ ] Lastly (after all UI is finished): Add snapshot test for the UserIcon and InlineUser component
