### ISSUE TITLE
ActivityCount component

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#401]
Pretty simple one that's just an icon and a number, but we'll be reusing it for both comments and identifications. Looks like this:

![Color=Dark](https://user-images.githubusercontent.com/22691/214989355-5538ee6c-6e0c-4f94-8538-792e43f28b49.svg)

Spec is [here](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=335%3A2161&t=C1renIwFPVp304V0-1).

Props:
- [x] icon: default to the speech bubble
- [x] color: default to `DarkGray` / `#454545`

**Comment by jtklein** [comment]
Accessibility props can follow this example [<View].(https://github.com/inaturalist/iNaturalistReactNative/blob/f8c403b9b14a0bd306b028fcd5237ee257c2c35b/src/components/ObsDetails/ObsDetails.js#L340-L341)
The enclosing view get's the props and is read with a label and the number.
