### ISSUE TITLE
ObsListToolbar component

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#405]
The `<ObsListToolbar>` sits at the bottom of the header on My Observations and remains stuck to the top of the screen as you scroll down. The intent here is to make a simple component that just responds to state, not one that actually uploads observations. I guess this isn't reusable, but it is something we'll need on My Observations, and it has a lot of moving parts.

There is a component for this in the Components sheet of the UI designs, but most of the actual states are on the [designs for My Observations](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=315%3A481&t=V7n3F2CGYm2TIfQO-1).

Props:
* `navigateToExplore`: navigates the user to Explore with contextually appropriate filters (i.e. only showing the current user's observations
* `startUpload`: function starts uploading all observations that need it
* `stopUpload`: function that stops upload in progress
* `uploadInProgress`: boolean indicating whether an upload is in progress
* `numToUpload`: number of records that need to be uploaded
* `numUploaded`: number of records in the current upload batch that have been uploaded
* `uploadError`: string containing one
* `layout`: string describing current layout, `grid` or `list` (default: `list)
* `toggleLayout`: function to change the layout to the opposite of what it is now

Here's an attempt at describing all the functionality, but you'll need to consult the designs for all the visual details.

- [ ] Explore button (compass rose icon): fires navigateToExplore when tapped, only visible when signed in
- [ ] Upload status (sync and related icons): combination button and status indicator,
  - [x] should be `inatGreen` when there are observations to upload or an upload is in progress, `darkGray` otherwise
  - [x] when `uploadInProgress` is false, tapping it should fire `startUpload()`
  - [ ] when `uploadInProgress` is false and numToUpload is 0, text should not appear
  - [x] when `uploadInProgress` is false and numToUpload is > 0, text should read "Upload {$numToUpload} observations"
  - [ ] - [ ] when `uploadInProgress` is false and numToUpload is > 0, icon should be an exclamation point inside of a sync icon (might just need to be a separate icon)
  - [ ] when `uploadInProgress` is false and numToUpload is > 0 and the device is the smallest size, text should read "Upload"
  - [x] when `uploadInProgress` is true, text should read "Uploading {$numUploaded} of {$numToUpload} observations"
  - [ ] when `uploadInProgress` is true and the device is the smallest size, text should read "{$numUploaded} of {$numToUpload}"
  - [ ] when `uploadInProgress` is true, sync icon should have a clockwise rotation animation
  - [x] when `uploadInProgress` is true, an inatGreen progress bar should appear along the bottom edge of the toolbar showing the progress (total is numToUpload, current state is numUploaded)
  - [x] when `uploadInProgress` is true, an IconButton appears after the text with an x; tapping it fires `stopUpload()`
  - [ ] text status can wrap, but the cancel button should not
  - [x] when `uploadError` has a value, a second line of smaller, red text should show that error below the other text
  - [ ] when `uploadError`has a value and `uploadInProgress` is false, the exclamation-sync icon should be red
- [x] when `layout` is `grid`, the layout button should show a `list` icon and vice versa (i.e. it shows what the user is going to get when they tap the button)
- [ ] tapping the layout button fires toggleLayout()

**Comment by Chrischuck** [comment]
I can get something going on this

**Comment by albullington** [comment]
@kueda what should the sync button do when uploadInProgress is false and numToUpload is 0? Should it be disabled?

**Comment by kueda** [comment]
@albullington sorry, totally missed your question! Yes, sync button should be disabled under those conditions.

**Comment by Chrischuck** [comment]
@kueda does it make sense to even show the sync button in that case?

**Comment by kueda** [comment]
@Chrischuck according to the designs, the button remains but with no text.

**Comment by albullington** [comment]
Completed via #411 and #510
