### ISSUE TITLE
Test that Observations/hooks/useObservations fetches observations when userLogin is set

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#41]
We've been mocking hooks instead of testing them. Sometimes, there are hooks like `useObservations` that check for internet/no internet states and pull data from either the API or Realm accordingly. We don't need 100% test coverage, but we should probably figure out a way to test the logic in certain custom hooks like `useObservations`.

Here, the tasks is to start that process with a single test: test that a network request is made to fetch observations when a component sets the `userLogin` with the `syncObservations` method.

There's an additional testing library called [react-hooks-testing-library](https://github.com/testing-library/react-hooks-testing-library), which seems to be the recommended way to test custom hooks. The other recommended way would be testing a hook via the component instead of mocking it.

**Comment by budowski** [comment]
This is no longer relevant - we changed the way we save/check for login tokens
