### ISSUE TITLE
Display internationalized strings with variables that have different HTML formatting

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#423]
One thing that came up in comments in PR #411 is the need to be able to use translated strings with variables that have different types of styling. This is specifically to address strings like "Welcome back, @username" (displayed below), though it's likely to come up in other places throughout the app.

![](https://user-images.githubusercontent.com/13311268/215300884-afa723a6-1229-4f99-b3fa-37681b22732e.png)

A few ideas we discussed:

1. Creating a [SubstringStyledText](https://github.com/inaturalist/SeekReactNative/blob/adfddb027faffb79eeb4abe08745bea35850d3c2/components/SeekYearInReview/SeekYearInReviewScreen.js#L45) component like in Seek
2. Using [react-i18next with HTML elements](https://react.i18next.com/latest/trans-component#usage-with-simple-html-elements-like-less-than-br-greater-than-and-others-v10.4.0)
3. Using an HTML renderer, like [this one](https://github.com/inaturalist/SeekReactNative/blob/347397c30a073ea0b48ed1cf2bf6ffc19e8f70a1/components/Auth/Signup/LicensePhotosScreen.js#L171) in Seek

**Comment by Chrischuck** [comment]
I can take a look at this
