### ISSUE TITLE
Basic Media Viewer

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#43]
The Media Viewer allows the viewer to view a collection of photos and/or sounds, generally associated with an observation. The user can enter the Media Viewer from the Normal Camera by tapping one of the photos taken, or from Obs Edit, by tapping a photo or a sound.

This issue addresses the basic functionality required for the [Observation Loop 1 milestone](https://github.com/inaturalist/iNaturalistReactNative/milestone/1), but we'll list the rest of the functionality for future reference

Functionality:
- [x] View a collection of photos with the selected media item in the main view and the others visible in a carousel below it
- [x] Carousel shows center-cropped thumbnails for photos; swipe left/right gestures show pan the carousel left and right
- [x] Tapping on items in the carousel shows them in the main area
- [x] Current item highlighted in the carousel with a differently-colored border
- [x] Swipe left/right gestures in the main area should navigate to the next/previous media item
- [x] View full sized image when selected (i.e. not a scaled down version), including zoom
- [x] Delete image or sound with confirmation alert
- [x] View and edit/delete other photos attached to the observation

[Design Figma file](https://www.figma.com/file/XmLaQzJ1McnsYQysB57hib/iNaturalist-Mobile-UX-Design?node-id=3%3A249) - look for the last screen in the multicapture camera section

<img width="390" alt="Media Viewer - Photos" src="https://user-images.githubusercontent.com/35536439/160724734-5f6e5a78-b560-4fcd-9479-67f6373ebfb8.png">

Future functionality:

- Show sounds as the selected media item in the main view and mixed in with other sounds and photos visible in the carousel below it
- Carousel shows sound icon for sounds
- Play a sound when in the main view
- Button to crop image using [react-native-image-crop-picker](https://www.npmjs.com/package/react-native-image-crop-picker) (or another, or custom, if preferred), which crops the image, saves it, and returns the user to the Media Viewer

**Comment by kueda** [comment]
Amanda's been having some trouble implementing zoom *and* swipe navigation in the main area, which raises this question for @abhasinat: *should* you be able to swipe to the prev / next photo while you are zoomed in? Supporting something like that requires complicated gesture handling that's tricky to implement, but also kind of confusing to the user (does a swipe pan the zoomed photo or does it navigate to the next photo?) Alternatively, when the photo is zoomed we could disable swipe nav, and maybe add a button to zoom all the way out to get back to swipability.

**Comment by abhasinat** [comment]
Good question. I think zooming in should disable swiping between different photos. When a photo is fully zoomed out, I think swiping between previous and next photo sounds good.
