### ISSUE TITLE
ObsStatus component

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#434]
<img width="516" alt="Screen Shot 2023-02-03 at 10 32 03 AM" src="https://user-images.githubusercontent.com/35536439/216680239-859964ad-fcf4-411c-8fc6-c7d80c4a0693.png">
<img width="394" alt="Screen Shot 2023-02-03 at 10 32 27 AM" src="https://user-images.githubusercontent.com/35536439/216680296-9ee73aae-dc80-4930-9964-56a3b5b1845d.png">

This component should have:
- [ ]  ActivityCount component for ids
- [x]  ActivityCount component for comments
- [x]  QualityGradeStatus component

Default color for these components should be:
- [x] #454545 (darkGray)

This component should accept a `layout` prop. If the layout is "list", the subcomponents should display in a column & use the default subcomponent colors.

If the layout is "grid", subcomponents should display in a row and the color of subcomponents should be white.

In each layout, subcomponents should have a margin of 10px between them.

**Comment by Chrischuck** [comment]
I can work on this. Not sure how much different it is from the current component?

I will put up a PR that can be discussed.
