### ISSUE TITLE
TaxonName component

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#435]
<img width="309" alt="Screen Shot 2023-02-03 at 10 39 34 AM" src="https://user-images.githubusercontent.com/35536439/216681572-4869b76b-5df4-4670-963e-5862adaa4e21.png">
<img width="156" alt="Screen Shot 2023-02-03 at 10 49 03 AM" src="https://user-images.githubusercontent.com/35536439/216683245-9b781be5-a6a8-4504-84a4-2c348423f461.png">
<img width="515" alt="Screen Shot 2023-02-03 at 10 49 26 AM" src="https://user-images.githubusercontent.com/35536439/216683306-c3b62492-2566-4541-b35e-ccd5210da2fb.png">

This component should build off of the existing [DisplayTaxonName](https://github.com/inaturalist/iNaturalistReactNative/blob/main/src/components/DisplayTaxonName.js) component. It should display:

- [ ] Optional Common Name (Body1 sizing) - default to scientific name if there is no common name available
- [ ] Optional Scientific Name (Body3 sizing, italic)

Default color should be:
- [ ] #454545 (darkGray)

- [ ] Since names can be long, all text should be able to wrap onto multiple lines for components like ObsListItem
- [ ] We'll also need a prop to limit Common Name to a max of 3 lines for ObsGridItem

See comments below for more implementation details.

**Comment by kueda** [comment]
I'd prefer to a) build off of https://github.com/inaturalist/iNaturalistReactNative/blob/main/src/components/DisplayTaxonName.js, and b) restrict the scope here to deal only with the taxon name. Name display is complicated and we don't want to repeat all the logic involved in deciding what name to show first, whether to show a common name, what common name to show, etc. The additional details only pertain to an observation and pretty much only occur in the ObsListItem so I'm not sure they need to be their own components.

As to *how* we can build off of `<DisplayTaxonName>`, I guess that's up to the developer. One option would be to add a prop to that component so renders two text components. Another might be to abstract some of the name choice logic out and make two components, one for the name in a single line and another for a two-line display.

**Comment by albullington** [comment]
Ok, updated these issues to move date/location/confidence interval into ObsListItem to-dos and to clarify that this should build off the DisplayTaxonName component.

**Comment by Chrischuck** [comment]
I can get something going on this.
