### ISSUE TITLE
ObsGridItem

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#436]
<img width="154" alt="Screen Shot 2023-02-03 at 10 59 12 AM" src="https://user-images.githubusercontent.com/35536439/216685089-bb1a9a73-bbb0-4248-abdc-d3ac9331b863.png">
<img width="281" alt="Screen Shot 2023-02-03 at 11 02 41 AM" src="https://user-images.githubusercontent.com/35536439/216685716-e3bb6c41-3efd-4a27-8488-79ba8efd51fe.png">

This component should display:
- [ ] Taxon photo as the background, at a width/height of 172px and border radius of 15px

Overlaying the taxon photo, this component should display:
- [ ] Top Left: sound icon if the observation has an associated sound
- [ ] Top Right: icon displaying the number of photos in the observation
- [ ] Bottom Left: either the ObsStatus component (#434) or the UploadIcon component (#433) if observation needs to be uploaded to the server
- [ ] Bottom Left: TaxonName component (#435), with color set to white, only the Common Name showing, a maximum of three lines of text, and a maximum text width of 145px. There should be 5px of space above this component (between it and UploadIcon or ObsStatus)

The color for all elements overlaying the taxon photo should be:
- [ ] #FFFFFF (white)

**Comment by Chrischuck** [comment]
i can take a stab at this

**Comment by Chrischuck** [comment]
Is there an example w/o a taxon image?

**Comment by kueda** [comment]
@Chrischuck, this component should never show a taxon image, but it should show an observation photo. Without a photo it should just show a gradient like this:

```css
background: linear-gradient(180deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.5) 100%), #454545;
background-blend-mode: multiply, normal;
border-radius: 15px;
```
