### ISSUE TITLE
Support italic in Whitney

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#449]
The `italic` class doesn't currently work in Tailwind, and we need it to properly render scientific names. I'm not entirely sure what the correct approach is, but maybe we need to follow the [nativewind advice](https://www.nativewind.dev/tailwind/typography/font-family) and model fonts usage off of https://github.com/jsamr/react-native-font-demo.

**Comment by Chrischuck** [comment]
I'm guessing the italic otf files just need to be added to assets and then wired up in the `link-assets-manifest.json`(s).
