### ISSUE TITLE
StandardCamera buttons

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#465]
- [x] Add the `flash` ![flash](https://user-images.githubusercontent.com/22691/218228671-fd5f9fcc-25ae-4cbb-9d71-06587dfafedc.svg) and `flashoff` ![flashoff](https://user-images.githubusercontent.com/22691/218228673-5527fbc9-c4f3-4493-bbbc-a3f78001dd6f.svg) icons to the icon font and the flash button
- [x] Add the flip icon but call it `rotate` ![rotate](https://user-images.githubusercontent.com/22691/218228831-10c9f69e-fc21-4af8-9204-69da565626ac.svg) so it's more reusable
- [x] Style and positions all buttons according to [spec](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=552%3A4920&t=nNPVG46Bv29RJHaR-1) (sizing, opacity for buttons over camera area, shutter style, confirmation button position, etc.)

**Comment by albullington** [comment]
@jtklein added these in #518

**Comment by albullington** [comment]
@angielt are you actively working on this one? trying to figure out what's in progress
