### ISSUE TITLE
Ensure camera area in StandardCamera has no hidden areas

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#466]
At present, I'm pretty sure the CameraView in the StandardCamera actually takes up the full screen and the bars at the top and bottom are just overlaid on top of it. Instead, the CameraView should only be what is visible and the image that it captures should have the aspect ratio of the visible area.

This definitely raises questions about how this area should be sized and how big the top and bottom bars need to be, but I don't have absolute clarity on that yet, so I would pick fixed sizes for the top and bottom bars and let the camera fill the rest of the space.

**Comment by Chrischuck** [comment]
I can make a pr for this

**Comment by albullington** [comment]
Closed via #513
