### ISSUE TITLE
Tapping on the background of the AddEvidenceModal doesn't dismiss the modal in iOS

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#468]
For me, the only way I can dismiss the modal in iOS is tapping the "X" button at the center. I can dismiss it by tapping on any of the background area in Android, and I think it should work that way on both platforms.

**Comment by Chrischuck** [comment]
@kueda are you using a simulator for iOS? If so, it _might_ work on a physical device based on this [issue](https://github.com/gorhom/react-native-bottom-sheet/issues/1114)

comments from this [thread](https://github.com/gorhom/react-native-bottom-sheet/issues/1165) suggest using `react-native-gesture-handler`

But I'm not even sure if it's worth it.

**Comment by kueda** [comment]
Sorry, just seeing this, @Chrischuck. You're probably right. I'm usually using a simulator, but I'll try on my iPad.

**Comment by albullington** [comment]
I believe this was fixed in [this commit](https://github.com/inaturalist/iNaturalistReactNative/pull/510/commits/dfc4105805b1c65f31eb822b1bbf95a4a918513b). Needed different styling to make the backdrop tap work correctly.
