### ISSUE TITLE
Confirmation bottom sheet when canceling out of StandardCamera

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#471]
We want to make sure the user knows they're throwing away their photographic work when they leave the StandardCamera, so

When the user

- [x] Taps the close button
- [ ] or taps the system back button in Android

Show a bottom sheet

- [ ] with the title "DISCARD PHOTOS?"
- [ ] body of "By exiting, your photos will not be saved"
- [ ] has a "Cancel" button that closes the bottom sheet and returns the user to the StandardCamera
- [ ] has a "Discard" button that does what the close button would have done

<img width="390" alt="Camera - Sheet - Discard Photos" src="https://user-images.githubusercontent.com/22691/218231350-3b4c934a-e210-4c1b-95d4-a332d08a9d2b.png">

FWIW, I'm still a bit confused if photos really will be discarded at this point, but we probably want some kind of modal blocker in this situation, so we might as well build out the bottom sheet.

**Comment by Chrischuck** [comment]
I can get a pr up for this

**Comment by albullington** [comment]
Closed by #516
