### ISSUE TITLE
Hold to show delete button in PhotoPreview

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#473]
Currently the PhotoPreview in the StandardCamera has delete buttons visible all the time. Instead, we'd like to show them on hold / long-press.

- [x] Remove existing delete buttons from PhotoPreview
- [x] Add the `trash` icon to the icon font
- [x] When the user long-presses on a thumbnail, show delete buttons over all the thumbnails; buttons should be translucent to show the photo behind them but they should cover the whole thumbnail so the entire area is tappable
- [x] When the user taps a delete button, delete the photo immediately
- [x] Tapping anywhere other than one of the delete buttons should exit deletion mode, i.e. the buttons disappear and the thumbnails appear as they did before

Here's what the thumbnails look like in delete mode:

<img width="300" alt="Screen Shot 2023-02-10 at 5 47 34 PM" src="https://user-images.githubusercontent.com/22691/218232265-74c1a4cd-e151-438c-b789-c06b50754572.png">

**Comment by Chrischuck** [comment]
I can work on this
