### ISSUE TITLE
GroupPhotos UI

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#480]
Depends on
- [x] #469

Integration issue for GroupPhotos UI

- [x] #481
- [x] Replace existing header with a `<ContextHeader>`
- [x] "Group photos into observations– make sure there is only one species per observation" should be Body2 and be a header to the FlatList (or FlashList) of photos
- [x] Replace FlatList with FlashList (one could potentially import a large number of photos; is there a cap?)
- [x] #482
- [x] Use GroupPhotoObservations or whatever comes out of #482
- [x] #484
- [x] Add a StickyToolbar with a single button that says "IMPORT X OBSERVATIONS" where X is the number of observations; should take the user to ObsEdit (equivalent of current "Next" button)
- [x] #485
- [x] Add a FloatingToolbar with group, split, and delete buttons
- [x] group button should group selected observations into a single observation
- [x] split button should ungroup all selected observations so all their photos are separate observations
- [x] delete button should remove the selected observations and delete selected photo records
- [x] FloatingToolbar should only appear when you've selected an observation, should animate in from behind the StickyToolbar
- [x] Breakpoints change the number of columns and the size of the grid items (size needs to be calculated based on screen size):
  - [x] `sm`: 1 col
  - [x] `md`: 2 col
  - [x] `lg`: 2 col
  - [x] `xl`: 4 col
  - [x] `2xl`: 6 col

**Comment by Chrischuck** [comment]
I can get a PR utilizing the floating action bar and sticky toolbar components
