### ISSUE TITLE
ContextHeader component

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#481]
This is a nav header for views that need an additional context that is visible regardless of scroll. If there's a way to plug this into react-navigation that would be awesome, but I'm not seeing one on a cursory glance. This might need to be implemented as a full view wrapper like `<ScrollWithFooter>` or something.

Props:
- [ ] `title`: string
- [ ] `subtitle`: string
- [ ] `onBack`: function that gets fired when the back button is pressed

Visuals:
- [x] Back button
- [ ] Start-aligned Heading1 `title`
- [ ] Start-aligned Heading4 `subtitle`
- [ ] Casts a shadow similar to `box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.25);`
- [x] sticks to the top of the screen when used with a ScrollView

<img width="683" alt="Screen Shot 2023-02-13 at 4 21 51 PM" src="https://user-images.githubusercontent.com/22691/218605902-01344fc4-8f2c-4866-97b5-aad8baf297b8.png">

Other TODOs:
- [ ] Put it in the UI library

**Comment by Chrischuck** [comment]
had to dig a bit, but eventually found [this](https://reactnavigation.org/docs/native-stack-navigator#header) in the docs. Pretty small pr to get this done

**Comment by albullington** [comment]
Closed via #508
