### ISSUE TITLE
GroupPhotosObservation

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#482]
Depends on:
- [x] #483

This is going to be very similar to `<ObsGridItem>`, and it might actually be best to do this as a modification of that 
component, or maybe it's better to keep it simple and separate from that more complicated component, not sure, but here are the rough requirements:

Props
- [ ] photos: array of photo objects represented by this item
- [x] selected: boolean for whether or not this "observation" is selected
- [ ] `width:` int, width in pixels

Visual
- [x] 15px border radius
- [x] circular checkbox in top-end (`selected` controls checked state) with shadow (this might need to be its own component like CircularCheckbox or something; hoping it can be rendered with CSS and the existing `checkmark` icon)
- [x] `<PhotoCount />` in bottom-end
- [ ] width and height should be `width` or 100%

<img width="525" alt="Screen Shot 2023-02-13 at 5 27 04 PM" src="https://user-images.githubusercontent.com/22691/218614313-b0e2eb34-965b-4b90-9e77-a8931abac8c2.png">

**Comment by Chrischuck** [comment]
Seems like an easy lift on top of the `ObsPreviewImage` component, which `ObsGridItem` just feeds data to anyway.

I can make a pr and see if it fits the requirements.

**Comment by albullington** [comment]
Closed via #525
