### ISSUE TITLE
FloatingToolbar component

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#485]
This is kind of like a [floating action button](https://m3.material.io/components/floating-action-button/overview) but with multiple buttons in one floating element:

<img width="540" alt="Screen Shot 2023-02-13 at 5 46 15 PM" src="https://user-images.githubusercontent.com/22691/218617187-e8186d7f-2072-464c-8b78-b184d24abb93.png">

Should just render the children as contents, not necessarily the buttons in that mock.

Props
- [ ] `position`: string, one of `topStart`, `topEnd`, `bottomStart`, `bottomEnd` to set the position of toolbar
- [ ] `marginX`: int, margin in the x dimension
- [ ] `marginY`: int, margin in the y dimension

Visuals:
- [ ] Should float above other elements on the screen
- [ ] Casts a shadow like `box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.25);`
- [ ] White background
- [ ] Should anchor to screen position specified in `position`

**Comment by Chrischuck** [comment]
Shouldn't be too hard to get this done.
