### ISSUE TITLE
Rename and re-upload icons

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#487]
We're accumulating icons with names that have extraneous stuff like `icon-`, overly specified names like `noevidence`, nonsensical names like `vector-stroke`, and most need to be re-uploaded on a square 24x24x document.

Each icon should
- [ ] Have its own 24x24 px SVG file
- [ ] Be named with just its name, e.g. `pencil.svg`, not `icn-pencil.svg` or `pencil-icon.svg`
- [ ] Have no `fill-rule: evenodd` styles
- [ ] Be checked into this repo (under assets/fonts?)

On fontastic
- [ ] Delete all entries with bad names and re-upload the new SVG files

...orrr maybe write a script to generate a font from our icons in this repo so anyone can do it without relying on fontastic?

In the code
- [ ] Refactor to use the new icon names
- [ ] Ensure there are no broken icons

**Comment by kueda** [comment]
Now I'm kind of wondering if fonts should be checked into their own repo...

**Comment by abhasinat** [comment]
super helpful, thanks for this guidance ken-ichi.
