### ISSUE TITLE
AddObsButton styling

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#500]
According to the design specs [here](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=333%3A541&t=ktTRo97Q9YUxm9i3-4) the AddObsButton component should be updated with the following changes:

- [x] Default size of 69x69
- [x] Replace the current "plus" icon with the correct version after #487 
- [x] The plus icon in the centre should have a size of 31x31 without any padding or margin. (Thereby leaving a 19px distance from the edge of icon to edge of button).
- [x] Add a drop shadow to the button: `box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.25)`
- [x] Add a linear gradient to the button's background color: `background: linear-gradient(156.95deg, #77B300 0%, #297F87 194.7%, #297F87 194.7%);`

**Comment by Chrischuck** [comment]
I can put something together for this
