### ISSUE TITLE
DateDisplay styling

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#501]
Some more changes needed following the current design [specs](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=315%3A343&t=ktTRo97Q9YUxm9i3-4):

- [ ] Add the `date` icon to the icon font, after #518  
- [ ] Replace MaterialIcon with the above icon, size 13x13

**Comment by Chrischuck** [comment]
I can make a pr for this
