### ISSUE TITLE
ObservationLocation styling

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#502]
Some more changes needed following the current design [specs](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=315%3A340&t=ktTRo97Q9YUxm9i3-4:

- [ ] Add the `location` icon to the icon font, after #518 
- [ ] Replace MaterialIcon with the above icon, size 13x13

**Comment by Chrischuck** [comment]
Can make this change
