### ISSUE TITLE
Safe Area View for group photos header

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#532]
**Describe the bug**
Group Photos could use a safe area view or some way of padding the header on iPhone. It's a bit too close to the top of the screen.

**Screenshots**
<img width="389" alt="Screen Shot 2023-03-14 at 12 43 08 PM" src="https://user-images.githubusercontent.com/35536439/225118984-8d2b0646-6bf7-4397-8d87-cafb3795eebf.png">

**Context (please complete the following information):**
 - Device: iPhone

**Comment by Chrischuck** [comment]
I think there's a similar issue on the obslist header
<img width="330" alt="Screenshot 2023-03-14 at 6 36 07 PM" src="https://user-images.githubusercontent.com/13311268/225165512-4f24df77-38fa-4f41-8a54-2d88c9bc8f77.png">

I can take a look at it

**Comment by albullington** [comment]
Closed in #537
