### ISSUE TITLE
UploadStatus progress circle is not synced to actual upload progress

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#534]
**Describe the bug**
The `UploadStatus` progress circle should display real upload progress, instead of an approximation. This means we'll probably need a way for the realm `Observation.uploadObservation` method to update the rest of the app on individual upload status. Right now, how we want to display progress is open to interpretation, but it might be something like:

1. Observation uploaded without evidence: 0.33 percent progress
2. Observation photos uploaded: 0.5 percent progress
3. Observation sounds uploaded: 0.66 progress

**Screenshots**
<img width="276" alt="Screen Shot 2023-03-14 at 1 56 14 PM" src="https://user-images.githubusercontent.com/35536439/225134251-d5c41406-c7c1-46b9-bfe7-5841c920caa4.png">

**Comment by Chrischuck** [comment]
I think some of the logic from #529 can be transferred over. I also think the progress circle is out of sync w/ the sync button.

I can get a spike pr going that we can colab from there.

**Comment by albullington** [comment]
Closed in #538
