### ISSUE TITLE
Improve performance of MyObservations

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#535]
This one is a bit experimental. There are some things on MyObservations that seem particularly slow to render, like switching between gridview and listview. The goal of this issue is to track down anything hindering performance (i.e. unnecessary rerenders, using FlatList instead of a more optimized list, etc.) and make everything feel less laggy.

**Comment by Chrischuck** [comment]
I can take a look at adding flashlist to MyObservations
