### ISSUE TITLE
Back button on species info does not go back to AddId

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#541]
With the following navigation:

AddObsButton -> Camera -> Take a photo -> ObsEdit -> AddID -> any taxon info

If you then press the back button the app goes back to the observation list, and not back to observation flow (AddId) and the observation seems to be discarded as well (at least not reachable anymore from the observation list).

**Comment by Chrischuck** [comment]
I think this would be fixed by moving everything out of the stack navigator and into the tab navigator. I wrote about it briefly in #528 

But looks like when you press back on AddId (part of stack nav) it goes backwards to the "Home" screen which defaults to the Observation list tab.

**Comment by Chrischuck** [comment]
@jtklein should the taxon page have the bottom tabs to begin with?

**Comment by jtklein** [comment]
The taxon detail page does have a bottom tabs component in the designs currently, it is not the final design version yet though.
