### ISSUE TITLE
Upload Status UI is not updating while uploading

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#543]
When uploading multiple observations the Upload Status for each individual observation is not updating, and not animated. See first half of this screen recording.

https://user-images.githubusercontent.com/17345891/225449721-60c85ba8-56b2-400c-b373-5f545643f2a5.mp4

**Comment by Chrischuck** [comment]
@jtklein is this still an issue w/ latest main?

**Comment by Chrischuck** [comment]
@jtklein ahh I see, the animation code is in there, just commented out. i think the current icon has the dots and the arrow in it, but it needs to be updated (or a new icon added) with just the dots so it can spin freely from the arrow.

**Comment by kueda** [comment]
I'm not sure I can still replicate this. Can you, @jtklein?
