### ISSUE TITLE
Scroll state is lost when uploading observations

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#544]
When uploading observations and then scrolling in between the upload of two observations, the scroll position is lost and jumps back to the top of the list. See second half of this screen recording.

https://user-images.githubusercontent.com/17345891/225450078-18dd0e90-e63d-4dd9-b3c4-6a8f8edaa3a1.mp4

**Comment by albullington** [comment]
I haven't been able to replicate this issue. Curious if anyone else can or if this is already fixed.

**Comment by kueda** [comment]
@jtklein please see if you can still replicate it. If you can, maybe try and post more detailed repro conditions?

**Comment by jtklein** [comment]
I can no longer replicate this on the same device the report is from.
