### ISSUE TITLE
Sync button does not update observation list immediately

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#546]
When hitting the sync button, some details are not refreshed when tapped shortly after their creation in the observations shown in the list. I did see new comments and identifications not changing the count shown. If I reload the website those changes are already shown, e.g. in the notifications icon. In the app it took a few minutes for the changes to appear.

To replicate:
1. Open app to observation list.
2. Add a comment/identification to one of the observations on a different client (I have tested as a different user)
3. Tap the refresh button shortly after creation, the count is not updated

**Comment by Chrischuck** [comment]
Looks like the delay is coming from `inatjs.observations.search`. I don't think there's any cache layer on the client side of things.

Could be an api issue? Are both clients pinging the same server and endpoint?

**Comment by jtklein** [comment]
I can not reproduce this anymore, closing it now.
