### ISSUE TITLE
Scrolling to the top of MyObservations doesn't always bring back Header

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#560]
A user should be able to scroll to the top and see both the Header and Toolbar. Currently, scrolling to the top is inconsistent -- sometimes it shows the Header & Toolbar, sometimes it only shows the Toolbar, and sometimes it shows half of the header (the username, but not the Welcome back line of text).

<img width="377" alt="Screenshot 2023-03-30 at 1 59 59 PM" src="https://user-images.githubusercontent.com/35536439/228963309-1c73599e-9aa0-42e4-8cd8-07e46229e728.png">

**Comment by kueda** [comment]
This is actually working pretty well for me, @albullington. Would you try and replicate again or close?

**Comment by albullington** [comment]
@kueda included a screen recording with repro conditions. For the original issue here, the main thing that I'm seeing is that when a user scrolls to the top, sometimes the whole header is displayed, but sometimes the "Welcome back" text is cut off.

This screen recording also highlights a separate (maybe related) issue, that when a user scrolls down and loads more observations, the top part of the header disappears suddenly so only the toolbar is displayed.

https://github.com/inaturalist/iNaturalistReactNative/assets/35536439/6de931cc-9c32-47a6-ac85-b11451dbb063

So things to fix here are:

- [ ] Welcome back text is occasionally cut off when scrolling up on MyObservations
- [ ] Top half of header disappears suddenly when user pulls down to load more observations

**Comment by kueda** [comment]
What device are you using? I'm not seeing that on an iPad Air (5th gen) or an iPhone SE, so maybe it has to do with using a device with a camera in the screen area?

**Comment by albullington** [comment]
This is on iPhone 15 Pro -- maybe has something to do with the SafeAreaView, if you're not seeing it on the other iOS devices
