### ISSUE TITLE
LoginSheet appears below tab navigation

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#561]
This is a known issue when using bottom sheet combined with a tab navigator. It looks like we might be able to use BottomSheetModal instead as a workaround. There's a long thread about this [here](https://github.com/gorhom/react-native-bottom-sheet/issues/249).

- [ ] LoginSheet should appear above Tab Navigation bar so the bar is no longer visible

![IMG_74580788E2F0-1](https://user-images.githubusercontent.com/35536439/228979212-ed226d39-23a9-4c89-a103-ecfb6036af6b.jpeg)

**Comment by flbn** [comment]
this looks like it should be closed? potentially by https://github.com/inaturalist/iNaturalistReactNative/commit/01099be1ce269cca428e158e4708bcbcf7322492

**Comment by jtklein** [comment]
Correct, thanks.
