### ISSUE TITLE
UploadStatus: excessive callbacks

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#571]
**Describe the bug**
When navigating from MyObservations to a new ObsEdit screen with no evidence, there is sometimes a console warning. According to the stack trace, it looks like this has to do with the animation in UploadStatus, which is likely still rendering after a user leaves the screen.

`WARN  Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code`

**Screenshots**
<img width="367" alt="Screenshot 2023-04-14 at 3 08 47 PM" src="https://user-images.githubusercontent.com/35536439/232163016-e5eb19fa-649c-422f-804d-b98342c317cb.png">
<img width="371" alt="Screenshot 2023-04-14 at 3 09 12 PM" src="https://user-images.githubusercontent.com/35536439/232163063-3b05b611-71df-45a8-a40c-06240c15f50a.png">

**Additional context**
I believe Ken-ichi experienced the same bug with [slightly different repro steps](https://github.com/inaturalist/iNaturalistReactNative/pull/570#pullrequestreview-1384426546). Fwiw, we're both trying this from the `obs-edit-bottom-sheets` branch, but I think it's worth an issue since it seems to be coming from `UploadStatus`, not any of the new code in this branch.

**Comment by Chrischuck** [comment]
I can take a look at this

**Comment by albullington** [comment]
Haven't been able to replicate this in [v0.19.0+67](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.19.0%2B67)
