### ISSUE TITLE
Body1, List1, and List2 font weights too light in Android

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#576]
Specifically, the species name in a list item on My Observations is lighter in Android than it is in iOS. They should have the same weight. Android font weights should match what we show in iOS. Here's a screenshot:

<img width="796" alt="Screen Shot 2023-04-20 at 12 19 38 PM" src="https://user-images.githubusercontent.com/22691/233466096-b5b86ec6-19de-4121-a76f-f552399d7d02.png">

**Comment by albullington** [comment]
Closed by #703
