### ISSUE TITLE
Sign in with Apple

### ISSUE THREAD

**Issue by flbn** [inaturalist/iNaturalistReactNative#583]
probably a ways to go before hitting this but the existing app allowed me to sign up with my Apple account - which, is proving to be difficult to log into the current build as the option is missing. wondering what the plan is for this? i think i can get away with creating a new account from scratch just for dev

**Comment by kueda** [comment]
This is a part of the plan so I'll leave this open, but I strongly advice you *not* to depend on 3rd party sign in. We don't have control over third parties so if they decide to cancel their service or just cut us off from it, you're going to be cut off from your iNat account. Also, if you're planning on making some code contributions, you might want to make a test account anyway.

**Comment by kueda** [comment]
Ok, revised spec

- [ ] Research whether people are still using 3rd party sign in on the web even though we forced everyone to have and confirm an email address (may need to collaborate with folks in the web circle)
- [ ] If fewer than 1% of web users are using 3rd party sign in, we will not support it in this mobile app and you can close this issue
- [ ] If >= 1% of web users are using 3rd party sign in, proceed to support Sign in with Apple
- [ ] Do not support account *creation* via 3rd party

**Comment by kueda** [comment]
This might be handled by [#1887](https://github.com/inaturalist/iNaturalistReactNative/issues/1887), so let's deal with that first.
