### ISSUE TITLE
Log in bottom sheet with two close buttons

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#585]
**Describe the bug**
The bottom sheet "Please log in" has two "X" Close buttons.

**To Reproduce**
1. When logged out of an iNat account, with no saved observations
3. Create a new observation
4. Press on "Upload 1 observation"
5. See wrong UI in bottom sheet

**Expected behavior**
The one X close button that is situated above the title "Please log in" and X close button should not be there.

**Screenshots**
![IMG_7679](https://user-images.githubusercontent.com/17345891/234217224-c54927b1-aff6-448f-9522-0439e10b66d7.PNG)

**Context (please complete the following information):**
 - Device: [iPhone7]

**Comment by JENNIFER-E** [comment]
I like to work on this, can you assign me please?

**Comment by albullington** [comment]
Closed via #638
