### ISSUE TITLE
MyObservations grid view gets screwed up when you rotate the device

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#586]

**Comment by kueda** [comment]
FYI, this applies to tablets where we allow rotation on MyObservation. It's supposed to have 4 columns in portrait and 6 columns in landscape, which works on first load, but when you rotate the device the number of columsn doesn't change and they end up being two widely spaced or all smushed together:

![IMG_0104](https://github.com/inaturalist/iNaturalistReactNative/assets/22691/6afb3b50-f7a1-4068-ad50-58ace857c670)
![IMG_0105](https://github.com/inaturalist/iNaturalistReactNative/assets/22691/7a0fafc6-e5f2-41c9-bd61-a1ac49c7e060)
