### ISSUE TITLE
MediaViewer UI for landscape mode

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#597]
We need the MediaViewer screen to rotate to landscape mode on both tablet & non-tablet devices. The best way to do this is by using the `useUnlockScreen( )` hook, like we're doing in the StandardCamera.

<img width="713" alt="Screenshot 2023-04-26 at 11 53 41 AM" src="https://user-images.githubusercontent.com/35536439/234674884-a289949e-e820-480a-8a5e-ae86c5ce2397.png">

**Comment by Chrischuck** [comment]
I can make a pr for this

**Comment by Chrischuck** [comment]
@jtklein Having an issue starting up android emulator and can't work on this till I get that going. Can't dedicate a ton of time to fix it and will take my name off this for now :(

**Comment by albullington** [comment]
closed by PR #608
