### ISSUE TITLE
Login flow

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#6]
Added current wireframes (3/29/22):

**Login**
- [x] Log in with email address and password
- [x] Display error messages from server for wrong email, wrong password

<img width="210" alt="Screen Shot 2022-03-29 at 5 22 30 PM" src="https://user-images.githubusercontent.com/35536439/160726968-ce16cdde-1863-44e9-b0bc-b8768d3f9fd9.png">

**Forgot password**
- [x] Show iNat forgot password page in browser view
<img width="433" alt="Screen Shot 2022-03-29 at 5 23 57 PM" src="https://user-images.githubusercontent.com/35536439/160727084-a1843dbd-fed3-46fe-8caa-3f33c001bbe5.png">

**Log out**
- [x] Let user log out of their account (this doesn't have designs as of 3/29/22)

**Comment by kueda** [comment]
Yaron got basic log in / log out functionality working in https://github.com/inaturalist/iNaturalistReactNative/pull/44. We still need the "Forgot password?" screen and higher fidelity UI matching the designs above.
