### ISSUE TITLE
ERROR Warning: Cannot update a component (`MyObservationsContainer`) while rendering a different component (`ObsDetails`)

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#606]
This came up during #574:
Happens after getting an update about an unviewed comment and tapping on that observation:

```
 ERROR  Warning: Cannot update a component (`MyObservationsContainer`) while rendering a different component (`ObsDetails`). To locate the bad setState() call inside `ObsDetails`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    in ObsDetails (created by SceneView)
```

When I got to ObsDetails, the new comment did not appear (seems inconsistent).

The problematic `setState` is happening in this call: `setObservationList( [...collection] );` in a listener here `localObservations.addListener`.

In ObsDetail we are updating the observation in realm which triggers this listener that is attached in MyObs Container.

**Comment by Chrischuck** [comment]
Think I can give this a shot
