### ISSUE TITLE
Importing or sharing a photo w/ app does not clear the "missing evidence"  warning

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#619]
**Describe the bug**
When you land on ObsEdit after importing a photo or sharing a photo from outside the app, the "Missing Evidence" warning still appears even though there is media evidence.

**To Reproduce**
1. Start a new observation by importing a photo
2. When you land on ObsEdit, the photo appears, but the red exclamation point triangle appears next to the "EVIDENCE" header
3. When you try to save, you get the "MISSING EVIDENCE" bottom sheet

Sharing a photo with iNat from a gallery app has the same effect.

**Expected behavior**
These warnings should not appear when there is media evidence, no matter where that evidence comes from.

**Context (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 12
 - App version: 0.4.0 (44)

Seems restricted to Android

**Comment by albullington** [comment]
Closed by #704
