### ISSUE TITLE
Investigate battery usage / return to sleepiness

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#631]
The app seemed to consume a ton of battery for me this weekend, and it seems to stay awake for long periods of time, especially after uploading, so we should investigate to make sure that whenever we tell the app to stay away (e.g. during upload) that we always tell it to stop doing that when upload ends, when the app is forcibly put in the background, when exceptions get raised during upload, etc.

**Comment by albullington** [comment]
I think this needs further investigation, but here's the main overview I found of our energy usage (XCode -> Debug -> Energy Report):

![Image](https://github.com/inaturalist/iNaturalistReactNative/assets/35536439/f4b82fcd-fea2-4cab-842d-95412ea9fa5f)

This tells us our overall energy usage in the app is fairly high. There are a number of things we can look into, including:

- number of unnecessary rerenders
- batching network requests
- making sure we're only using system resources (like data about whether a user is online or what their current location is) when absolutely necessary

High CPU utilization seems to be the main thing associated with draining battery. I used the CPU Time Profile tool in XCode to run through a typical upload flow (take a photo, save with ObsEdit, upload in batch on MyObservations). The last section on the right represents 100-120% CPU usage during the batch uploads, and there are a few other places in that flow where CPU usage spikes. XCode suggests that 20% CPU usage is considered high and will drain battery faster.

![Image](https://github.com/inaturalist/iNaturalistReactNative/assets/35536439/a9f196a6-93b4-4dff-9c46-6ce3536a88d7)

So I might recommend that we split performance / energy improvements into new issues & focus on trying to improve CPU usage on each screen in the Observation Loop flow.

I started with a few PRs to reduce our usage on Context/Provider for global state, which adds significantly to the number of UI renders: [#879](https://github.com/inaturalist/iNaturalistReactNative/pull/879), [#844](https://github.com/inaturalist/iNaturalistReactNative/pull/844), and [#845](https://github.com/inaturalist/iNaturalistReactNative/pull/845).
