### ISSUE TITLE
Accuracy circle and obscuration cell for ObsDetail map

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#655]
Pending feedback from @abhasinat re: design, but IMO it would be ok to mimic the way the Android app behaves here, i.e. with translucent polygons.

**Comment by abhasinat** [comment]
Heads up- these both now have designs in the Figma file, on the Keystone Screens Page, in the Obs Detail Section. I took a look at android and used it as inspiration. Main change was to make the obscured point a new icon, and add text that expressed what that point is both on obs detail and in the map view.

Here's a preview:
<img width="877" alt="image" src="https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/c256c036-cfc8-4b82-914a-ee82a1f0e928">
