### ISSUE TITLE
Can't share photos with app if permission not granted

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#659]
**Describe the bug**
If the app does not have permission to access photos and you share a photo with the app, the import fails silently on Android and crashes the app in iOS.

**To Reproduce**
1. Remove the app's permission to access photos ("Files and media" in Android, "ALLOW PHOTO ACCESS" in iOS)
2. Go to an external photo app like Apple or Google Photos and share a photo with our app
3. When you land in our app, nothing happens in Android, and the app crashes in iOS

**Expected behavior**
The app should tell the user that the permission is required to import photos and then ask the user for the permission.

**Context (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 12
 - App version: 0.5.1 (46)

**Additional context**
IMO an alert would do the trick for now, e.g.

Title: Access to photos required
Body: You must grant access to your photos if you want to share a photo with this app.
Buttons: Cancel (closes the alert), OK (asks the user for the photo permission)

**Comment by albullington** [comment]
I haven't been able to replicate this on my iPhone or Android devices -- sharing seems to be working for me, even with photo permissions off. I wonder if this is specific to Android 12 and lower?

The only thing I'm seeing here is that Android sharing doesn't ever seem to fill in photo location data on ObsEdit.

**Comment by budowski** [comment]
Haven't been able to recreate this as well (tried on Android 12 emulator, Android 14 device and iOS)

**Comment by kueda** [comment]
Yeah, I can't replicate on iOS or Android either. Guess it somehow got fixed. @albullington I suspect the Android coordinate thing might have to do with differing access to photo location metadata between photos that are on the device and photos in the cloud. When I share a photo with coordinates on my device from Google Photos to iNat, I get the photo and the coordinates, but it doesn't work for photos that are not on device. I believe this is a limitation we can't get around (happens in the native Android app too).
