### ISSUE TITLE
Signup flow

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#69]
A user should be able to create an iNaturalist account using the mobile app. From the login screen, they can tap to create an account. Functionality:

- [ ] Email input field
- [ ] Consent checkboxes
- [ ] Username and password fields
- [ ] License photo checkbox
- [ ] Terms of service and privacy policy links and checkbox
- [ ] Create account button
- [ ] Tap to open email client for confirmation email / link
- [ ] Navigation: allow user to skip signup or return to the login screen
- [ ] Keyboard: make sure the keyboard is not covering relevant elements on the screen, like create account button

<img width="848" alt="Screen Shot 2022-03-29 at 5 17 36 PM" src="https://user-images.githubusercontent.com/35536439/160726584-37a518b5-ae2f-47ff-b8e2-e732c6453654.png">

**Comment by kueda** [comment]
We're going to go with the web sign up form in a web view... but we haven't figured out the flow yet, so I'm just going to close this for now and open a new issue when we've figured that out.
