### ISSUE TITLE
Observation reappears after deletion

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#694]
Delete one observation from the main screen, and after a short while the observation reappears on the main screen.

Screen recording for the first observation in the list:

https://github.com/inaturalist/iNaturalistReactNative/assets/17345891/2b66b635-0b76-4d29-93d4-5649524c2955

**Comment by jtklein** [comment]
This seems to be flaky though and does not happen every time I delete an observation.

**Comment by kueda** [comment]
FWIW, I *think* this might be related to caching in React Query, the app fetches your observation w/ React Query, you delete an observation and return to My Observations, which tries to fetch your obs again but it hits the React Query cache that still contains your deleted observation.

**Comment by kueda** [comment]
@jtklein why did you close this? Did you test and could not replicate, or do you think it was fixed by a specific commit?

**Comment by kueda** [comment]
FWIW, this is still happening for me in [v0.18.1+66](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.18.1%2B66) (Pixel 8, Android 13).

**Comment by albullington** [comment]
So far I'm not able to replicate this in [v0.19.0+67](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.19.0%2B67) (iPhone 15 Pro, iOS 17)

**Comment by kueda** [comment]
I can still replicate it with these steps on a simulated iPhone 15 Pro (iOS 17.2)

1. Sign in
2. Make a new obs without evidence
3. Tap the upload button the toolbar to upload, allow upload to complete
4. Delete the observation you just created
5. Back on My Observations, tap the sync button
6. The obs you deleted re-appears

**Comment by jtklein** [comment]
I could not replicate this using the steps laid out above on a simulator iPhone 15 Pro (iOS 17.2) in [0.21.1](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.21.1%2B70). So, I assign it back to the creator.

**Comment by kueda** [comment]
FWIW, I can still replicate this on device and in a simulator, but you have to sync quickly after deletion. I have a fix ready in #1240
