### ISSUE TITLE
Signup modals, privacy and terms screens

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#70]
There are a lot of modals and text screens related to the signup flow which need to be built and included in relevant parts of the flow:

- [ ] Privacy policy screen
- [ ] Terms of service screen
- [ ] Explanation of why a user needs an iNat account
- [ ] Explanation modal for licensing photos
- [ ] Explanation modal for storing PII

<img width="1106" alt="Screen Shot 2022-03-29 at 5 25 34 PM" src="https://user-images.githubusercontent.com/35536439/160727224-6539b69c-41b7-46f2-be52-0c19513ce0fd.png">

**Comment by kueda** [comment]
I'm going to close this because we decided to handle sign up in a webview, so the work we need to do in the app will be different (setting up a webview, detecting end of signup process by url, etc).
