### ISSUE TITLE
Android location doesn't resolve in location picker

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#710]
On the Android device I tested this it never resolves with a location when pressing the "My location" button. The default timeout for `Geolocation.getCurrentPosition` is 10 minutes. I think it makes sense to use a smaller timeout when the call comes fom pressing the "current location" button. But this is not part of the PR spec, so we can also make a new issue for this.

_Originally posted by @jtklein in https://github.com/inaturalist/iNaturalistReactNative/issues/692#issuecomment-1625574916_

**Comment by kueda** [comment]
This may have been addressed in #727 but I think it was fixed earlier.
