### ISSUE TITLE
ActivityList doesn't update after Agree with ID

### ISSUE THREAD

**Issue by angielt** [inaturalist/iNaturalistReactNative#719]
**Describe the bug**
When agreeing on an id the ActivityList in ObsDetails does not change to update the previous IDs in the list to accompany the new ID without pressing back and opening the observation again. 

**To Reproduce**
1. Press into an existing observation with existing IDs
2. Tap the Agree with ID button 
3. Agree with ID bottom sheet should appear. Press agree
4. When the bottom sheet closes, a new Id should appear but the Agree with ID button that was pressed earlier is still there as well.

**Expected behavior**
The Agree with ID button should disappear if the user agreed with the id already without having to press back and into the observation again. Other elements in the identification like ID Withdrawn should also update accordingly. 

**Additional context**
Possibly due to some ActivityItems in the ActivityList not rerendering because their position in the list not changing.

**Comment by kueda** [comment]
FYI, this is still happening for me on Explore, i.e. when viewing someone else's observation. Is that expected, @albullington?

**Comment by albullington** [comment]
Possibly, I hadn't considered the flow from Explore, only from MyObservations. Do you have a repro example? The first one I tried gives a "cannot agree with ID" error but not sure if you're seeing something different.
