### ISSUE TITLE
Following list screen

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#72]
From a user profile, a user should be able to tap into a following list and a followers list screen. These screens display:

- [ ] username
- [ ] user icon
- [ ] total number of observations for a given user
- [ ] total number of followers / people following

This functionality exists in the API, but I'm not sure it's currently accessible via inatjs due to this issue ([#59](https://github.com/inaturalist/inaturalistjs/issues/59))

<img width="679" alt="Screen Shot 2022-03-29 at 5 33 08 PM" src="https://user-images.githubusercontent.com/35536439/160727854-df3ea412-ffef-46ee-a46c-146bbe595ffc.png">

**Comment by kueda** [comment]
Tabling pending updated designs.
