### ISSUE TITLE
Notifications screen

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#73]
A user can tap into notifications on the tab bar to view notifications and messages. This is what notifications should look like, with as much of this detail as exists in the current API.

<img width="199" alt="Screen Shot 2022-03-29 at 5 39 20 PM" src="https://user-images.githubusercontent.com/35536439/160728329-ca022d40-5774-4970-8e7f-3aa57b4f7b8b.png">

**Comment by kueda** [comment]
IMO we should work from a design that works with the API we have.
