### ISSUE TITLE
Zoom snaps back after tapping shutter

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#736]
**Describe the bug**
Zoom level on StandardCamera snaps back to the default after tapping the shutter button on Android.

**To Reproduce**
1. Go to the StandardCamera
2. Zoom in by pinching
3. Tap the shutter button
4. The zoom level snaps back to the default

**Expected behavior**
Tapping the shutter should not affect the zoom level.

**Context (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 12
 - App version: 0.9.1 (52)

**Additional context**
This only happens in Android, and does *not* happen when you tap the "1x" zoom button. In fact, when you tap the "1x" zoom button first, it doesn't happen after you pinch to zoom either.

**Comment by jtklein** [comment]
This should be fixed, correct?
