### ISSUE TITLE
Explore Filters

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#751]
Instead of a placeholder screen, we need to build out the Explore Filters screen and filter API calls accordingly.

The design specs for this screen are [here](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?type=design&node-id=1406-11405&mode=design&t=pIggNZbSl0Gy2Jm3-0).

**Comment by kueda** [comment]
Superseded by #886
