### ISSUE TITLE
Need thumbnail or photo for identifications on ObsEdit passed from AR Camera

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#752]
Right now, when a user takes a photo in the AR Camera and moves to the ObsEdit screen, they can see the scientific name only. They can't see a common name, and they can't see an identification photo.

We'll need to think about what to display here and whether we need more data stored in the taxonomy files, like photo URLs, or whether we can fetch this data with an API call or a caching strategy. We'll likely want to load common names into Realm similar to how we're [handling them in Seek](https://github.com/inaturalist/SeekReactNative/blob/main/utility/commonNamesHelpers.js).

For now, we should use something simple like the linear gradient we use on MyObservations to at least let a user see the skeleton of where a taxon photo should be on ObsEdit.

**Comment by angielt** [comment]
Fixed from another issue  #1067  . An IconicTaxonIcon with unknown shows up as a skeleton of where the taxon photo should be, similar to when there is no photo in an ObsListItem in MyObservations.
