### ISSUE TITLE
Empty screen flashing on first load of MyObservations

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#756]
**Describe the bug**
Every first load of the app, I'm seeing the MyObservations empty screen load briefly before being replaced by the grid/list view.

**To Reproduce**
1. Launch app and wait for MyObservations to load
2. Empty screen will flash briefly

**Expected behavior**
Screen shouldn't load anything without knowing whether or not there is a current user & whether there are any observations, so the correct screen loads from the start.

**Comment by kueda** [comment]
Are you still seeing this, @albullington? I'm not in the latest build.

**Comment by albullington** [comment]
Yes, still seeing this when I log out and log in -- on the first load of MyObs the header shows that I'm logged in, while the rest of the screen shows the no observations state. A few seconds later, the observations list loads and replaces the no observations state. I think we need to show a loading wheel or skeleton state instead of the empty state.

![IMG_2907](https://github.com/inaturalist/iNaturalistReactNative/assets/35536439/38e9c444-ec4e-4f2c-b29a-0569e892d5c2)
