### ISSUE TITLE
Photos disappearing from saved observations

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#759]
**Describe the bug**
In [v0.10.0+53](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.10.0%2B53), the photos I take on a hike and save for later seem to be disappearing. The observation is saved, but the photo on MyObservations shows up blank.

**To Reproduce**
1. Go to AR Camera and take a handful of photo observations.
2. Save them on ObsEdit
3. Close and reopen the app at a later time
4. Observations will display without photos on MyObservations
5. Uploads will stall instead of completing or erroring out

**Expected behavior**
Photos should be saved for later upload

**Screenshots**
![IMG_3154](https://github.com/inaturalist/iNaturalistReactNative/assets/35536439/a60de2ed-8521-4e04-9c03-60bc0dc43504)

**Context (please complete the following information):**
 - Device: iPhone XS

**Additional context**
TBD on whether this still happens in the latest version, but I suspect it will

**Comment by budowski** [comment]
@albullington - couldn't recreate this with latest version. If this is still happening to you - could you privately send me some logs? 🙏

**Comment by albullington** [comment]
I think this is no longer happening in [v0.20.0+68](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.20.0%2B68), so will close as unplanned.
