### ISSUE TITLE
Add an ID background color

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#768]
The background of the "Add an ID" button on ObsCreate should be not filled when an iconic taxon is selected. Similarly the button text color should not be white then.

From Figma:

![image](https://github.com/inaturalist/iNaturalistReactNative/assets/17345891/5b3a4c8d-bde6-4041-a8a5-84a897cf85b1)

**Comment by albullington** [comment]
This one might be related to #755 where ADD AN ID appears selected when a user's phone is in dark mode.
