### ISSUE TITLE
Iconic taxa do not show default photo

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#769]
Some iconic taxa, e.g. plants, have no default photo showing when being selected in ObsCreate. When you switch from a Taxon with picture to one without, eg from Fungi to Plant the photo prevails.

![image](https://github.com/inaturalist/iNaturalistReactNative/assets/17345891/f0026bb9-25d2-4c2b-84ca-054e2c8e2527)

**Comment by kueda** [comment]
This might be feature creep, but another useful change might be to make it so the `<DisplayTaxon>` component shows the iconic taxon *icon* if it doesn't have a photo. That should work even while offline.
