### ISSUE TITLE
DQA screen shows an error modal on navigating there

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#770]
When I navigate to the dqa screen there is an error modal popping up even though I have made no change request.

https://github.com/inaturalist/iNaturalistReactNative/assets/17345891/9fa2bdca-b92a-40e7-a987-6a5e52b8fb3a

**Comment by kueda** [comment]
FWIW, I can't replicate this in a simulated iPhone, on my physical iPad, or on my physical Pixel 3. I was viewing the DQA from obs detailed accessed via MyObs. Can you provide more details that might help folks reproduce this?

**Comment by jtklein** [comment]
OK, I could actually also only replicate this when the phone is offline.

So, I can replicate now with:
Real device, iPhone8
Airplane mode
Navigate 1) App open, 2) Any observation in obs list, 3) Details, 4) View DQA
=> the error message in the modal is saying that the phone is offline but I assume no vote has happened contrary to the error message
