### ISSUE TITLE
Jumping modal in Agree with ID - Add comment

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#771]
When clicking on the "Agree with ID" button and then on Add comment the comment modal keeps jumping up and down.

https://github.com/inaturalist/iNaturalistReactNative/assets/17345891/e5c84a7b-bb45-42d8-8591-fb39273763db

**Comment by kueda** [comment]
I'm struggling to reproduce this one too. Could you add some more detail? Like are you on Explore or MyObs?
