### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#807]
The only amendments I'll make to the [designs](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?type=design&node-id=3110-19528&mode=design&t=ez0bvIRRMEFSRNLr-4) are

1. Try to use the model results, not the API, so it works quickly and offline
1. Omit the location-specific stuff like "Include taxa not expected nearby" and the Geomodel scores... since we don't know how to incorporate the Geomodel yet
1. Don't show the Compare button. I think that merits a separate issue we should work on after Suggestions are in a usable state
1. The attribution text at the bottom can appear asynchronously and *does* require an API request to get the top 3 observers or identifiers for all the taxa presented, so that's going to be something like https://api.inaturalist.org/v2/observations/observers?taxon_ids=12937,27250&fields=user.login,user.name (these data do *not* need to be stored in the database). I think in the Android app we just randomly choose observers or identifiers.

**Comment by albullington** [comment]
Screens are done, but we still need to do the first step here (make this work with model results, not the API.

**Comment by jtklein** [comment]
Prerequisite for receiving predictions on an image from disk, i.e. offline mode, [here](https://github.com/inaturalist/vision-camera-plugin-inatvision/issues/8).
