### ISSUE TITLE
Can't back out of TaxonDetail from AddID

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#817]
**Describe the bug**
When you navigate to TaxonDetail from AddID, there is no back button and the system Android back button closes the app.

**To Reproduce**
1. Start a new obs with no media
2. Tap on "ADD AN ID"
3. Enter a query that shows some taxa
4. Tap on the "i" button to navigate to TaxonDetail
5. On TaxonDetail there is no back button, and on Android the system back button closes the app, so you can't navigate back to AddID or the observation you were adding

**Expected behavior**
You should be able to get back to AddID and your observation, otherwise you could lose work.

**Context (please complete the following information):**
 - Device: iPad Air (5th gen)
 - OS: iPadOS 16.6.1
 - App version: 0.13.2 (59)

**Comment by albullington** [comment]
Fixed in #821
