### ISSUE TITLE
Fetch and cache available locales from the API

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#83]
Pending https://github.com/inaturalist/iNaturalistAPI/issues/322, fetch and store the locales a user can associate with their account in the Settings screen. Caching the data is necessary for the Settings screen to work offline, but we should update that cache every time the user views the Settings screen and has an Internet connection (or if that seems like too much, maybe just check if we haven't checked in a week or something). This will allow us to ensure the user can always choose the locales they can choose on the website, and that the app can always handle the locale of an existing user account that might have last been updated on the web.

This also depends on the merging of https://github.com/inaturalist/iNaturalistReactNative/pull/77, which species these locales in a file.

Also need to add locale as a setting outside of the webview.

**Comment by kueda** [comment]
@abhasinat I'm not sure this is still relevant with the webview approach to settings. Is the webview a stopgap or are we going to keep it for the foreseeable future? Maybe locale is one of those settings that we should pull out of the webview? If so, this issue is still relevant.

**Comment by abhasinat** [comment]
I want the webview to be used for the forseeable future. I'm happy to pull things like this out of the webview (like names) if it feels relevant/important.

**Comment by kueda** [comment]
Top-level locale setting might not be necessary, so closing for now.
