### ISSUE TITLE
Photos can't be deleted from camera preview

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#837]
Replicate by:
1. Go to standard camera
2. Take photos
3. Long press to bring up delete mode
4. Tap again to try to delete a photo
5. Nothing happens

Here are the [details](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?type=design&node-id=1983-15273&mode=design&t=bUV5a5Sj1znSoAMS-0) on what is supposed to happen when a photo gets deleted.

I think this is happening because the photo FlatList is covered by [this Modal](https://github.com/inaturalist/iNaturalistReactNative/blob/8df67b8992c3eb44dc409d4cedef26fd8f2d4878/src/components/Camera/StandardCamera/PhotoCarousel.js#L231), which means the items in the FlatList are no longer pressable.

**Comment by abhasinat** [comment]
It looks like the tappable area for the delete button is closer to the top right corner of the image (like we had in the old designs), even though we moved the delete icon to the center of the image.

**Comment by jtklein** [comment]
I was also able to tap the delete button in the other corners. So, maybe everything except the icon buttons is the tappable area.
