### ISSUE TITLE
Importing a photo generated in the app does not import the date

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#848]
**Describe the bug**
Importing a photo that was generate by this app does not populate the date.

**To Reproduce**
1. Take a photo using the StandardCamera and save the obs
2. Confirm that the photo was saved out in a photos app (e.g. Apple Photos or Google Photos) and confirm that it has a date
3. Add a new obs by importing a photo
4. Import the photo you took in the app
5. The date field does not get filled in

**Expected behavior**
Photos that this app generates should write enough metadata that they can be imported again as additional observations. This definitely applies to the date, but also the coordinates.

**Context (please complete the following information):**
 - Device: iPad Air (5th gen)
 - OS: iPadOS 16.6.1
 - App version: [v0.15.0+61](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.15.0%2B61)

**Additional context**
I'm not sure if this is an export or an import problem. If it's an import problem it *might* be solved in https://github.com/inaturalist/iNaturalistReactNative/pull/828

**Comment by jtklein** [comment]
I can not replicate this on my iPad with version 0.16.0 which includes #828.
Was this only on iPad or also on Android? Can you still reproduce this on your specific device?

**Comment by budowski** [comment]
Cannot recreate this with latest version (tried both Android and iPhone physical devices) - @kueda / @jtklein - still not working for you?

**Comment by kueda** [comment]
Yes, I can still replicate on my iPad Air, and also on an iPhone SE (3rd Gen).

**Comment by kueda** [comment]
TODO, replicate and check the logs, see if there's anything there.

**Comment by kueda** [comment]
Ok, I can replicate this on an iPhone SE. I've spent the last two days investigating what's going on and my conclusion is that at least on an iPhone SE, when you take a photo in the StandardCamera and save the observation, the `DateTimeOriginal` EXIF tag never gets written, which is what react-native-exif-reader uses to populate the `date` attribute it returns from its `readExif()` method.

IMO, the quickest fix would be to write the `DateTimeOriginal` tag like we write the GPS tags, but I am blocked in that by a [bug that creates duplicate photos when you write EXIF](https://github.com/inaturalist/react-native-exif-reader/issues/5).

Alternatively, we could update that library to return the GPS timestamp if DateTimeOriginal isn't there, but that's just a hack around the real problem that our camera isn't writing the EXIF tags that it should, certainly not the minimum set that the Apple Camera app does.

Anyway, this issue can't proceed until https://github.com/inaturalist/react-native-exif-reader/issues/5 is done.

**Comment by jtklein** [comment]
I can now replicate this bug with iPhone 12 using iOS 17.2
But I could still not replicate it with iPhone 7 using iOS 15.x

**Comment by carrieseltzer** [comment]
Still happening consistently on iPhone 13 Pro, iOS 17.3.1

**Comment by kueda** [comment]
Pretty sure this was fixed in #1268
