### ISSUE TITLE
LocationPicker should not have a maximum zoom

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#849]
**Describe the bug**
Currently when I zoom in on an iPad I can only get to about 68m of accuracy before I can't zoom in any further but on my Pixel 3 I can get down about as far as 17m, which seems about as far as I can zoom in on Google Maps. We should let people zoom in as far as the map library will allow.

**To Reproduce**
1. On an iPad or simulated iPad, make a new obs w/ no media and edit the location to enter the LocationPicker
2. Zoom in to a familiar place as far as you can go
3. Note that you can't get past 68 m of accuracy in portrait mode

**Expected behavior**
You should be able to zoom in at least as far as you can in Google Maps, further if that's possible.

**Context (please complete the following information):**
 - Device: iPad Air (5th gen)
 - OS: iPadOS 16.6.1
 - App version: [v0.15.0+61](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.15.0%2B61)

**Additional context**
This might just be an iPad issue, but I suspect it's more dependent on screen size.

**Comment by budowski** [comment]
After debugging this for a while - found it this was like this in the original Apple Maps as well - for example, in your repro steps - if you open up the built-in Apple Maps, you'll hit the same zoom limit - you can zoom less when you're in landscape mode.

**Comment by kueda** [comment]
Yeah, I can't replicate this in [v0.17.1+64](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.17.1%2B64). Sorry for the wild goose chase, Yaron!
