### ISSUE TITLE
Observations show upload button and incorrect no photos icon on Explore

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#852]
**Describe the bug**
Explore grid view is showing the "no photos" icon for observations with photos, and both grid and list views are showing the upload button for all observations.

**To Reproduce**
1. Go to Explore
2. In list view, note that all observations have the upload button (up arrow surrounded by a dotted circle)
3. In grid view, note that all observations have the upload button (up arrow surrounded by a dotted circle) and all observations have the "no photos" icon in the upper right.

**Expected behavior**
Explore should never provide the option to upload unless you have permission to edit that observation (e.g. you created the observation), and perhaps never (check with Abhas if he wants to support upload from Explore).

The "no photos" icon should only appear if the observation has no photos.

**Screenshots**
![IMG_0186](https://github.com/inaturalist/iNaturalistReactNative/assets/22691/aa9be0c1-69a9-410b-835b-45585222a779)
![IMG_0187](https://github.com/inaturalist/iNaturalistReactNative/assets/22691/5fe2b39b-0468-4bb4-b524-b28f2b54e725)

**Context (please complete the following information):**
 - Device: iPad Air (5th gen)
 - OS: iPadOS 16.6.1
 - App version: [v0.15.0+61](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.15.0%2B61)

**Additional context**
I realize Explore isn't fully designed yet, but I think the obs grid/list will remain pretty much the same so we should fix these.

**Comment by angielt** [comment]
@abhasinat Do we want to support upload from the Explore screen?

**Comment by abhasinat** [comment]
I'm assuming you mean the upload button in the tab bar, or the tab bar in general? Yep, I think we should support it on explore. Only screens that lay on top of everything else (obs edit, explore filters, etc) don't have the tab bar.

**Comment by kueda** [comment]
@abhasinat, this issue is about the upload buttons on individual observation items that appear in Explore (see the screenshots in the OP). We can discuss if you want, but I'm strongly opposed to to supporting that in Explore. As far as I can tell from the designs there is no upload button in the tab bar (maybe you're referring to the Add Obs button?).

**Comment by abhasinat** [comment]
Ah, I thought this was already explained in the issue and angie was asking about something in addition to it.

Yes, the upload buttons next to each obs item in explore are a mistake. On explore, a user should only ever see the obs list status (with quality grade, number of comments, and number of IDs). Those upload buttons should only ever appear on home screen/my observations.

**Comment by kueda** [comment]
@angielt you removed the upload button, but you also removed the observation status indicators, e.g. the quality grade, number of comments, IDs, etc. Could you please restore them, and write a test the confirms that they are present on Explore and that the upload buttons are not?
