### ISSUE TITLE
StandardCamera can't autofocus in landscape

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#853]
**Describe the bug**
Tap to focus does not work in StandardCamera in landscape mode.

**To Reproduce**
1. Go to the StandardCamera
2. Rotate your device to landscape orientation
3. Point the device such that there are close and distant objects in the field of view
4. Try to focus on a close object and then a distant one. One of them won't work.

**Expected behavior**
Tap to focus should work the same in landscape as it does in portrait, i.e. tapping to focus should focus on the area tapped to the best of the devices ability.

**Screenshots**
Uploading RPReplay_Final1699138782.mp4…

**Context (please complete the following information):**
 - Device: iPad Air (5th gen)
 - OS: iPadOS 16.6.1
 - App version: [v0.15.0+61](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.15.0%2B61)

**Additional context**
It's as bad or worse in Android. Portrait sort of works in Android... sort of.

**Comment by kueda** [comment]
Investigated this today and I couldn't find a good reason this wasn't working, but then I found https://github.com/mrousavy/react-native-vision-camera/issues/2120, ran the rn-vision-camera example app, and realized it's happening in their main branch too, so this might need to wait for an update to that library.

**Comment by griffinbaker12** [comment]
Portrait is similarly problematic for me.

**Comment by kueda** [comment]
@griffinbaker12 what build / commit / device? This should have been addressed in https://github.com/inaturalist/iNaturalistReactNative/pull/923. react-native-vision-camera v2 doesn't have *great* autofocusing, but it should work.

**Comment by griffinbaker12** [comment]
I am on the iPhone 15 Pro on version 3.6.8. It has the effect of blurring the area that I select.

**Comment by kueda** [comment]
We're currently on version 0.17.1+64 of our app, which runs a fork of react-native-vision-camera from the v2 line of that repo. react-native-vision camera v3.6.8 probably will not work, though v3.6.11 might. Either way, StandardCamera *is* focusing now, so I think this is closed. We'll try and keep an eye on focusing if we try to update to v3 of react-native-vision-camera again.
