### ISSUE TITLE
Observation creation flow; Recording Sounds

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#869]
First of all there is a prerequisite list of tasks for this issue:
- [x] Do research on different sound visualizer libraries to use
- [x] Present research to @abhasinat and together pick a library to use

In general, recording a sound in this view should only be temporary and not permanently to disk yet. It should save to disk at the time of uploading the observation.

With this library the list of things to change on the "Sound Recorder" screen are to 1) restyle the elements on the screen according to the recent [designs](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?type=design&node-id=1406-11391&mode=dev), and 2) add functionality to the elements. In particular:
- [x] Screen background restyle
- [x] Title restyle
- [x] ([Not recording](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?type=design&node-id=1597-12466&mode=dev) state) Record button restyle
- [x] (Not recording state) Record button on start recording switches the UI to the "Recording" state
- [x] (Not recording state) Add Close button
- [ ] #1165
- [x] (Not recording state) Add Help button
- [x] (Not recording state) Help button opens the Help bottom sheet
- [x] (Not recording state) Add Help bottom sheet with explanatory texts and close button
- [x] (Not recording state) Add centered explanation text
- [x] (Not recording state) Do not show Finish button
- [x] (Not recording state) Do not show duration
- [x] ([Recording](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?type=design&node-id=1597-12518&mode=dev) state) Pause button restyle
- [x] (Recording state) Pause button press switches the UI to "Recorded" state
- [x] (Recording state) Duration restyle
- [x] (Recording state) Change centered explanation
- [x] (Recording state) Add sound visualization library to show the ongoing recording as per prerequisite tasks
- [x] (Recording state) Hide close button
- [x] (Recording state) Hide Help button
- [x] ([Recorded](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?type=design&node-id=1597-12541&mode=dev) state) Show Close button, Record button, and Help button as in "Not Recording" state
- [ ] (Recorded state) Record button press appends the current sound with new recording [if you think getting the app to append to an existing sound is a lot of work we can discuss if this needs be MVP or punted to later]
- [x] (Recorded state) Show Duration as in "Recording" state
- [x] (Recorded state) Play button restyle
- [x] (Recorded state) change current Play button in a way that on pressing this button the UI changes to the "Sound Viewer" state with the recording being paused at 00:00
- [x] (Recorded state) Change centered explanation
- [x] (Recorded state) Add Refresh button
- [x] (Recorded state) Refresh button press shows Reset bottom sheet. Close button in bottom sheet closes the sheet. Press on reset recording removes the current recording from state and immediately starts a new recording, and closes sheet.
- [x] (Recorded state) current Finish button restyle, is now a checkmark
- [x] (Recorded state) Finish button press navigates to Obs Edit and adds the recorded sound to the observation, make sure sound shows up in Obs Edit (currently it doesn't)
- [x] (Recorded state) Close button on press show Discard bottom sheet. Close button in bottom sheet closes the sheet. Press on discard recording button exits this screen and removes the current recording from app state / or temporary file per your discretion.
- [x] ([Sound Viewer](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?type=design&node-id=1597-16018&mode=dev) state) Change title
- [x] (Sound Viewer state) Add a back button, on press changes the UI back to "Recorded" state.
- [x] (Sound Viewer state) Show checkmark as on "Recorded" state
- [x] (Sound Viewer state) Add a Delete button, on press removes this recording from state and changes the UI back to "Not Recorded" state.
- [x] (Sound Viewer state) Add a Duration and Slider to the center, the Duration text as well as the slider show the current time of the playing recording, and the slider can be dragged to set a time at which to continue playing the recording
- [x] (Sound Viewer state) Add a Play button to start playing this recording. While the recording is playing this button should change to a Pause button, pressing it will pause the playing of the recording.
- [x] (Sound Viewer state) While the recording is not playing, add a text "Paused" to the center

**Comment by kueda** [comment]
> (Recorded state) Record button press appends the current sound with new recording [if you think getting the app to append to an existing sound is a lot of work we can discuss if this needs be MVP or punted to later]

Note that I wasn't able to get the library we're using to reliably restart an existing recording, so I talked it over with Abhas and arrived at a slightly different flow where you can only reset the recording after stopping.
