### ISSUE TITLE
Taxon Detail screen; Photo section

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#871]
In the photo section according to the [designs](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?type=design&node-id=2106-15859&mode=dev) add a kebab (meetballs) menu to the section.
The opened menu has two items:
1) View in browser
On press it should: Opens an external browser with this taxon detail page on web. Opening the external browser should not deeplink back into the app directly, and ideally not show the "Open this page in the app banner", however, if you feel this is out of scope here, feel free to move this part to a separate issue.
2) Share
On press it should: Open the native share modal with a link (same URL as in 1) to this taxon detail page

**Comment by kueda** [comment]
Closed in 1bc128bfc
