### ISSUE TITLE
Taxon Detail map and Taxon Map screen

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#872]
On the Taxon Detail screen, add a map preview component with section header following the [designs](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?type=design&node-id=2255-16637&mode=dev). The map view is a static representation, no interaction apart from pressing is possible, so no pan or zoom. The map preview shows only a region that "makes sense" based on the observations shown. So, the map extent depends on the range of the taxon (plus some padding to look better).
Pressing the map area opens a full screen modal screen on top of the Taxon Detail screen. This screen component needs to be added according to the most recent [designs](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?type=design&node-id=2414-22084&mode=dev). This full screen map is very similar to the Explore map and maybe reused with the same component.

- [x] The styling of the header section follow the Taxon Detail screen, therefore requires these issues (#871 and #873).
- [x] Add a Close button that on press closes this modal screen and shows Taxon Detail again.
- [x] Add a Map component to the screen. The map should pan and zoom. Even though the design specs show different shapes and polygons we only need to show all observations of this taxon worldwide. The design of how to show those observations is the same as on the Explore screen map.
- [x] Add a Maplayer button. On pressing this button the map toggles between Map and Satellite on iOS and Map, Satellite, and Terrain layers on Android.
- [x] Add a CurrentLocation button. On press is the same as on Explore screen map.

**Comment by abhasinat** [comment]
I was imagining pan & zoom on this map, same as the other maps in the app so far, just with the header for the taxon on top of it.

**Comment by kueda** [comment]
@budowski IDK if you've started on this yet, but a few minor alterations given that the maps on TaxonDetails are so similar to the ones on ObsDetails

- [ ] Move `ObsDetails/DetailsTab/DetailsMap.js` into a more generalized place, e.g. `SharedComponents/DetailsMap.js`
- [ ] Some of the view-specific logic in `ObsDetails/DetailsTab/DetailsMapContainer.js`(e.g. `cycleMapTypes`) needs to move into DetailsMap.js. Stuff that remains specific to ObsDetails context can stay
- [ ] Add a new DetailsMapContainer for TaxonDetails
- [ ] DetailsMap should only show the share and copy buttons if it was given coordinates to show a map marker for
- [ ] The header should probably become a prop specified by the container
- [ ] If possible, set the custom header using `navigation.setOptions` (does `navigation.setOptions( headerTitle: CustomComponent )` work?)
