### ISSUE TITLE
Taxon Detail screen; Media Viewer

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#875]
On the Taxon Detail, when pressing the photo section (but not the buttons nested inside), the app should navigate to the Media Viewer screen. The Media Viewer for taxon details has a different layout than when accessing the Media Viewer from observation photos, current designs [here](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?type=design&node-id=8585-34909&mode=dev). Given a taxon ID this component needs to fetch the photos for this taxon from the API.

Similar to #862, the Media Viewer should:

- [x] The styling of the header section follows the Taxon Detail screen, therefore requires these issues (#871 and #873). Also see #872.
- [x] Tapping on a photo on ObsDetail should take the user to the MediaViewer
- [x]  The MediaViewer should not show any edit controls (currently only the delete button)
- [x]  Tapping on the second photo on ObsDetail should open the MediaViewer and show the second photo
- [x] Try opening the MediaViewer in a [React Navigation modal](https://reactnavigation.org/docs/modal/).
- [x] Similar to the web version of this element, the bottom area contains all taxon photos and is swipeable. The list should fetch only an initial set of photos and then paginate on reaching the end of the swipeable list shown. (E.g. https://www.inaturalist.org/taxa/122866-Cucurbita-maxima). In other words, the list at the bottom is horizontally scrollable. the image in the viewer is highlighted with a white border, and clicking an image opens that image in the viewer.
- [x] The inital full photo shown in the center is the standard photo for the taxon.
- [x] Pressing on any thumbnail on the swipeable list show this photo (in a higher resolution that makes sense) in the center section.
- [x] The center section of full photos is also swipeable, and swiping through the center section photos should also update the state of the highlighted photo in the lower section.
- [x] On top of the photo in the center is a Copyright button. When pressed this opens a native modal titled “Copyright” and populated with the string that expresses media copyright for this particular image. There should be only one CTA button that should say “OK”.

**Comment by kueda** [comment]
> Tapping on a photo on ObsDetail should take the user to the MediaViewer

I'm assuming this is a typo and the intent was "Tapping on a photo on TaxonDetail should take the user to the MediaViewer"

> The list should fetch only an initial set of photos and then paginate on reaching the end of the swipeable list shown

FWIW, a taxon can only have 12 TaxonPhotos, so there's no reason to paginate... unless the intent was to show photos from observations like we do at https://www.inaturalist.org/taxa/122866-Cucurbita-maxima/browse_photos. If so, I think that merits a separate issue.

**Comment by jtklein** [comment]
Yes, correct was an error in copying over the issue text.

I was not aware of the 12 photos limit for taxa, so no pagination required I would agree.
