### ISSUE TITLE
Obs Detail screen; observation with sound first

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#885]
When a user lands on an observation with a sound as the first piece of media. In the top section of the Obs Detail screen, show the play button and duration controls, according to the recent [designs](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?type=design&node-id=8379-46076&mode=dev). The screen starts in "Paused" state.
When tapped, the sound starts to play, and the UI switches to the pause "Playing" state. The Playing state shows a Pause button instead of the Play button, which when tapped pauses the playing of the sound.
In the Playing state, the Duration text as well as the slider show the current time of the playing recording, and the slider can be dragged to set a time at which to continue playing the recording after release of the sliding motion.

When the observation has multiple media, swiping to the next photo/or sound should not loose the state of the current paused time if playing the sound has been paused.

**Comment by kueda** [comment]
Some stuff that I spun off from this issue:

* https://github.com/inaturalist/iNaturalistReactNative/issues/1068
* https://github.com/inaturalist/iNaturalistReactNative/issues/1069
* https://github.com/inaturalist/iNaturalistReactNative/issues/1070
