### ISSUE TITLE
Explore screen; navigating from User Profile to Explore with filters applied

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/iNaturalistReactNative#894]
A user can navigate from User Profiles to explore by:
- clicking the "Observations" section at the top to open the obs list view of all organisms worldwide by that user
- clicking the "Species" section at the top to open the species view of all organisms worldwide by that user

When navigating from the User Profile screen to the Explore screen:
- Send the current user's id as navigation param to the Explore page.
- Receive the id in the Explore screen and set the Explore filter of user to this id. Requires https://github.com/inaturalist/iNaturalistReactNative/issues/886
- Ensure that only observations by this user are retrieved, worldwide.

**Comment by jtklein** [comment]
@abhasinat The second bullet point should read Species instead of Observations?

**Comment by abhasinat** [comment]
yep, corrected. thanks!
