### ISSUE TITLE
Top-align ObsStatus

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#895]
On Home screen in the observation list the ObsStatus element showing the number of ids and quality grade needs to be top-aligned, as per the current [designs](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?type=design&node-id=354-8027&mode=dev).

**Comment by kueda** [comment]
Presumably this also applies to Explore.

**Comment by jtklein** [comment]
Correct, this also applies to Explore.
