### ISSUE TITLE
Explore screen; Map layer button

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#896]
Similar to #872 add a Maplayer button to the Explore screen, as per the current [designs](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?type=design&node-id=7063-35744&mode=dev). On pressing this button the map toggles between Map and Satellite on iOS and Map, Satellite, and Terrain layers on Android.

**Comment by kueda** [comment]
@jtklein and @abhasinat did we really want different functionality on iOS (Map & Satellite) and Android (Map, Terrain, & Satellite)? That's no in the designs, FWIW. If that's what we want, I'll re-open this.

**Comment by jtklein** [comment]
Yes, the decision was taken because iOS native Maps app has Map & Satellite only, whereas Google Maps being the standard on Android has Map, Terrain & Satellite.
However, since now Map to Satellite is implemented, maybe @abhasinat might decide to punt the addition of Terrain to post-MVP?

**Comment by abhasinat** [comment]
that's fine with me if that makes implementation easier.
