### ISSUE TITLE
Replace App Icons

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#897]
Before MVP launch the app icons have to be replaced with a different icon for both Android and iOS.

Current prerequisite: needs designs @abhasinat

- [x] Android (794b014e157917033f1cc432f582e7c794a6cb5f and ecbe6fd53b0c0e5739b3fef66d118e0ded244e8c, but w/ the caveat that this messes up the default splash screen)
- [ ] iOS

**Comment by abhasinat** [comment]
Here are updated files to use for the App Icon:

[iOS App Icons - 011124.zip](https://github.com/inaturalist/iNaturalistReactNative/files/13903694/iOS.App.Icons.-.011124.zip)

**Comment by kueda** [comment]
For Android we'll need an SVG.

**Comment by abhasinat** [comment]
![iNatRN-AppIcon](https://github.com/inaturalist/iNaturalistReactNative/assets/44380775/d5faf52d-9716-4f08-bdb4-61939326c91e)

**Comment by abhasinat** [comment]
Sent those in slack.
