### ISSUE TITLE
Bulk Uploader should not remember photos chosen after observations saved

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#90]
To replicate

1. Enter the Bulk Uploader and choose a photo
2. Proceed to the Group Photos screen and just tap "Next" to land on Obs Edit
3. Tap "Save" to save the observation
4. Enter the Bulk Uploader again; the photo you selected is still selected; instead, nothing should be selected because you are starting a new import

There may be some need to preserve the selection state when backing out from the Group Photos screen, or even from Obs Edit at the end of the new observation flow (@abhasinat?), but after you've saved an observation I think that state should definitely be cleared.

**Comment by abhasinat** [comment]
Yes, when backing out to the gallery from the select/group photos screen, the selection state should be preserved. When backing out of obs edit, I think it would be nice to be able to go back to the group/select photos screens if a user used the bulk uploader.

**Comment by albullington** [comment]
I think this one has already been fixed
