### ISSUE TITLE
Viewed_updates hook getting called repeatedly

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#967]
**Describe the bug**
When a user goes to ObsDetails, the viewed_updates endpoint is getting called an infinite number of times on certain observations. I believe this has to do with the useEffect hook dependencies changing, so this hook keeps getting called over and over.

`LOG  10:34:34 AM | INatApiError | ERROR : Error requesting https://api.inaturalist.org/v2/observations/[OBSERVATION]/viewed_updates (status: 401): [object Object]`

**To Reproduce**
1. Go to MyObservations as a logged in user
2. Tap on an existing observation -- I chose an observation with an unknown taxon, which was already synced to the server
3. From ObsDetails, tap on the ObsEdit pencil. On ObsEdit, you'll receive an infinite number of warnings, blocking the bottom of the screen

**Expected behavior**
This endpoint should only be called once when a user first lands on ObsDetails.

**Context (please complete the following information):**
 - Device: iPhone 15 Plus simulator, iOS 17
 - OS: iOS
 - App version: v0.18.1+66

**Comment by kueda** [comment]
@albullington, since you filed it but can no longer replicate it, please go ahead and "close as not planned"
