### ISSUE TITLE
positional_accuracy not getting submitted for new obs

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#973]
**Describe the bug**
`positional_accuracy` field is not getting submitted when creating new observations.

**To Reproduce**
1. Sign in
1. Make a new observation without evidence
1. Confirm that the coordinates *and* accuracy get recorded
1. Tap "SAVE"
1. Tap "Upload 1 observation" in the toolbar
1. Look at the observation on the website (click Details under the map) and the accuracy is listed as "Not recorded"

**Expected behavior**
`positional_accuracy` should always be submitted when available.

**Context (please complete the following information):**
 - Device: iPad Air (5th gen)
 - OS: iPadOS 17.1.2
 - App version: 0.19.0 (67)

**Additional context**
Happens on Android too. Also happens when adding a new photo with the StandardCamera.

**Comment by albullington** [comment]
Closed by PR #988
