### ISSUE TITLE
Endless spinner when adding a photo to an existing observation

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#993]
**Describe the bug**
You see an endless spinner when you try to add a photo to an existing observation (one downloaded from the web).

**To Reproduce**
1. Sign in to an account with existing observations; allow existing observations to download
2. Edit an existing observation with a photo to get to ObsEdit
3. Tap the "+" button next to the existing photo
4. Tap the gallery button in the bottom sheet
5. Choose a photo and tap "Add"  in the upper right
6. You see a blank white screen with a green loading spinner that spins forever

**Expected behavior**
You should be able to add photos to existing observations just like you can for new observations.

**Context (please complete the following information):**
 - Device: iPad Air (5th gen)
 - OS: iPadOS 16.6.1
 - App version: [v0.19.0+67](https://github.com/inaturalist/iNaturalistReactNative/releases/tag/v0.19.0%2B67)

**Additional context**
Happens on Android too. While trying to replicate I occasionally got a crash immediately after tapping the "+" button so that's worth investigating too. In the log it looks like `Error: Accessing object which has been invalidated or deleted` so another fun Realm error.

**Comment by albullington** [comment]
Note for @budowski : there's a PR open that may address this issue: https://github.com/inaturalist/iNaturalistReactNative/pull/998

**Comment by joergmlpts** [comment]
This issue does not occur anymore in v0.20.0+68. The PR for issue #918 appears to have fixed this as well.

**Comment by kueda** [comment]
Closed in #998
