### ISSUE TITLE
StickyView only works with headers that are as tall or shorter than the tab bar

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#997]
The current approach in sticky view is to set the content to the height of the screen, which makes it flow under the tab bar, and then translate it up as the user scrolls until the user has scrolled to `heightAboveView` pixels, which means the header has been translated off screen.

However, since this approach translates the entire contents, including the ScrollView, this creates a gap at the bottom of the view that's `heightAboveView` pixels tall when fully scrolled. This sort of works at present if `heightAboveView` is shorter than the tab bar, because the gap is hidden by the tab bar, but it creates problems in Explore where the header being hidden is a bit taller, and on the map view, where there is no scrolling and the map is flowing under the tab bar anyway, making it hard to layout buttons.

My requirements here are

- [x] StickyView should work without flowing under the tab bar
- [x] Should support `heightAboveView` value that's greater than the height of the footer
- [x] Should never show a white gap at the bottom

**Comment by kueda** [comment]
Actually, is it possible we could just replace this with https://reactnative.dev/docs/scrollview#stickyheaderindices?

**Comment by albullington** [comment]
Explore screen addressed in https://github.com/inaturalist/iNaturalistReactNative/pull/1030. MyObservations still uses StickyView.
